/* This file is code generated. */

import SwiftUI
import UIKit
@_exported import SDDSThemeCore

public enum Gradients {
    case surfaceDefaultAccentGradient
    case surfaceDefaultAccentGradientActive
    case surfaceDefaultAccentGradientHover
    case surfaceDefaultSkeletonDeepGradient
    case surfaceDefaultSkeletonDeepGradientActive
    case surfaceDefaultSkeletonDeepGradientHover
    case surfaceDefaultSkeletonGradient
    case surfaceDefaultSkeletonGradientActive
    case surfaceDefaultSkeletonGradientHover
    case surfaceInverseAccentGradient
    case surfaceInverseAccentGradientActive
    case surfaceInverseAccentGradientHover
    case surfaceInverseSkeletonDeepGradient
    case surfaceInverseSkeletonDeepGradientActive
    case surfaceInverseSkeletonDeepGradientHover
    case surfaceInverseSkeletonGradient
    case surfaceInverseSkeletonGradientActive
    case surfaceInverseSkeletonGradientHover
    case surfaceOnDarkAccentGradient
    case surfaceOnDarkAccentGradientActive
    case surfaceOnDarkAccentGradientHover
    case surfaceOnDarkSkeletonDeepGradient
    case surfaceOnDarkSkeletonDeepGradientActive
    case surfaceOnDarkSkeletonDeepGradientHover
    case surfaceOnDarkSkeletonGradient
    case surfaceOnDarkSkeletonGradientActive
    case surfaceOnDarkSkeletonGradientHover
    case surfaceOnLightAccentGradient
    case surfaceOnLightAccentGradientActive
    case surfaceOnLightAccentGradientHover
    case surfaceOnLightSkeletonDeepGradient
    case surfaceOnLightSkeletonDeepGradientActive
    case surfaceOnLightSkeletonDeepGradientHover
    case surfaceOnLightSkeletonGradient
    case surfaceOnLightSkeletonGradientActive
    case surfaceOnLightSkeletonGradientHover
    case textDefaultAccentGradient
    case textDefaultAccentGradientActive
    case textDefaultAccentGradientHover
    case textInverseAccentGradient
    case textInverseAccentGradientActive
    case textInverseAccentGradientHover
    case textOnDarkAccentGradient
    case textOnDarkAccentGradientActive
    case textOnDarkAccentGradientHover
    case textOnLightAccentGradient
    case textOnLightAccentGradientActive
    case textOnLightAccentGradientHover

    public var token: GradientToken {
        switch self {
        case .surfaceDefaultAccentGradient:
            return .surfaceDefaultAccentGradient
        case .surfaceDefaultAccentGradientActive:
            return .surfaceDefaultAccentGradientActive
        case .surfaceDefaultAccentGradientHover:
            return .surfaceDefaultAccentGradientHover
        case .surfaceDefaultSkeletonDeepGradient:
            return .surfaceDefaultSkeletonDeepGradient
        case .surfaceDefaultSkeletonDeepGradientActive:
            return .surfaceDefaultSkeletonDeepGradientActive
        case .surfaceDefaultSkeletonDeepGradientHover:
            return .surfaceDefaultSkeletonDeepGradientHover
        case .surfaceDefaultSkeletonGradient:
            return .surfaceDefaultSkeletonGradient
        case .surfaceDefaultSkeletonGradientActive:
            return .surfaceDefaultSkeletonGradientActive
        case .surfaceDefaultSkeletonGradientHover:
            return .surfaceDefaultSkeletonGradientHover
        case .surfaceInverseAccentGradient:
            return .surfaceInverseAccentGradient
        case .surfaceInverseAccentGradientActive:
            return .surfaceInverseAccentGradientActive
        case .surfaceInverseAccentGradientHover:
            return .surfaceInverseAccentGradientHover
        case .surfaceInverseSkeletonDeepGradient:
            return .surfaceInverseSkeletonDeepGradient
        case .surfaceInverseSkeletonDeepGradientActive:
            return .surfaceInverseSkeletonDeepGradientActive
        case .surfaceInverseSkeletonDeepGradientHover:
            return .surfaceInverseSkeletonDeepGradientHover
        case .surfaceInverseSkeletonGradient:
            return .surfaceInverseSkeletonGradient
        case .surfaceInverseSkeletonGradientActive:
            return .surfaceInverseSkeletonGradientActive
        case .surfaceInverseSkeletonGradientHover:
            return .surfaceInverseSkeletonGradientHover
        case .surfaceOnDarkAccentGradient:
            return .surfaceOnDarkAccentGradient
        case .surfaceOnDarkAccentGradientActive:
            return .surfaceOnDarkAccentGradientActive
        case .surfaceOnDarkAccentGradientHover:
            return .surfaceOnDarkAccentGradientHover
        case .surfaceOnDarkSkeletonDeepGradient:
            return .surfaceOnDarkSkeletonDeepGradient
        case .surfaceOnDarkSkeletonDeepGradientActive:
            return .surfaceOnDarkSkeletonDeepGradientActive
        case .surfaceOnDarkSkeletonDeepGradientHover:
            return .surfaceOnDarkSkeletonDeepGradientHover
        case .surfaceOnDarkSkeletonGradient:
            return .surfaceOnDarkSkeletonGradient
        case .surfaceOnDarkSkeletonGradientActive:
            return .surfaceOnDarkSkeletonGradientActive
        case .surfaceOnDarkSkeletonGradientHover:
            return .surfaceOnDarkSkeletonGradientHover
        case .surfaceOnLightAccentGradient:
            return .surfaceOnLightAccentGradient
        case .surfaceOnLightAccentGradientActive:
            return .surfaceOnLightAccentGradientActive
        case .surfaceOnLightAccentGradientHover:
            return .surfaceOnLightAccentGradientHover
        case .surfaceOnLightSkeletonDeepGradient:
            return .surfaceOnLightSkeletonDeepGradient
        case .surfaceOnLightSkeletonDeepGradientActive:
            return .surfaceOnLightSkeletonDeepGradientActive
        case .surfaceOnLightSkeletonDeepGradientHover:
            return .surfaceOnLightSkeletonDeepGradientHover
        case .surfaceOnLightSkeletonGradient:
            return .surfaceOnLightSkeletonGradient
        case .surfaceOnLightSkeletonGradientActive:
            return .surfaceOnLightSkeletonGradientActive
        case .surfaceOnLightSkeletonGradientHover:
            return .surfaceOnLightSkeletonGradientHover
        case .textDefaultAccentGradient:
            return .textDefaultAccentGradient
        case .textDefaultAccentGradientActive:
            return .textDefaultAccentGradientActive
        case .textDefaultAccentGradientHover:
            return .textDefaultAccentGradientHover
        case .textInverseAccentGradient:
            return .textInverseAccentGradient
        case .textInverseAccentGradientActive:
            return .textInverseAccentGradientActive
        case .textInverseAccentGradientHover:
            return .textInverseAccentGradientHover
        case .textOnDarkAccentGradient:
            return .textOnDarkAccentGradient
        case .textOnDarkAccentGradientActive:
            return .textOnDarkAccentGradientActive
        case .textOnDarkAccentGradientHover:
            return .textOnDarkAccentGradientHover
        case .textOnLightAccentGradient:
            return .textOnLightAccentGradient
        case .textOnLightAccentGradientActive:
            return .textOnLightAccentGradientActive
        case .textOnLightAccentGradientHover:
            return .textOnLightAccentGradientHover
        }
    }
}
