// This file is auto-generated by scripts/generate_sandbox_stories.py.
// Do not edit manually.

import SandboxCore
import SwiftUI

enum GeneratedStoriesAutogen {
    static func registerAll() {
        StoryRegistry.shared.register(AccordionItemStory.self)
        SandboxStoryRenderRegistry.shared.register(id: AccordionItemStory.id) { theme in
            AnyView(AccordionItemStory.content(state: AccordionItemStory.defaultState, theme: theme))
        }
        StoryRegistry.shared.register(AccordionStory.self)
        SandboxStoryRenderRegistry.shared.register(id: AccordionStory.id) { theme in
            AnyView(AccordionStory.content(state: AccordionStory.defaultState, theme: theme))
        }
        StoryRegistry.shared.register(AutocompleteStory.self)
        SandboxStoryRenderRegistry.shared.register(id: AutocompleteStory.id) { theme in
            AnyView(AutocompleteStory.content(state: AutocompleteStory.defaultState, theme: theme))
        }
        StoryRegistry.shared.register(AvatarGroupStory.self)
        SandboxStoryRenderRegistry.shared.register(id: AvatarGroupStory.id) { theme in
            AnyView(AvatarGroupStory.content(state: AvatarGroupStory.defaultState, theme: theme))
        }
        StoryRegistry.shared.register(AvatarStory.self)
        SandboxStoryRenderRegistry.shared.register(id: AvatarStory.id) { theme in
            AnyView(AvatarStory.content(state: AvatarStory.defaultState, theme: theme))
        }
        StoryRegistry.shared.register(BadgeStory.self)
        SandboxStoryRenderRegistry.shared.register(id: BadgeStory.id) { theme in
            AnyView(BadgeStory.content(state: BadgeStory.defaultState, theme: theme))
        }
        StoryRegistry.shared.register(BottomSheetStory.self)
        SandboxStoryRenderRegistry.shared.register(id: BottomSheetStory.id) { theme in
            AnyView(BottomSheetStory.content(state: BottomSheetStory.defaultState, theme: theme))
        }
        StoryRegistry.shared.register(ButtonGroupStory.self)
        SandboxStoryRenderRegistry.shared.register(id: ButtonGroupStory.id) { theme in
            AnyView(ButtonGroupStory.content(state: ButtonGroupStory.defaultState, theme: theme))
        }
        StoryRegistry.shared.register(ButtonStory.self)
        SandboxStoryRenderRegistry.shared.register(id: ButtonStory.id) { theme in
            AnyView(ButtonStory.content(state: ButtonStory.defaultState, theme: theme))
        }
        StoryRegistry.shared.register(CardStory.self)
        SandboxStoryRenderRegistry.shared.register(id: CardStory.id) { theme in
            AnyView(CardStory.content(state: CardStory.defaultState, theme: theme))
        }
        StoryRegistry.shared.register(CarouselStory.self)
        SandboxStoryRenderRegistry.shared.register(id: CarouselStory.id) { theme in
            AnyView(CarouselStory.content(state: CarouselStory.defaultState, theme: theme))
        }
        StoryRegistry.shared.register(CellStory.self)
        SandboxStoryRenderRegistry.shared.register(id: CellStory.id) { theme in
            AnyView(CellStory.content(state: CellStory.defaultState, theme: theme))
        }
        StoryRegistry.shared.register(CheckboxGroupStory.self)
        SandboxStoryRenderRegistry.shared.register(id: CheckboxGroupStory.id) { theme in
            AnyView(CheckboxGroupStory.content(state: CheckboxGroupStory.defaultState, theme: theme))
        }
        StoryRegistry.shared.register(CheckboxStory.self)
        SandboxStoryRenderRegistry.shared.register(id: CheckboxStory.id) { theme in
            AnyView(CheckboxStory.content(state: CheckboxStory.defaultState, theme: theme))
        }
        StoryRegistry.shared.register(ChipGroupStory.self)
        SandboxStoryRenderRegistry.shared.register(id: ChipGroupStory.id) { theme in
            AnyView(ChipGroupStory.content(state: ChipGroupStory.defaultState, theme: theme))
        }
        StoryRegistry.shared.register(ChipStory.self)
        SandboxStoryRenderRegistry.shared.register(id: ChipStory.id) { theme in
            AnyView(ChipStory.content(state: ChipStory.defaultState, theme: theme))
        }
        StoryRegistry.shared.register(CircularProgressBarStory.self)
        SandboxStoryRenderRegistry.shared.register(id: CircularProgressBarStory.id) { theme in
            AnyView(CircularProgressBarStory.content(state: CircularProgressBarStory.defaultState, theme: theme))
        }
        StoryRegistry.shared.register(CodeFieldStory.self)
        SandboxStoryRenderRegistry.shared.register(id: CodeFieldStory.id) { theme in
            AnyView(CodeFieldStory.content(state: CodeFieldStory.defaultState, theme: theme))
        }
        StoryRegistry.shared.register(CodeInputStory.self)
        SandboxStoryRenderRegistry.shared.register(id: CodeInputStory.id) { theme in
            AnyView(CodeInputStory.content(state: CodeInputStory.defaultState, theme: theme))
        }
        StoryRegistry.shared.register(CollapsingNavigationBarStory.self)
        SandboxStoryRenderRegistry.shared.register(id: CollapsingNavigationBarStory.id) { theme in
            AnyView(CollapsingNavigationBarStory.content(state: CollapsingNavigationBarStory.defaultState, theme: theme))
        }
        StoryRegistry.shared.register(CounterStory.self)
        SandboxStoryRenderRegistry.shared.register(id: CounterStory.id) { theme in
            AnyView(CounterStory.content(state: CounterStory.defaultState, theme: theme))
        }
        StoryRegistry.shared.register(DividerStory.self)
        SandboxStoryRenderRegistry.shared.register(id: DividerStory.id) { theme in
            AnyView(DividerStory.content(state: DividerStory.defaultState, theme: theme))
        }
        StoryRegistry.shared.register(DrawerStory.self)
        SandboxStoryRenderRegistry.shared.register(id: DrawerStory.id) { theme in
            AnyView(DrawerStory.content(state: DrawerStory.defaultState, theme: theme))
        }
        StoryRegistry.shared.register(DropDownMenuStory.self)
        SandboxStoryRenderRegistry.shared.register(id: DropDownMenuStory.id) { theme in
            AnyView(DropDownMenuStory.content(state: DropDownMenuStory.defaultState, theme: theme))
        }
        StoryRegistry.shared.register(EditableStory.self)
        SandboxStoryRenderRegistry.shared.register(id: EditableStory.id) { theme in
            AnyView(EditableStory.content(state: EditableStory.defaultState, theme: theme))
        }
        StoryRegistry.shared.register(IconStory.self)
        SandboxStoryRenderRegistry.shared.register(id: IconStory.id) { theme in
            AnyView(IconStory.content(state: IconStory.defaultState, theme: theme))
        }
        StoryRegistry.shared.register(ImageStory.self)
        SandboxStoryRenderRegistry.shared.register(id: ImageStory.id) { theme in
            AnyView(ImageStory.content(state: ImageStory.defaultState, theme: theme))
        }
        StoryRegistry.shared.register(IndicatorStory.self)
        SandboxStoryRenderRegistry.shared.register(id: IndicatorStory.id) { theme in
            AnyView(IndicatorStory.content(state: IndicatorStory.defaultState, theme: theme))
        }
        StoryRegistry.shared.register(ListItemStory.self)
        SandboxStoryRenderRegistry.shared.register(id: ListItemStory.id) { theme in
            AnyView(ListItemStory.content(state: ListItemStory.defaultState, theme: theme))
        }
        StoryRegistry.shared.register(ListStory.self)
        SandboxStoryRenderRegistry.shared.register(id: ListStory.id) { theme in
            AnyView(ListStory.content(state: ListStory.defaultState, theme: theme))
        }
        StoryRegistry.shared.register(LoaderStory.self)
        SandboxStoryRenderRegistry.shared.register(id: LoaderStory.id) { theme in
            AnyView(LoaderStory.content(state: LoaderStory.defaultState, theme: theme))
        }
        StoryRegistry.shared.register(MaskStory.self)
        SandboxStoryRenderRegistry.shared.register(id: MaskStory.id) { theme in
            AnyView(MaskStory.content(state: MaskStory.defaultState, theme: theme))
        }
        StoryRegistry.shared.register(ModalStory.self)
        SandboxStoryRenderRegistry.shared.register(id: ModalStory.id) { theme in
            AnyView(ModalStory.content(state: ModalStory.defaultState, theme: theme))
        }
        StoryRegistry.shared.register(NavigationBarStory.self)
        SandboxStoryRenderRegistry.shared.register(id: NavigationBarStory.id) { theme in
            AnyView(NavigationBarStory.content(state: NavigationBarStory.defaultState, theme: theme))
        }
        StoryRegistry.shared.register(NoteCompactStory.self)
        SandboxStoryRenderRegistry.shared.register(id: NoteCompactStory.id) { theme in
            AnyView(NoteCompactStory.content(state: NoteCompactStory.defaultState, theme: theme))
        }
        StoryRegistry.shared.register(NoteStory.self)
        SandboxStoryRenderRegistry.shared.register(id: NoteStory.id) { theme in
            AnyView(NoteStory.content(state: NoteStory.defaultState, theme: theme))
        }
        StoryRegistry.shared.register(NotificationStory.self)
        SandboxStoryRenderRegistry.shared.register(id: NotificationStory.id) { theme in
            AnyView(NotificationStory.content(state: NotificationStory.defaultState, theme: theme))
        }
        StoryRegistry.shared.register(OverlayStory.self)
        SandboxStoryRenderRegistry.shared.register(id: OverlayStory.id) { theme in
            AnyView(OverlayStory.content(state: OverlayStory.defaultState, theme: theme))
        }
        StoryRegistry.shared.register(PaginationDotsStory.self)
        SandboxStoryRenderRegistry.shared.register(id: PaginationDotsStory.id) { theme in
            AnyView(PaginationDotsStory.content(state: PaginationDotsStory.defaultState, theme: theme))
        }
        StoryRegistry.shared.register(PopoverStory.self)
        SandboxStoryRenderRegistry.shared.register(id: PopoverStory.id) { theme in
            AnyView(PopoverStory.content(state: PopoverStory.defaultState, theme: theme))
        }
        StoryRegistry.shared.register(ProgressBarStory.self)
        SandboxStoryRenderRegistry.shared.register(id: ProgressBarStory.id) { theme in
            AnyView(ProgressBarStory.content(state: ProgressBarStory.defaultState, theme: theme))
        }
        StoryRegistry.shared.register(RadioboxGroupStory.self)
        SandboxStoryRenderRegistry.shared.register(id: RadioboxGroupStory.id) { theme in
            AnyView(RadioboxGroupStory.content(state: RadioboxGroupStory.defaultState, theme: theme))
        }
        StoryRegistry.shared.register(RadioboxStory.self)
        SandboxStoryRenderRegistry.shared.register(id: RadioboxStory.id) { theme in
            AnyView(RadioboxStory.content(state: RadioboxStory.defaultState, theme: theme))
        }
        StoryRegistry.shared.register(RectSkeletonStory.self)
        SandboxStoryRenderRegistry.shared.register(id: RectSkeletonStory.id) { theme in
            AnyView(RectSkeletonStory.content(state: RectSkeletonStory.defaultState, theme: theme))
        }
        StoryRegistry.shared.register(ScrollbarStory.self)
        SandboxStoryRenderRegistry.shared.register(id: ScrollbarStory.id) { theme in
            AnyView(ScrollbarStory.content(state: ScrollbarStory.defaultState, theme: theme))
        }
        StoryRegistry.shared.register(SegmentElementStory.self)
        SandboxStoryRenderRegistry.shared.register(id: SegmentElementStory.id) { theme in
            AnyView(SegmentElementStory.content(state: SegmentElementStory.defaultState, theme: theme))
        }
        StoryRegistry.shared.register(SegmentStory.self)
        SandboxStoryRenderRegistry.shared.register(id: SegmentStory.id) { theme in
            AnyView(SegmentStory.content(state: SegmentStory.defaultState, theme: theme))
        }
        StoryRegistry.shared.register(SelectStory.self)
        SandboxStoryRenderRegistry.shared.register(id: SelectStory.id) { theme in
            AnyView(SelectStory.content(state: SelectStory.defaultState, theme: theme))
        }
        StoryRegistry.shared.register(SpinnerStory.self)
        SandboxStoryRenderRegistry.shared.register(id: SpinnerStory.id) { theme in
            AnyView(SpinnerStory.content(state: SpinnerStory.defaultState, theme: theme))
        }
        StoryRegistry.shared.register(SwitchStory.self)
        SandboxStoryRenderRegistry.shared.register(id: SwitchStory.id) { theme in
            AnyView(SwitchStory.content(state: SwitchStory.defaultState, theme: theme))
        }
        StoryRegistry.shared.register(TabBarIslandStory.self)
        SandboxStoryRenderRegistry.shared.register(id: TabBarIslandStory.id) { theme in
            AnyView(TabBarIslandStory.content(state: TabBarIslandStory.defaultState, theme: theme))
        }
        StoryRegistry.shared.register(TabBarStory.self)
        SandboxStoryRenderRegistry.shared.register(id: TabBarStory.id) { theme in
            AnyView(TabBarStory.content(state: TabBarStory.defaultState, theme: theme))
        }
        StoryRegistry.shared.register(TabItemStory.self)
        SandboxStoryRenderRegistry.shared.register(id: TabItemStory.id) { theme in
            AnyView(TabItemStory.content(state: TabItemStory.defaultState, theme: theme))
        }
        StoryRegistry.shared.register(TabsStory.self)
        SandboxStoryRenderRegistry.shared.register(id: TabsStory.id) { theme in
            AnyView(TabsStory.content(state: TabsStory.defaultState, theme: theme))
        }
        StoryRegistry.shared.register(TextAreaStory.self)
        SandboxStoryRenderRegistry.shared.register(id: TextAreaStory.id) { theme in
            AnyView(TextAreaStory.content(state: TextAreaStory.defaultState, theme: theme))
        }
        StoryRegistry.shared.register(TextFieldMasksStory.self)
        SandboxStoryRenderRegistry.shared.register(id: TextFieldMasksStory.id) { theme in
            AnyView(TextFieldMasksStory.content(state: TextFieldMasksStory.defaultState, theme: theme))
        }
        StoryRegistry.shared.register(TextFieldStory.self)
        SandboxStoryRenderRegistry.shared.register(id: TextFieldStory.id) { theme in
            AnyView(TextFieldStory.content(state: TextFieldStory.defaultState, theme: theme))
        }
        StoryRegistry.shared.register(TextSkeletonStory.self)
        SandboxStoryRenderRegistry.shared.register(id: TextSkeletonStory.id) { theme in
            AnyView(TextSkeletonStory.content(state: TextSkeletonStory.defaultState, theme: theme))
        }
        StoryRegistry.shared.register(TextStory.self)
        SandboxStoryRenderRegistry.shared.register(id: TextStory.id) { theme in
            AnyView(TextStory.content(state: TextStory.defaultState, theme: theme))
        }
        StoryRegistry.shared.register(ToastStory.self)
        SandboxStoryRenderRegistry.shared.register(id: ToastStory.id) { theme in
            AnyView(ToastStory.content(state: ToastStory.defaultState, theme: theme))
        }
        StoryRegistry.shared.register(ToolbarStory.self)
        SandboxStoryRenderRegistry.shared.register(id: ToolbarStory.id) { theme in
            AnyView(ToolbarStory.content(state: ToolbarStory.defaultState, theme: theme))
        }
        StoryRegistry.shared.register(TooltipStory.self)
        SandboxStoryRenderRegistry.shared.register(id: TooltipStory.id) { theme in
            AnyView(TooltipStory.content(state: TooltipStory.defaultState, theme: theme))
        }
        StoryRegistry.shared.register(WheelStory.self)
        SandboxStoryRenderRegistry.shared.register(id: WheelStory.id) { theme in
            AnyView(WheelStory.content(state: WheelStory.defaultState, theme: theme))
        }
    }
}
