/* This file is code generated. */

import SwiftUI
import UIKit
@_exported import SDDSThemeCore

public enum Gradients {
    case backgroundDefaultMobileAssistantAthena
    case backgroundDefaultMobileAssistantB2E
    case backgroundDefaultMobileAssistantBrand
    case backgroundDefaultMobileAssistantJoy
    case backgroundDefaultMobileAssistantMain
    case backgroundDefaultModalSheet
    case outlineDefaultAccentGradient
    case outlineDefaultAccentGradientActive
    case outlineDefaultAccentGradientHover
    case outlineDefaultAccentMinorGradient
    case outlineDefaultAccentMinorGradientActive
    case outlineDefaultAccentMinorGradientHover
    case outlineDefaultPromoGradient
    case outlineDefaultPromoGradientActive
    case outlineDefaultPromoGradientHover
    case outlineDefaultPromoMinorGradient
    case outlineDefaultPromoMinorGradientActive
    case outlineDefaultPromoMinorGradientHover
    case outlineDefaultTransparentAccentGradient
    case outlineDefaultTransparentAccentGradientActive
    case outlineDefaultTransparentAccentGradientHover
    case outlineInverseAccentGradient
    case outlineInverseAccentGradientActive
    case outlineInverseAccentGradientHover
    case outlineInverseAccentMinorGradient
    case outlineInverseAccentMinorGradientActive
    case outlineInverseAccentMinorGradientHover
    case outlineInversePromoGradient
    case outlineInversePromoGradientActive
    case outlineInversePromoGradientHover
    case outlineInversePromoMinorGradient
    case outlineInversePromoMinorGradientActive
    case outlineInversePromoMinorGradientHover
    case outlineInverseTransparentAccentGradient
    case outlineInverseTransparentAccentGradientActive
    case outlineInverseTransparentAccentGradientHover
    case outlineOnDarkAccentGradient
    case outlineOnDarkAccentGradientActive
    case outlineOnDarkAccentGradientHover
    case outlineOnDarkAccentMinorGradient
    case outlineOnDarkAccentMinorGradientActive
    case outlineOnDarkAccentMinorGradientHover
    case outlineOnDarkPromoGradient
    case outlineOnDarkPromoGradientActive
    case outlineOnDarkPromoGradientHover
    case outlineOnDarkPromoMinorGradient
    case outlineOnDarkPromoMinorGradientActive
    case outlineOnDarkPromoMinorGradientHover
    case outlineOnDarkTransparentAccentGradient
    case outlineOnDarkTransparentAccentGradientActive
    case outlineOnDarkTransparentAccentGradientHover
    case outlineOnLightAccentGradient
    case outlineOnLightAccentGradientActive
    case outlineOnLightAccentGradientHover
    case outlineOnLightAccentMinorGradient
    case outlineOnLightAccentMinorGradientActive
    case outlineOnLightAccentMinorGradientHover
    case outlineOnLightPromoGradient
    case outlineOnLightPromoGradientActive
    case outlineOnLightPromoGradientHover
    case outlineOnLightPromoMinorGradient
    case outlineOnLightPromoMinorGradientActive
    case outlineOnLightPromoMinorGradientHover
    case outlineOnLightTransparentAccentGradient
    case outlineOnLightTransparentAccentGradientActive
    case outlineOnLightTransparentAccentGradientHover
    case surfaceDefaultAccentGradient
    case surfaceDefaultAccentGradientActive
    case surfaceDefaultAccentGradientHover
    case surfaceDefaultAccentMinorGradient
    case surfaceDefaultAccentMinorGradientActive
    case surfaceDefaultAccentMinorGradientHover
    case surfaceDefaultGradientMain
    case surfaceDefaultGradientMainActive
    case surfaceDefaultGradientMainHover
    case surfaceDefaultPromoGradient
    case surfaceDefaultPromoGradientActive
    case surfaceDefaultPromoGradientHover
    case surfaceDefaultPromoMinorGradient
    case surfaceDefaultPromoMinorGradientActive
    case surfaceDefaultPromoMinorGradientHover
    case surfaceDefaultSkeleton
    case surfaceDefaultSkeletonDeepGradient
    case surfaceDefaultSkeletonDeepGradientActive
    case surfaceDefaultSkeletonDeepGradientHover
    case surfaceDefaultSkeletonGradient
    case surfaceDefaultSkeletonGradientActive
    case surfaceDefaultSkeletonGradientHover
    case surfaceDefaultTransparentAccentGradient
    case surfaceDefaultTransparentAccentGradientActive
    case surfaceDefaultTransparentAccentGradientHover
    case surfaceDefaultTransparentPromoGradient
    case surfaceDefaultTransparentPromoGradientActive
    case surfaceDefaultTransparentPromoGradientHover
    case surfaceInverseAccentGradient
    case surfaceInverseAccentGradientActive
    case surfaceInverseAccentGradientHover
    case surfaceInverseAccentMinorGradient
    case surfaceInverseAccentMinorGradientActive
    case surfaceInverseAccentMinorGradientHover
    case surfaceInverseGradientMain
    case surfaceInverseGradientMainActive
    case surfaceInverseGradientMainHover
    case surfaceInversePromoGradient
    case surfaceInversePromoGradientActive
    case surfaceInversePromoGradientHover
    case surfaceInversePromoMinorGradient
    case surfaceInversePromoMinorGradientActive
    case surfaceInversePromoMinorGradientHover
    case surfaceInverseSkeletonDeepGradient
    case surfaceInverseSkeletonDeepGradientActive
    case surfaceInverseSkeletonDeepGradientHover
    case surfaceInverseSkeletonGradient
    case surfaceInverseSkeletonGradientActive
    case surfaceInverseSkeletonGradientHover
    case surfaceInverseTransparentAccentGradient
    case surfaceInverseTransparentAccentGradientActive
    case surfaceInverseTransparentAccentGradientHover
    case surfaceInverseTransparentPromoGradient
    case surfaceInverseTransparentPromoGradientActive
    case surfaceInverseTransparentPromoGradientHover
    case surfaceOnDarkAccentGradient
    case surfaceOnDarkAccentGradientActive
    case surfaceOnDarkAccentGradientHover
    case surfaceOnDarkAccentMinorGradient
    case surfaceOnDarkAccentMinorGradientActive
    case surfaceOnDarkAccentMinorGradientHover
    case surfaceOnDarkGradientMain
    case surfaceOnDarkGradientMainActive
    case surfaceOnDarkGradientMainHover
    case surfaceOnDarkPromoGradient
    case surfaceOnDarkPromoGradientActive
    case surfaceOnDarkPromoGradientHover
    case surfaceOnDarkPromoMinorGradient
    case surfaceOnDarkPromoMinorGradientActive
    case surfaceOnDarkPromoMinorGradientHover
    case surfaceOnDarkSkeletonDeepGradient
    case surfaceOnDarkSkeletonDeepGradientActive
    case surfaceOnDarkSkeletonDeepGradientHover
    case surfaceOnDarkSkeletonGradient
    case surfaceOnDarkSkeletonGradientActive
    case surfaceOnDarkSkeletonGradientHover
    case surfaceOnDarkTransparentAccentGradient
    case surfaceOnDarkTransparentAccentGradientActive
    case surfaceOnDarkTransparentAccentGradientHover
    case surfaceOnDarkTransparentPromoGradient
    case surfaceOnDarkTransparentPromoGradientActive
    case surfaceOnDarkTransparentPromoGradientHover
    case surfaceOnLightAccentGradient
    case surfaceOnLightAccentGradientActive
    case surfaceOnLightAccentGradientHover
    case surfaceOnLightAccentMinorGradient
    case surfaceOnLightAccentMinorGradientActive
    case surfaceOnLightAccentMinorGradientHover
    case surfaceOnLightGradientMain
    case surfaceOnLightGradientMainActive
    case surfaceOnLightGradientMainHover
    case surfaceOnLightPromoGradient
    case surfaceOnLightPromoGradientActive
    case surfaceOnLightPromoGradientHover
    case surfaceOnLightPromoMinorGradient
    case surfaceOnLightPromoMinorGradientActive
    case surfaceOnLightPromoMinorGradientHover
    case surfaceOnLightSkeletonDeepGradient
    case surfaceOnLightSkeletonDeepGradientActive
    case surfaceOnLightSkeletonDeepGradientHover
    case surfaceOnLightSkeletonGradient
    case surfaceOnLightSkeletonGradientActive
    case surfaceOnLightSkeletonGradientHover
    case surfaceOnLightTransparentAccentGradient
    case surfaceOnLightTransparentAccentGradientActive
    case surfaceOnLightTransparentAccentGradientHover
    case surfaceOnLightTransparentPromoGradient
    case surfaceOnLightTransparentPromoGradientActive
    case surfaceOnLightTransparentPromoGradientHover
    case textDefaultAccentGradient
    case textDefaultAccentGradientActive
    case textDefaultAccentGradientHover
    case textDefaultAccentMinorGradient
    case textDefaultAccentMinorGradientActive
    case textDefaultAccentMinorGradientHover
    case textDefaultGradientAthena
    case textDefaultGradientAthenaActive
    case textDefaultGradientAthenaHover
    case textDefaultGradientB2E
    case textDefaultGradientB2EActive
    case textDefaultGradientB2EHover
    case textDefaultGradientBrand
    case textDefaultGradientBrandActive
    case textDefaultGradientBrandHover
    case textDefaultGradientJoy
    case textDefaultGradientJoyActive
    case textDefaultGradientJoyHover
    case textDefaultGradientMain
    case textDefaultGradientMainActive
    case textDefaultGradientMainHover
    case textDefaultPromoGradient
    case textDefaultPromoGradientActive
    case textDefaultPromoGradientHover
    case textDefaultPromoMinorGradient
    case textDefaultPromoMinorGradientActive
    case textDefaultPromoMinorGradientHover
    case textInverseAccentGradient
    case textInverseAccentGradientActive
    case textInverseAccentGradientHover
    case textInverseAccentMinorGradient
    case textInverseAccentMinorGradientActive
    case textInverseAccentMinorGradientHover
    case textInverseGradientAthena
    case textInverseGradientAthenaActive
    case textInverseGradientAthenaHover
    case textInverseGradientB2E
    case textInverseGradientB2EActive
    case textInverseGradientB2EHover
    case textInverseGradientBrand
    case textInverseGradientBrandActive
    case textInverseGradientBrandHover
    case textInverseGradientJoy
    case textInverseGradientJoyActive
    case textInverseGradientJoyHover
    case textInverseGradientMain
    case textInverseGradientMainActive
    case textInverseGradientMainHover
    case textInversePromoGradient
    case textInversePromoGradientActive
    case textInversePromoGradientHover
    case textInversePromoMinorGradient
    case textInversePromoMinorGradientActive
    case textInversePromoMinorGradientHover
    case textOnDarkAccentGradient
    case textOnDarkAccentGradientActive
    case textOnDarkAccentGradientHover
    case textOnDarkAccentMinorGradient
    case textOnDarkAccentMinorGradientActive
    case textOnDarkAccentMinorGradientHover
    case textOnDarkGradientAthena
    case textOnDarkGradientAthenaActive
    case textOnDarkGradientAthenaHover
    case textOnDarkGradientB2E
    case textOnDarkGradientB2EActive
    case textOnDarkGradientB2EHover
    case textOnDarkGradientBrand
    case textOnDarkGradientBrandActive
    case textOnDarkGradientBrandHover
    case textOnDarkGradientJoy
    case textOnDarkGradientJoyActive
    case textOnDarkGradientJoyHover
    case textOnDarkGradientMain
    case textOnDarkGradientMainActive
    case textOnDarkGradientMainHover
    case textOnDarkPromoGradient
    case textOnDarkPromoGradientActive
    case textOnDarkPromoGradientHover
    case textOnDarkPromoMinorGradient
    case textOnDarkPromoMinorGradientActive
    case textOnDarkPromoMinorGradientHover
    case textOnLightAccentGradient
    case textOnLightAccentGradientActive
    case textOnLightAccentGradientHover
    case textOnLightAccentMinorGradient
    case textOnLightAccentMinorGradientActive
    case textOnLightAccentMinorGradientHover
    case textOnLightGradientAthena
    case textOnLightGradientAthenaActive
    case textOnLightGradientAthenaHover
    case textOnLightGradientB2E
    case textOnLightGradientB2EActive
    case textOnLightGradientB2EHover
    case textOnLightGradientBrand
    case textOnLightGradientBrandActive
    case textOnLightGradientBrandHover
    case textOnLightGradientJoy
    case textOnLightGradientJoyActive
    case textOnLightGradientJoyHover
    case textOnLightGradientMain
    case textOnLightGradientMainActive
    case textOnLightGradientMainHover
    case textOnLightPromoGradient
    case textOnLightPromoGradientActive
    case textOnLightPromoGradientHover
    case textOnLightPromoMinorGradient
    case textOnLightPromoMinorGradientActive
    case textOnLightPromoMinorGradientHover

    public var token: GradientToken {
        switch self {
        case .backgroundDefaultMobileAssistantAthena:
            return .backgroundDefaultMobileAssistantAthena
        case .backgroundDefaultMobileAssistantB2E:
            return .backgroundDefaultMobileAssistantB2E
        case .backgroundDefaultMobileAssistantBrand:
            return .backgroundDefaultMobileAssistantBrand
        case .backgroundDefaultMobileAssistantJoy:
            return .backgroundDefaultMobileAssistantJoy
        case .backgroundDefaultMobileAssistantMain:
            return .backgroundDefaultMobileAssistantMain
        case .backgroundDefaultModalSheet:
            return .backgroundDefaultModalSheet
        case .outlineDefaultAccentGradient:
            return .outlineDefaultAccentGradient
        case .outlineDefaultAccentGradientActive:
            return .outlineDefaultAccentGradientActive
        case .outlineDefaultAccentGradientHover:
            return .outlineDefaultAccentGradientHover
        case .outlineDefaultAccentMinorGradient:
            return .outlineDefaultAccentMinorGradient
        case .outlineDefaultAccentMinorGradientActive:
            return .outlineDefaultAccentMinorGradientActive
        case .outlineDefaultAccentMinorGradientHover:
            return .outlineDefaultAccentMinorGradientHover
        case .outlineDefaultPromoGradient:
            return .outlineDefaultPromoGradient
        case .outlineDefaultPromoGradientActive:
            return .outlineDefaultPromoGradientActive
        case .outlineDefaultPromoGradientHover:
            return .outlineDefaultPromoGradientHover
        case .outlineDefaultPromoMinorGradient:
            return .outlineDefaultPromoMinorGradient
        case .outlineDefaultPromoMinorGradientActive:
            return .outlineDefaultPromoMinorGradientActive
        case .outlineDefaultPromoMinorGradientHover:
            return .outlineDefaultPromoMinorGradientHover
        case .outlineDefaultTransparentAccentGradient:
            return .outlineDefaultTransparentAccentGradient
        case .outlineDefaultTransparentAccentGradientActive:
            return .outlineDefaultTransparentAccentGradientActive
        case .outlineDefaultTransparentAccentGradientHover:
            return .outlineDefaultTransparentAccentGradientHover
        case .outlineInverseAccentGradient:
            return .outlineInverseAccentGradient
        case .outlineInverseAccentGradientActive:
            return .outlineInverseAccentGradientActive
        case .outlineInverseAccentGradientHover:
            return .outlineInverseAccentGradientHover
        case .outlineInverseAccentMinorGradient:
            return .outlineInverseAccentMinorGradient
        case .outlineInverseAccentMinorGradientActive:
            return .outlineInverseAccentMinorGradientActive
        case .outlineInverseAccentMinorGradientHover:
            return .outlineInverseAccentMinorGradientHover
        case .outlineInversePromoGradient:
            return .outlineInversePromoGradient
        case .outlineInversePromoGradientActive:
            return .outlineInversePromoGradientActive
        case .outlineInversePromoGradientHover:
            return .outlineInversePromoGradientHover
        case .outlineInversePromoMinorGradient:
            return .outlineInversePromoMinorGradient
        case .outlineInversePromoMinorGradientActive:
            return .outlineInversePromoMinorGradientActive
        case .outlineInversePromoMinorGradientHover:
            return .outlineInversePromoMinorGradientHover
        case .outlineInverseTransparentAccentGradient:
            return .outlineInverseTransparentAccentGradient
        case .outlineInverseTransparentAccentGradientActive:
            return .outlineInverseTransparentAccentGradientActive
        case .outlineInverseTransparentAccentGradientHover:
            return .outlineInverseTransparentAccentGradientHover
        case .outlineOnDarkAccentGradient:
            return .outlineOnDarkAccentGradient
        case .outlineOnDarkAccentGradientActive:
            return .outlineOnDarkAccentGradientActive
        case .outlineOnDarkAccentGradientHover:
            return .outlineOnDarkAccentGradientHover
        case .outlineOnDarkAccentMinorGradient:
            return .outlineOnDarkAccentMinorGradient
        case .outlineOnDarkAccentMinorGradientActive:
            return .outlineOnDarkAccentMinorGradientActive
        case .outlineOnDarkAccentMinorGradientHover:
            return .outlineOnDarkAccentMinorGradientHover
        case .outlineOnDarkPromoGradient:
            return .outlineOnDarkPromoGradient
        case .outlineOnDarkPromoGradientActive:
            return .outlineOnDarkPromoGradientActive
        case .outlineOnDarkPromoGradientHover:
            return .outlineOnDarkPromoGradientHover
        case .outlineOnDarkPromoMinorGradient:
            return .outlineOnDarkPromoMinorGradient
        case .outlineOnDarkPromoMinorGradientActive:
            return .outlineOnDarkPromoMinorGradientActive
        case .outlineOnDarkPromoMinorGradientHover:
            return .outlineOnDarkPromoMinorGradientHover
        case .outlineOnDarkTransparentAccentGradient:
            return .outlineOnDarkTransparentAccentGradient
        case .outlineOnDarkTransparentAccentGradientActive:
            return .outlineOnDarkTransparentAccentGradientActive
        case .outlineOnDarkTransparentAccentGradientHover:
            return .outlineOnDarkTransparentAccentGradientHover
        case .outlineOnLightAccentGradient:
            return .outlineOnLightAccentGradient
        case .outlineOnLightAccentGradientActive:
            return .outlineOnLightAccentGradientActive
        case .outlineOnLightAccentGradientHover:
            return .outlineOnLightAccentGradientHover
        case .outlineOnLightAccentMinorGradient:
            return .outlineOnLightAccentMinorGradient
        case .outlineOnLightAccentMinorGradientActive:
            return .outlineOnLightAccentMinorGradientActive
        case .outlineOnLightAccentMinorGradientHover:
            return .outlineOnLightAccentMinorGradientHover
        case .outlineOnLightPromoGradient:
            return .outlineOnLightPromoGradient
        case .outlineOnLightPromoGradientActive:
            return .outlineOnLightPromoGradientActive
        case .outlineOnLightPromoGradientHover:
            return .outlineOnLightPromoGradientHover
        case .outlineOnLightPromoMinorGradient:
            return .outlineOnLightPromoMinorGradient
        case .outlineOnLightPromoMinorGradientActive:
            return .outlineOnLightPromoMinorGradientActive
        case .outlineOnLightPromoMinorGradientHover:
            return .outlineOnLightPromoMinorGradientHover
        case .outlineOnLightTransparentAccentGradient:
            return .outlineOnLightTransparentAccentGradient
        case .outlineOnLightTransparentAccentGradientActive:
            return .outlineOnLightTransparentAccentGradientActive
        case .outlineOnLightTransparentAccentGradientHover:
            return .outlineOnLightTransparentAccentGradientHover
        case .surfaceDefaultAccentGradient:
            return .surfaceDefaultAccentGradient
        case .surfaceDefaultAccentGradientActive:
            return .surfaceDefaultAccentGradientActive
        case .surfaceDefaultAccentGradientHover:
            return .surfaceDefaultAccentGradientHover
        case .surfaceDefaultAccentMinorGradient:
            return .surfaceDefaultAccentMinorGradient
        case .surfaceDefaultAccentMinorGradientActive:
            return .surfaceDefaultAccentMinorGradientActive
        case .surfaceDefaultAccentMinorGradientHover:
            return .surfaceDefaultAccentMinorGradientHover
        case .surfaceDefaultGradientMain:
            return .surfaceDefaultGradientMain
        case .surfaceDefaultGradientMainActive:
            return .surfaceDefaultGradientMainActive
        case .surfaceDefaultGradientMainHover:
            return .surfaceDefaultGradientMainHover
        case .surfaceDefaultPromoGradient:
            return .surfaceDefaultPromoGradient
        case .surfaceDefaultPromoGradientActive:
            return .surfaceDefaultPromoGradientActive
        case .surfaceDefaultPromoGradientHover:
            return .surfaceDefaultPromoGradientHover
        case .surfaceDefaultPromoMinorGradient:
            return .surfaceDefaultPromoMinorGradient
        case .surfaceDefaultPromoMinorGradientActive:
            return .surfaceDefaultPromoMinorGradientActive
        case .surfaceDefaultPromoMinorGradientHover:
            return .surfaceDefaultPromoMinorGradientHover
        case .surfaceDefaultSkeleton:
            return .surfaceDefaultSkeleton
        case .surfaceDefaultSkeletonDeepGradient:
            return .surfaceDefaultSkeletonDeepGradient
        case .surfaceDefaultSkeletonDeepGradientActive:
            return .surfaceDefaultSkeletonDeepGradientActive
        case .surfaceDefaultSkeletonDeepGradientHover:
            return .surfaceDefaultSkeletonDeepGradientHover
        case .surfaceDefaultSkeletonGradient:
            return .surfaceDefaultSkeletonGradient
        case .surfaceDefaultSkeletonGradientActive:
            return .surfaceDefaultSkeletonGradientActive
        case .surfaceDefaultSkeletonGradientHover:
            return .surfaceDefaultSkeletonGradientHover
        case .surfaceDefaultTransparentAccentGradient:
            return .surfaceDefaultTransparentAccentGradient
        case .surfaceDefaultTransparentAccentGradientActive:
            return .surfaceDefaultTransparentAccentGradientActive
        case .surfaceDefaultTransparentAccentGradientHover:
            return .surfaceDefaultTransparentAccentGradientHover
        case .surfaceDefaultTransparentPromoGradient:
            return .surfaceDefaultTransparentPromoGradient
        case .surfaceDefaultTransparentPromoGradientActive:
            return .surfaceDefaultTransparentPromoGradientActive
        case .surfaceDefaultTransparentPromoGradientHover:
            return .surfaceDefaultTransparentPromoGradientHover
        case .surfaceInverseAccentGradient:
            return .surfaceInverseAccentGradient
        case .surfaceInverseAccentGradientActive:
            return .surfaceInverseAccentGradientActive
        case .surfaceInverseAccentGradientHover:
            return .surfaceInverseAccentGradientHover
        case .surfaceInverseAccentMinorGradient:
            return .surfaceInverseAccentMinorGradient
        case .surfaceInverseAccentMinorGradientActive:
            return .surfaceInverseAccentMinorGradientActive
        case .surfaceInverseAccentMinorGradientHover:
            return .surfaceInverseAccentMinorGradientHover
        case .surfaceInverseGradientMain:
            return .surfaceInverseGradientMain
        case .surfaceInverseGradientMainActive:
            return .surfaceInverseGradientMainActive
        case .surfaceInverseGradientMainHover:
            return .surfaceInverseGradientMainHover
        case .surfaceInversePromoGradient:
            return .surfaceInversePromoGradient
        case .surfaceInversePromoGradientActive:
            return .surfaceInversePromoGradientActive
        case .surfaceInversePromoGradientHover:
            return .surfaceInversePromoGradientHover
        case .surfaceInversePromoMinorGradient:
            return .surfaceInversePromoMinorGradient
        case .surfaceInversePromoMinorGradientActive:
            return .surfaceInversePromoMinorGradientActive
        case .surfaceInversePromoMinorGradientHover:
            return .surfaceInversePromoMinorGradientHover
        case .surfaceInverseSkeletonDeepGradient:
            return .surfaceInverseSkeletonDeepGradient
        case .surfaceInverseSkeletonDeepGradientActive:
            return .surfaceInverseSkeletonDeepGradientActive
        case .surfaceInverseSkeletonDeepGradientHover:
            return .surfaceInverseSkeletonDeepGradientHover
        case .surfaceInverseSkeletonGradient:
            return .surfaceInverseSkeletonGradient
        case .surfaceInverseSkeletonGradientActive:
            return .surfaceInverseSkeletonGradientActive
        case .surfaceInverseSkeletonGradientHover:
            return .surfaceInverseSkeletonGradientHover
        case .surfaceInverseTransparentAccentGradient:
            return .surfaceInverseTransparentAccentGradient
        case .surfaceInverseTransparentAccentGradientActive:
            return .surfaceInverseTransparentAccentGradientActive
        case .surfaceInverseTransparentAccentGradientHover:
            return .surfaceInverseTransparentAccentGradientHover
        case .surfaceInverseTransparentPromoGradient:
            return .surfaceInverseTransparentPromoGradient
        case .surfaceInverseTransparentPromoGradientActive:
            return .surfaceInverseTransparentPromoGradientActive
        case .surfaceInverseTransparentPromoGradientHover:
            return .surfaceInverseTransparentPromoGradientHover
        case .surfaceOnDarkAccentGradient:
            return .surfaceOnDarkAccentGradient
        case .surfaceOnDarkAccentGradientActive:
            return .surfaceOnDarkAccentGradientActive
        case .surfaceOnDarkAccentGradientHover:
            return .surfaceOnDarkAccentGradientHover
        case .surfaceOnDarkAccentMinorGradient:
            return .surfaceOnDarkAccentMinorGradient
        case .surfaceOnDarkAccentMinorGradientActive:
            return .surfaceOnDarkAccentMinorGradientActive
        case .surfaceOnDarkAccentMinorGradientHover:
            return .surfaceOnDarkAccentMinorGradientHover
        case .surfaceOnDarkGradientMain:
            return .surfaceOnDarkGradientMain
        case .surfaceOnDarkGradientMainActive:
            return .surfaceOnDarkGradientMainActive
        case .surfaceOnDarkGradientMainHover:
            return .surfaceOnDarkGradientMainHover
        case .surfaceOnDarkPromoGradient:
            return .surfaceOnDarkPromoGradient
        case .surfaceOnDarkPromoGradientActive:
            return .surfaceOnDarkPromoGradientActive
        case .surfaceOnDarkPromoGradientHover:
            return .surfaceOnDarkPromoGradientHover
        case .surfaceOnDarkPromoMinorGradient:
            return .surfaceOnDarkPromoMinorGradient
        case .surfaceOnDarkPromoMinorGradientActive:
            return .surfaceOnDarkPromoMinorGradientActive
        case .surfaceOnDarkPromoMinorGradientHover:
            return .surfaceOnDarkPromoMinorGradientHover
        case .surfaceOnDarkSkeletonDeepGradient:
            return .surfaceOnDarkSkeletonDeepGradient
        case .surfaceOnDarkSkeletonDeepGradientActive:
            return .surfaceOnDarkSkeletonDeepGradientActive
        case .surfaceOnDarkSkeletonDeepGradientHover:
            return .surfaceOnDarkSkeletonDeepGradientHover
        case .surfaceOnDarkSkeletonGradient:
            return .surfaceOnDarkSkeletonGradient
        case .surfaceOnDarkSkeletonGradientActive:
            return .surfaceOnDarkSkeletonGradientActive
        case .surfaceOnDarkSkeletonGradientHover:
            return .surfaceOnDarkSkeletonGradientHover
        case .surfaceOnDarkTransparentAccentGradient:
            return .surfaceOnDarkTransparentAccentGradient
        case .surfaceOnDarkTransparentAccentGradientActive:
            return .surfaceOnDarkTransparentAccentGradientActive
        case .surfaceOnDarkTransparentAccentGradientHover:
            return .surfaceOnDarkTransparentAccentGradientHover
        case .surfaceOnDarkTransparentPromoGradient:
            return .surfaceOnDarkTransparentPromoGradient
        case .surfaceOnDarkTransparentPromoGradientActive:
            return .surfaceOnDarkTransparentPromoGradientActive
        case .surfaceOnDarkTransparentPromoGradientHover:
            return .surfaceOnDarkTransparentPromoGradientHover
        case .surfaceOnLightAccentGradient:
            return .surfaceOnLightAccentGradient
        case .surfaceOnLightAccentGradientActive:
            return .surfaceOnLightAccentGradientActive
        case .surfaceOnLightAccentGradientHover:
            return .surfaceOnLightAccentGradientHover
        case .surfaceOnLightAccentMinorGradient:
            return .surfaceOnLightAccentMinorGradient
        case .surfaceOnLightAccentMinorGradientActive:
            return .surfaceOnLightAccentMinorGradientActive
        case .surfaceOnLightAccentMinorGradientHover:
            return .surfaceOnLightAccentMinorGradientHover
        case .surfaceOnLightGradientMain:
            return .surfaceOnLightGradientMain
        case .surfaceOnLightGradientMainActive:
            return .surfaceOnLightGradientMainActive
        case .surfaceOnLightGradientMainHover:
            return .surfaceOnLightGradientMainHover
        case .surfaceOnLightPromoGradient:
            return .surfaceOnLightPromoGradient
        case .surfaceOnLightPromoGradientActive:
            return .surfaceOnLightPromoGradientActive
        case .surfaceOnLightPromoGradientHover:
            return .surfaceOnLightPromoGradientHover
        case .surfaceOnLightPromoMinorGradient:
            return .surfaceOnLightPromoMinorGradient
        case .surfaceOnLightPromoMinorGradientActive:
            return .surfaceOnLightPromoMinorGradientActive
        case .surfaceOnLightPromoMinorGradientHover:
            return .surfaceOnLightPromoMinorGradientHover
        case .surfaceOnLightSkeletonDeepGradient:
            return .surfaceOnLightSkeletonDeepGradient
        case .surfaceOnLightSkeletonDeepGradientActive:
            return .surfaceOnLightSkeletonDeepGradientActive
        case .surfaceOnLightSkeletonDeepGradientHover:
            return .surfaceOnLightSkeletonDeepGradientHover
        case .surfaceOnLightSkeletonGradient:
            return .surfaceOnLightSkeletonGradient
        case .surfaceOnLightSkeletonGradientActive:
            return .surfaceOnLightSkeletonGradientActive
        case .surfaceOnLightSkeletonGradientHover:
            return .surfaceOnLightSkeletonGradientHover
        case .surfaceOnLightTransparentAccentGradient:
            return .surfaceOnLightTransparentAccentGradient
        case .surfaceOnLightTransparentAccentGradientActive:
            return .surfaceOnLightTransparentAccentGradientActive
        case .surfaceOnLightTransparentAccentGradientHover:
            return .surfaceOnLightTransparentAccentGradientHover
        case .surfaceOnLightTransparentPromoGradient:
            return .surfaceOnLightTransparentPromoGradient
        case .surfaceOnLightTransparentPromoGradientActive:
            return .surfaceOnLightTransparentPromoGradientActive
        case .surfaceOnLightTransparentPromoGradientHover:
            return .surfaceOnLightTransparentPromoGradientHover
        case .textDefaultAccentGradient:
            return .textDefaultAccentGradient
        case .textDefaultAccentGradientActive:
            return .textDefaultAccentGradientActive
        case .textDefaultAccentGradientHover:
            return .textDefaultAccentGradientHover
        case .textDefaultAccentMinorGradient:
            return .textDefaultAccentMinorGradient
        case .textDefaultAccentMinorGradientActive:
            return .textDefaultAccentMinorGradientActive
        case .textDefaultAccentMinorGradientHover:
            return .textDefaultAccentMinorGradientHover
        case .textDefaultGradientAthena:
            return .textDefaultGradientAthena
        case .textDefaultGradientAthenaActive:
            return .textDefaultGradientAthenaActive
        case .textDefaultGradientAthenaHover:
            return .textDefaultGradientAthenaHover
        case .textDefaultGradientB2E:
            return .textDefaultGradientB2E
        case .textDefaultGradientB2EActive:
            return .textDefaultGradientB2EActive
        case .textDefaultGradientB2EHover:
            return .textDefaultGradientB2EHover
        case .textDefaultGradientBrand:
            return .textDefaultGradientBrand
        case .textDefaultGradientBrandActive:
            return .textDefaultGradientBrandActive
        case .textDefaultGradientBrandHover:
            return .textDefaultGradientBrandHover
        case .textDefaultGradientJoy:
            return .textDefaultGradientJoy
        case .textDefaultGradientJoyActive:
            return .textDefaultGradientJoyActive
        case .textDefaultGradientJoyHover:
            return .textDefaultGradientJoyHover
        case .textDefaultGradientMain:
            return .textDefaultGradientMain
        case .textDefaultGradientMainActive:
            return .textDefaultGradientMainActive
        case .textDefaultGradientMainHover:
            return .textDefaultGradientMainHover
        case .textDefaultPromoGradient:
            return .textDefaultPromoGradient
        case .textDefaultPromoGradientActive:
            return .textDefaultPromoGradientActive
        case .textDefaultPromoGradientHover:
            return .textDefaultPromoGradientHover
        case .textDefaultPromoMinorGradient:
            return .textDefaultPromoMinorGradient
        case .textDefaultPromoMinorGradientActive:
            return .textDefaultPromoMinorGradientActive
        case .textDefaultPromoMinorGradientHover:
            return .textDefaultPromoMinorGradientHover
        case .textInverseAccentGradient:
            return .textInverseAccentGradient
        case .textInverseAccentGradientActive:
            return .textInverseAccentGradientActive
        case .textInverseAccentGradientHover:
            return .textInverseAccentGradientHover
        case .textInverseAccentMinorGradient:
            return .textInverseAccentMinorGradient
        case .textInverseAccentMinorGradientActive:
            return .textInverseAccentMinorGradientActive
        case .textInverseAccentMinorGradientHover:
            return .textInverseAccentMinorGradientHover
        case .textInverseGradientAthena:
            return .textInverseGradientAthena
        case .textInverseGradientAthenaActive:
            return .textInverseGradientAthenaActive
        case .textInverseGradientAthenaHover:
            return .textInverseGradientAthenaHover
        case .textInverseGradientB2E:
            return .textInverseGradientB2E
        case .textInverseGradientB2EActive:
            return .textInverseGradientB2EActive
        case .textInverseGradientB2EHover:
            return .textInverseGradientB2EHover
        case .textInverseGradientBrand:
            return .textInverseGradientBrand
        case .textInverseGradientBrandActive:
            return .textInverseGradientBrandActive
        case .textInverseGradientBrandHover:
            return .textInverseGradientBrandHover
        case .textInverseGradientJoy:
            return .textInverseGradientJoy
        case .textInverseGradientJoyActive:
            return .textInverseGradientJoyActive
        case .textInverseGradientJoyHover:
            return .textInverseGradientJoyHover
        case .textInverseGradientMain:
            return .textInverseGradientMain
        case .textInverseGradientMainActive:
            return .textInverseGradientMainActive
        case .textInverseGradientMainHover:
            return .textInverseGradientMainHover
        case .textInversePromoGradient:
            return .textInversePromoGradient
        case .textInversePromoGradientActive:
            return .textInversePromoGradientActive
        case .textInversePromoGradientHover:
            return .textInversePromoGradientHover
        case .textInversePromoMinorGradient:
            return .textInversePromoMinorGradient
        case .textInversePromoMinorGradientActive:
            return .textInversePromoMinorGradientActive
        case .textInversePromoMinorGradientHover:
            return .textInversePromoMinorGradientHover
        case .textOnDarkAccentGradient:
            return .textOnDarkAccentGradient
        case .textOnDarkAccentGradientActive:
            return .textOnDarkAccentGradientActive
        case .textOnDarkAccentGradientHover:
            return .textOnDarkAccentGradientHover
        case .textOnDarkAccentMinorGradient:
            return .textOnDarkAccentMinorGradient
        case .textOnDarkAccentMinorGradientActive:
            return .textOnDarkAccentMinorGradientActive
        case .textOnDarkAccentMinorGradientHover:
            return .textOnDarkAccentMinorGradientHover
        case .textOnDarkGradientAthena:
            return .textOnDarkGradientAthena
        case .textOnDarkGradientAthenaActive:
            return .textOnDarkGradientAthenaActive
        case .textOnDarkGradientAthenaHover:
            return .textOnDarkGradientAthenaHover
        case .textOnDarkGradientB2E:
            return .textOnDarkGradientB2E
        case .textOnDarkGradientB2EActive:
            return .textOnDarkGradientB2EActive
        case .textOnDarkGradientB2EHover:
            return .textOnDarkGradientB2EHover
        case .textOnDarkGradientBrand:
            return .textOnDarkGradientBrand
        case .textOnDarkGradientBrandActive:
            return .textOnDarkGradientBrandActive
        case .textOnDarkGradientBrandHover:
            return .textOnDarkGradientBrandHover
        case .textOnDarkGradientJoy:
            return .textOnDarkGradientJoy
        case .textOnDarkGradientJoyActive:
            return .textOnDarkGradientJoyActive
        case .textOnDarkGradientJoyHover:
            return .textOnDarkGradientJoyHover
        case .textOnDarkGradientMain:
            return .textOnDarkGradientMain
        case .textOnDarkGradientMainActive:
            return .textOnDarkGradientMainActive
        case .textOnDarkGradientMainHover:
            return .textOnDarkGradientMainHover
        case .textOnDarkPromoGradient:
            return .textOnDarkPromoGradient
        case .textOnDarkPromoGradientActive:
            return .textOnDarkPromoGradientActive
        case .textOnDarkPromoGradientHover:
            return .textOnDarkPromoGradientHover
        case .textOnDarkPromoMinorGradient:
            return .textOnDarkPromoMinorGradient
        case .textOnDarkPromoMinorGradientActive:
            return .textOnDarkPromoMinorGradientActive
        case .textOnDarkPromoMinorGradientHover:
            return .textOnDarkPromoMinorGradientHover
        case .textOnLightAccentGradient:
            return .textOnLightAccentGradient
        case .textOnLightAccentGradientActive:
            return .textOnLightAccentGradientActive
        case .textOnLightAccentGradientHover:
            return .textOnLightAccentGradientHover
        case .textOnLightAccentMinorGradient:
            return .textOnLightAccentMinorGradient
        case .textOnLightAccentMinorGradientActive:
            return .textOnLightAccentMinorGradientActive
        case .textOnLightAccentMinorGradientHover:
            return .textOnLightAccentMinorGradientHover
        case .textOnLightGradientAthena:
            return .textOnLightGradientAthena
        case .textOnLightGradientAthenaActive:
            return .textOnLightGradientAthenaActive
        case .textOnLightGradientAthenaHover:
            return .textOnLightGradientAthenaHover
        case .textOnLightGradientB2E:
            return .textOnLightGradientB2E
        case .textOnLightGradientB2EActive:
            return .textOnLightGradientB2EActive
        case .textOnLightGradientB2EHover:
            return .textOnLightGradientB2EHover
        case .textOnLightGradientBrand:
            return .textOnLightGradientBrand
        case .textOnLightGradientBrandActive:
            return .textOnLightGradientBrandActive
        case .textOnLightGradientBrandHover:
            return .textOnLightGradientBrandHover
        case .textOnLightGradientJoy:
            return .textOnLightGradientJoy
        case .textOnLightGradientJoyActive:
            return .textOnLightGradientJoyActive
        case .textOnLightGradientJoyHover:
            return .textOnLightGradientJoyHover
        case .textOnLightGradientMain:
            return .textOnLightGradientMain
        case .textOnLightGradientMainActive:
            return .textOnLightGradientMainActive
        case .textOnLightGradientMainHover:
            return .textOnLightGradientMainHover
        case .textOnLightPromoGradient:
            return .textOnLightPromoGradient
        case .textOnLightPromoGradientActive:
            return .textOnLightPromoGradientActive
        case .textOnLightPromoGradientHover:
            return .textOnLightPromoGradientHover
        case .textOnLightPromoMinorGradient:
            return .textOnLightPromoMinorGradient
        case .textOnLightPromoMinorGradientActive:
            return .textOnLightPromoMinorGradientActive
        case .textOnLightPromoMinorGradientHover:
            return .textOnLightPromoMinorGradientHover
        }
    }
}
