name: 'Generate commit-based changelog'
description: 'Generates changelog from commits, extracting PR descriptions'
inputs:
  fromTag:
    description: 'Тэг, название ветки или хэш коммита'
    required: true
  toTag:
    description: 'Тэг, название ветки или хэш коммита'
    required: true
outputs:
  changelog:
    description: "Generated changelog"
    value: ${{ steps.changelog.outputs.changelog }}
runs:
  using: "composite"
  steps:
    - name: Compute envs
      shell: bash
      run: |
        FROM_TAG="${{ inputs.fromTag }}"
        TO_TAG="${{ inputs.toTag }}"

        echo "FROM_TAG=$FROM_TAG" >> $GITHUB_ENV
        echo "TO_TAG=$TO_TAG" >> $GITHUB_ENV
        echo "FROM_TAG = $FROM_TAG and TO_TAG = $TO_TAG"

    - name: Generate changelog from PR descriptions
      id: changelog
      shell: bash
      run: |
        echo "🔍 Generating changelog from PR descriptions between ${{ env.FROM_TAG }} and ${{ env.TO_TAG }}"
        
        # Получаем коммиты между тегами
        COMMITS=$(git log --pretty=format:"%h|%s" ${{ env.FROM_TAG }}..${{ env.TO_TAG }})
        
        if [ -z "$COMMITS" ]; then
          echo "No commits found between ${{ env.FROM_TAG }} and ${{ env.TO_TAG }}"
          echo "changelog=No changes found in this release." >> $GITHUB_OUTPUT
          exit 0
        fi
        
        echo "🔍 Found commits: $(echo "$COMMITS" | wc -l)"
        
        # Формируем changelog
        CHANGELOG=""
        
        # Простой подход - находим все PR с PLASMA в названии и собираем их описания
        echo "🔍 Searching for PRs with PLASMA in title..."
        PLASMA_PRS=$(gh pr list --state merged --search "PLASMA" --json number,title,body --jq '.[] | select(.title | contains("PLASMA")) | {number, title, body}' 2>/dev/null || echo "[]")
        
        if [ "$PLASMA_PRS" != "[]" ] && [ -n "$PLASMA_PRS" ]; then
          echo "🔍 Found PRs with PLASMA:"
          echo "$PLASMA_PRS" | jq -r '.number + ": " + .title' 2>/dev/null || echo "Found PRs but couldn't parse"
          
          # Обрабатываем каждый PR
          echo "$PLASMA_PRS" | jq -r '.number' 2>/dev/null | while read -r PR_NUMBER; do
            if [ -n "$PR_NUMBER" ]; then
              echo "🔍 Processing PR: $PR_NUMBER"
              
              # Получаем описание PR
              PR_BODY=$(echo "$PLASMA_PRS" | jq -r 'select(.number == '$PR_NUMBER') | .body // ""' 2>/dev/null || echo "")
              
              if [ -n "$PR_BODY" ] && [ "$PR_BODY" != "null" ]; then
                echo "🔍 Extracting component descriptions from PR $PR_NUMBER"
                # Извлекаем только описания компонентов (H2 и H3 заголовки)
                COMPONENT_DESCRIPTIONS=$(echo "$PR_BODY" | grep -E "^###|^##" | head -20)
                
                if [ -n "$COMPONENT_DESCRIPTIONS" ]; then
                  echo "🔍 Found component descriptions: $(echo "$COMPONENT_DESCRIPTIONS" | wc -l) lines"
                  CHANGELOG="$CHANGELOG$COMPONENT_DESCRIPTIONS\n\n"
                else
                  # Если нет описаний компонентов, используем название PR
                  PR_TITLE=$(echo "$PLASMA_PRS" | jq -r 'select(.number == '$PR_NUMBER') | .title // ""' 2>/dev/null || echo "")
                  CHANGELOG="$CHANGELOG- $PR_TITLE (#$PR_NUMBER)\n"
                fi
              else
                echo "🔍 No PR body found for PR $PR_NUMBER"
              fi
            fi
          done
        else
          echo "🔍 No PRs with PLASMA found"
        fi
        
        if [ -z "$CHANGELOG" ]; then
          CHANGELOG="No changes found in this release."
        fi
        
        echo "Generated changelog:"
        echo "$CHANGELOG"
        
        # Сохраняем в output
        echo "changelog<<EOF" >> $GITHUB_OUTPUT
        echo "$CHANGELOG" >> $GITHUB_OUTPUT
        echo "EOF" >> $GITHUB_OUTPUT