name: 'Generate commit-based changelog'
description: 'Generate changelog from commits instead of PRs'
inputs:
  fromTag:
    description: 'From tag or commit'
    required: false
  toTag:
    description: 'To tag or commit'
    required: false
outputs:
  changelog:
    description: "Generated changelog"
    value: ${{ steps.changelog.outputs.changelog }}
runs:
  using: "composite"
  steps:
    - name: Compute envs
      shell: bash
      run: |
        if [ -z "${{ inputs.fromTag }}" ]; then
          FROM_TAG=$(git tag --sort=-creatordate | grep '^release-' | sed -n '1p')
        else
          FROM_TAG="${{ inputs.fromTag }}"
        fi

        if [ -z "${{ inputs.toTag }}" ]; then
          TO_TAG="HEAD"
        else
          TO_TAG="${{ inputs.toTag }}"
        fi

        echo "FROM_TAG=$FROM_TAG" >> $GITHUB_ENV
        echo "TO_TAG=$TO_TAG" >> $GITHUB_ENV
        echo "FROM_TAG = $FROM_TAG and TO_TAG = $TO_TAG"

    - name: Generate changelog from PR descriptions
      id: changelog
      shell: bash
      run: |
        echo "🔍 Generating changelog from PR descriptions between ${{ env.FROM_TAG }} and ${{ env.TO_TAG }}"
        
        # Получаем коммиты между тегами
        echo "🔍 Getting commits between ${{ env.FROM_TAG }} and ${{ env.TO_TAG }}"
        COMMITS=$(git log --pretty=format:"%h|%s" ${{ env.FROM_TAG }}..${{ env.TO_TAG }})
        
        if [ -z "$COMMITS" ]; then
          echo "No commits found between ${{ env.FROM_TAG }} and ${{ env.TO_TAG }}"
          echo "changelog=No changes found in this release." >> $GITHUB_OUTPUT
          exit 0
        fi
        
        echo "🔍 Found commits: $(echo "$COMMITS" | wc -l)"
        
        # Формируем changelog
        CHANGELOG=""
        
        # Простой подход - показываем только коммиты с PLASMA-номером
        while IFS='|' read -r hash message; do
          if [ -z "$hash" ]; then
            continue
          fi
          
          echo "🔍 Processing commit: $hash - $message"
          
          # Пропускаем служебные коммиты
          if echo "$message" | grep -qiE "^(chore|bump|version|release|fix:.*changelog|simplify|feat:.*changelog)"; then
            echo "🔍 Skipping service commit: $message"
            continue
          fi
          
          # Ищем PR по PLASMA-номеру
          PLASMA_NUMBER=$(echo "$message" | grep -o "PLASMA-[0-9]+" | head -1)
          if [ -n "$PLASMA_NUMBER" ]; then
            echo "🔍 Found PLASMA number: $PLASMA_NUMBER"
            # Пока просто добавляем коммит
            CHANGELOG="$CHANGELOG- $message ($hash)\n"
          else
            echo "🔍 No PLASMA number found, adding commit"
            CHANGELOG="$CHANGELOG- $message ($hash)\n"
          fi
          
        done <<< "$COMMITS"
        
        if [ -z "$CHANGELOG" ]; then
          CHANGELOG="No changes found in this release."
        fi
        
        echo "Generated changelog:"
        echo "$CHANGELOG"
        
        # Сохраняем в output
        echo "changelog<<EOF" >> $GITHUB_OUTPUT
        echo "$CHANGELOG" >> $GITHUB_OUTPUT
        echo "EOF" >> $GITHUB_OUTPUT