name: 'Generate commit-based changelog'
description: 'Generate changelog from commits instead of PRs'
inputs:
  fromTag:
    description: 'From tag or commit'
    required: false
  toTag:
    description: 'To tag or commit'
    required: false
outputs:
  changelog:
    description: "Generated changelog"
    value: ${{ steps.changelog.outputs.changelog }}
runs:
  using: "composite"
  steps:
    - name: Compute envs
      shell: bash
      run: |
        if [ -z "${{ inputs.fromTag }}" ]; then
          FROM_TAG=$(git tag --sort=-creatordate | grep '^release-' | sed -n '1p')
        else
          FROM_TAG="${{ inputs.fromTag }}"
        fi

        if [ -z "${{ inputs.toTag }}" ]; then
          TO_TAG="HEAD"
        else
          TO_TAG="${{ inputs.toTag }}"
        fi

        echo "FROM_TAG=$FROM_TAG" >> $GITHUB_ENV
        echo "TO_TAG=$TO_TAG" >> $GITHUB_ENV
        echo "FROM_TAG = $FROM_TAG and TO_TAG = $TO_TAG"

    - name: Generate changelog from PR descriptions
      id: changelog
      shell: bash
      run: |
        echo "🔍 Generating changelog from PR descriptions between ${{ env.FROM_TAG }} and ${{ env.TO_TAG }}"
        
        # Получаем коммиты между тегами
        COMMITS=$(git log --pretty=format:"%h|%s" ${{ env.FROM_TAG }}..${{ env.TO_TAG }})
        
        if [ -z "$COMMITS" ]; then
          echo "No commits found between ${{ env.FROM_TAG }} and ${{ env.TO_TAG }}"
          echo "changelog=No changes found in this release." >> $GITHUB_OUTPUT
          exit 0
        fi
        
        # Формируем changelog
        CHANGELOG=""
        
        while IFS='|' read -r hash message; do
          if [ -z "$hash" ]; then
            continue
          fi
          
          # Пропускаем служебные коммиты
          if echo "$message" | grep -qiE "^(chore|bump|version|release|fix:.*changelog|simplify|feat:.*changelog)"; then
            continue
          fi
          
          # Ищем PR по содержимому коммита
          PR_NUMBER=""
          
          # Пробуем найти PR по PLASMA-номеру
          PLASMA_NUMBER=$(echo "$message" | grep -o "PLASMA-[0-9]+" | head -1)
          if [ -n "$PLASMA_NUMBER" ]; then
            echo "🔍 Searching for PR with PLASMA number: $PLASMA_NUMBER"
            PR_NUMBER=$(gh pr list --state merged --search "$PLASMA_NUMBER" --json number,title --jq '.[0].number // empty' 2>/dev/null || echo "")
            echo "🔍 Found PR number: $PR_NUMBER"
          fi
          
          # Если не нашли, пробуем найти по хешу в описании PR'ов
          if [ -z "$PR_NUMBER" ]; then
            echo "🔍 Searching for PR by commit hash: $hash"
            PR_NUMBER=$(gh pr list --state merged --json number,body --jq '.[] | select(.body | contains("'$hash'")) | .number' 2>/dev/null | head -1 || echo "")
            echo "🔍 Found PR number by hash: $PR_NUMBER"
          fi
          
          if [ -n "$PR_NUMBER" ]; then
            echo "🔍 Getting PR $PR_NUMBER description"
            # Получаем описание PR
            PR_BODY=$(gh pr view $PR_NUMBER --json body --jq '.body // ""' 2>/dev/null || echo "")
            
            if [ -n "$PR_BODY" ] && [ "$PR_BODY" != "null" ]; then
              echo "🔍 Extracting component descriptions from PR $PR_NUMBER"
              # Извлекаем только описания компонентов (H2 и H3 заголовки)
              COMPONENT_DESCRIPTIONS=$(echo "$PR_BODY" | grep -E "^###|^##" | head -20)
              
              if [ -n "$COMPONENT_DESCRIPTIONS" ]; then
                echo "🔍 Found component descriptions: $(echo "$COMPONENT_DESCRIPTIONS" | wc -l) lines"
                CHANGELOG="$CHANGELOG$COMPONENT_DESCRIPTIONS\n\n"
              else
                # Если нет описаний компонентов, используем название PR
                PR_TITLE=$(gh pr view $PR_NUMBER --json title --jq '.title // ""' 2>/dev/null || echo "")
                CHANGELOG="$CHANGELOG- $PR_TITLE (#$PR_NUMBER)\n"
              fi
            else
              echo "🔍 No PR body found, using commit message"
              # Если нет описания PR, используем сообщение коммита
              CHANGELOG="$CHANGELOG- $message ($hash)\n"
            fi
          else
            echo "🔍 No PR found, using commit message"
            # Если PR не найден, используем сообщение коммита
            CHANGELOG="$CHANGELOG- $message ($hash)\n"
          fi
          
        done <<< "$COMMITS"
        
        if [ -z "$CHANGELOG" ]; then
          CHANGELOG="No changes found in this release."
        fi
        
        echo "Generated changelog:"
        echo "$CHANGELOG"
        
        # Сохраняем в output
        echo "changelog<<EOF" >> $GITHUB_OUTPUT
        echo "$CHANGELOG" >> $GITHUB_OUTPUT
        echo "EOF" >> $GITHUB_OUTPUT