default_platform(:ios)

platform :ios do
  lane :build_and_upload do
    def check_env_variable(key)
      if ENV[key].nil? || ENV[key].empty?
        UI.user_error!("Missing environment variable: #{key}")
      end
    end

    check_env_variable("APP_STORE_CONNECT_API_KEY_ID")
    check_env_variable("APP_STORE_CONNECT_API_KEY")
    check_env_variable("APP_STORE_CONNECT_ISSUER_ID")

    UI.message("All required environment variables are set!")
    
    # Получаем текущую версию из Info.plist
    # version = get_version_number(
    #   xcodeproj: "SDDSDemoApp/SDDSDemoApp.xcodeproj",
    #   target: "SDDSDemoApp"
    # )

    # UI.user_error!("Version number is missing.") if version.nil?
    
    # # Получение последнего номера сборки из TestFlight
    # latest_build_number = latest_testflight_build_number(
    #   app_identifier: "com.sd.SDDSDemo",
    #   api_key: {
    #     key_id: ENV["APP_STORE_CONNECT_API_KEY_ID"],
    #     issuer_id: ENV["APP_STORE_CONNECT_ISSUER_ID"],
    #     key: ENV["APP_STORE_CONNECT_API_KEY"]
    #   }
    # )
    
    # increment_build_number(
    #   build_number: (latest_build_number.to_i + 1).to_s,
    #   xcodeproj: "SDDSDemoApp/SDDSDemoApp.xcodeproj"
    # )

    # Определяем имя сборки
    branch_name = git_branch
    build_name = case branch_name
                 when "main"
                   "SDDSDemo #{0} #{0}"
                 when "feature/vsdimitraki/testflight-update-build-add-release"
                   "SDDSDemo [Dev]"
                 else
                   "SDDSDemo"
                 end

    UI.message("Build name is #{build_name}")

    build_app(
      scheme: "SDDSDemoApp",
      export_method: "app-store",
      export_options: {
        signingStyle: "manual",
        teamID: "KDMYYG676V",
        provisioningProfiles: {
          "com.sd.SDDSDemo" => "SDDS Demo Distribution"
        }
      },
      output_name: build_name
    )

    # upload_to_testflight(
    #   api_key: {
    #     key_id: ENV["APP_STORE_CONNECT_API_KEY_ID"],
    #     issuer_id: ENV["APP_STORE_CONNECT_ISSUER_ID"],
    #     key: ENV["APP_STORE_CONNECT_API_KEY"]
    #   }
    # )
  end
end