/* This file is code generated. */

import SwiftUI
import UIKit
@_exported import SDDSThemeCore


public extension Colors {
    static func registerGold() {
        ThemeTenantRegistry.shared.registerColors(theme: "SDDSServ", tenant: Tenant(name: "Gold")) { id in
            switch id {
            case "backgroundDarkPrimary": return .backgroundDarkPrimaryGold
            case "backgroundDarkSecondary": return .backgroundDarkSecondaryGold
            case "backgroundDarkTertiary": return .backgroundDarkTertiaryGold
            case "backgroundDefaultOverlay": return .backgroundDefaultOverlayGold
            case "backgroundDefaultPrimary": return .backgroundDefaultPrimaryGold
            case "backgroundDefaultPrimaryBrightness": return .backgroundDefaultPrimaryBrightnessGold
            case "backgroundDefaultSecondary": return .backgroundDefaultSecondaryGold
            case "backgroundDefaultTertiary": return .backgroundDefaultTertiaryGold
            case "backgroundInversePrimary": return .backgroundInversePrimaryGold
            case "backgroundInversePrimaryBrightness": return .backgroundInversePrimaryBrightnessGold
            case "backgroundInverseSecondary": return .backgroundInverseSecondaryGold
            case "backgroundInverseTertiary": return .backgroundInverseTertiaryGold
            case "backgroundLightPrimary": return .backgroundLightPrimaryGold
            case "backgroundLightSecondary": return .backgroundLightSecondaryGold
            case "backgroundLightTertiary": return .backgroundLightTertiaryGold
            case "bannerDefaultBlue": return .bannerDefaultBlueGold
            case "bannerDefaultGold": return .bannerDefaultGoldGold
            case "bannerDefaultGreen": return .bannerDefaultGreenGold
            case "bannerDefaultMalachite": return .bannerDefaultMalachiteGold
            case "bannerDefaultRed": return .bannerDefaultRedGold
            case "bannersDefaultBannerBlue": return .bannersDefaultBannerBlueGold
            case "bannersDefaultBannerGold": return .bannersDefaultBannerGoldGold
            case "bannersDefaultBannerGreen": return .bannersDefaultBannerGreenGold
            case "bannersDefaultBannerMalachite": return .bannersDefaultBannerMalachiteGold
            case "bannersDefaultBannerRed": return .bannersDefaultBannerRedGold
            case "dataDefaultYellow": return .dataDefaultYellowGold
            case "dataDefaultYellowActive": return .dataDefaultYellowActiveGold
            case "dataDefaultYellowHover": return .dataDefaultYellowHoverGold
            case "dataDefaultYellowMinor": return .dataDefaultYellowMinorGold
            case "dataDefaultYellowMinorActive": return .dataDefaultYellowMinorActiveGold
            case "dataDefaultYellowMinorHover": return .dataDefaultYellowMinorHoverGold
            case "dataDefaultYellowTransparent": return .dataDefaultYellowTransparentGold
            case "dataDefaultYellowTransparentActive": return .dataDefaultYellowTransparentActiveGold
            case "dataDefaultYellowTransparentHover": return .dataDefaultYellowTransparentHoverGold
            case "dataInverseYellow": return .dataInverseYellowGold
            case "dataInverseYellowActive": return .dataInverseYellowActiveGold
            case "dataInverseYellowHover": return .dataInverseYellowHoverGold
            case "dataInverseYellowMinor": return .dataInverseYellowMinorGold
            case "dataInverseYellowMinorActive": return .dataInverseYellowMinorActiveGold
            case "dataInverseYellowMinorHover": return .dataInverseYellowMinorHoverGold
            case "dataInverseYellowTransparent": return .dataInverseYellowTransparentGold
            case "dataInverseYellowTransparentActive": return .dataInverseYellowTransparentActiveGold
            case "dataInverseYellowTransparentHover": return .dataInverseYellowTransparentHoverGold
            case "dataOnDarkYellow": return .dataOnDarkYellowGold
            case "dataOnDarkYellowActive": return .dataOnDarkYellowActiveGold
            case "dataOnDarkYellowHover": return .dataOnDarkYellowHoverGold
            case "dataOnDarkYellowMinor": return .dataOnDarkYellowMinorGold
            case "dataOnDarkYellowMinorActive": return .dataOnDarkYellowMinorActiveGold
            case "dataOnDarkYellowMinorHover": return .dataOnDarkYellowMinorHoverGold
            case "dataOnDarkYellowTransparent": return .dataOnDarkYellowTransparentGold
            case "dataOnDarkYellowTransparentActive": return .dataOnDarkYellowTransparentActiveGold
            case "dataOnDarkYellowTransparentHover": return .dataOnDarkYellowTransparentHoverGold
            case "dataOnLightYellow": return .dataOnLightYellowGold
            case "dataOnLightYellowActive": return .dataOnLightYellowActiveGold
            case "dataOnLightYellowHover": return .dataOnLightYellowHoverGold
            case "dataOnLightYellowMinor": return .dataOnLightYellowMinorGold
            case "dataOnLightYellowMinorActive": return .dataOnLightYellowMinorActiveGold
            case "dataOnLightYellowMinorHover": return .dataOnLightYellowMinorHoverGold
            case "dataOnLightYellowTransparent": return .dataOnLightYellowTransparentGold
            case "dataOnLightYellowTransparentActive": return .dataOnLightYellowTransparentActiveGold
            case "dataOnLightYellowTransparentHover": return .dataOnLightYellowTransparentHoverGold
            case "outlineDefaultAccent": return .outlineDefaultAccentGold
            case "outlineDefaultAccentActive": return .outlineDefaultAccentActiveGold
            case "outlineDefaultAccentHover": return .outlineDefaultAccentHoverGold
            case "outlineDefaultAccentMinor": return .outlineDefaultAccentMinorGold
            case "outlineDefaultAccentMinorActive": return .outlineDefaultAccentMinorActiveGold
            case "outlineDefaultAccentMinorHover": return .outlineDefaultAccentMinorHoverGold
            case "outlineDefaultClear": return .outlineDefaultClearGold
            case "outlineDefaultClearActive": return .outlineDefaultClearActiveGold
            case "outlineDefaultClearHover": return .outlineDefaultClearHoverGold
            case "outlineDefaultInfo": return .outlineDefaultInfoGold
            case "outlineDefaultInfoActive": return .outlineDefaultInfoActiveGold
            case "outlineDefaultInfoHover": return .outlineDefaultInfoHoverGold
            case "outlineDefaultInfoMinor": return .outlineDefaultInfoMinorGold
            case "outlineDefaultInfoMinorActive": return .outlineDefaultInfoMinorActiveGold
            case "outlineDefaultInfoMinorHover": return .outlineDefaultInfoMinorHoverGold
            case "outlineDefaultNegative": return .outlineDefaultNegativeGold
            case "outlineDefaultNegativeActive": return .outlineDefaultNegativeActiveGold
            case "outlineDefaultNegativeHover": return .outlineDefaultNegativeHoverGold
            case "outlineDefaultNegativeMinor": return .outlineDefaultNegativeMinorGold
            case "outlineDefaultNegativeMinorActive": return .outlineDefaultNegativeMinorActiveGold
            case "outlineDefaultNegativeMinorHover": return .outlineDefaultNegativeMinorHoverGold
            case "outlineDefaultPositive": return .outlineDefaultPositiveGold
            case "outlineDefaultPositiveActive": return .outlineDefaultPositiveActiveGold
            case "outlineDefaultPositiveHover": return .outlineDefaultPositiveHoverGold
            case "outlineDefaultPositiveMinor": return .outlineDefaultPositiveMinorGold
            case "outlineDefaultPositiveMinorActive": return .outlineDefaultPositiveMinorActiveGold
            case "outlineDefaultPositiveMinorHover": return .outlineDefaultPositiveMinorHoverGold
            case "outlineDefaultPromo": return .outlineDefaultPromoGold
            case "outlineDefaultPromoActive": return .outlineDefaultPromoActiveGold
            case "outlineDefaultPromoHover": return .outlineDefaultPromoHoverGold
            case "outlineDefaultPromoMinor": return .outlineDefaultPromoMinorGold
            case "outlineDefaultPromoMinorActive": return .outlineDefaultPromoMinorActiveGold
            case "outlineDefaultPromoMinorHover": return .outlineDefaultPromoMinorHoverGold
            case "outlineDefaultSolidPrimary": return .outlineDefaultSolidPrimaryGold
            case "outlineDefaultSolidPrimaryActive": return .outlineDefaultSolidPrimaryActiveGold
            case "outlineDefaultSolidPrimaryHover": return .outlineDefaultSolidPrimaryHoverGold
            case "outlineDefaultSolidSecondary": return .outlineDefaultSolidSecondaryGold
            case "outlineDefaultSolidSecondaryActive": return .outlineDefaultSolidSecondaryActiveGold
            case "outlineDefaultSolidSecondaryHover": return .outlineDefaultSolidSecondaryHoverGold
            case "outlineDefaultSolidTertiary": return .outlineDefaultSolidTertiaryGold
            case "outlineDefaultSolidTertiaryActive": return .outlineDefaultSolidTertiaryActiveGold
            case "outlineDefaultSolidTertiaryHover": return .outlineDefaultSolidTertiaryHoverGold
            case "outlineDefaultTransparentAccent": return .outlineDefaultTransparentAccentGold
            case "outlineDefaultTransparentAccentActive": return .outlineDefaultTransparentAccentActiveGold
            case "outlineDefaultTransparentAccentHover": return .outlineDefaultTransparentAccentHoverGold
            case "outlineDefaultTransparentDefault": return .outlineDefaultTransparentDefaultGold
            case "outlineDefaultTransparentDefaultActive": return .outlineDefaultTransparentDefaultActiveGold
            case "outlineDefaultTransparentDefaultHover": return .outlineDefaultTransparentDefaultHoverGold
            case "outlineDefaultTransparentInfo": return .outlineDefaultTransparentInfoGold
            case "outlineDefaultTransparentInfoActive": return .outlineDefaultTransparentInfoActiveGold
            case "outlineDefaultTransparentInfoHover": return .outlineDefaultTransparentInfoHoverGold
            case "outlineDefaultTransparentNegative": return .outlineDefaultTransparentNegativeGold
            case "outlineDefaultTransparentNegativeActive": return .outlineDefaultTransparentNegativeActiveGold
            case "outlineDefaultTransparentNegativeHover": return .outlineDefaultTransparentNegativeHoverGold
            case "outlineDefaultTransparentPositive": return .outlineDefaultTransparentPositiveGold
            case "outlineDefaultTransparentPositiveActive": return .outlineDefaultTransparentPositiveActiveGold
            case "outlineDefaultTransparentPositiveHover": return .outlineDefaultTransparentPositiveHoverGold
            case "outlineDefaultTransparentPrimary": return .outlineDefaultTransparentPrimaryGold
            case "outlineDefaultTransparentPrimaryActive": return .outlineDefaultTransparentPrimaryActiveGold
            case "outlineDefaultTransparentPrimaryHover": return .outlineDefaultTransparentPrimaryHoverGold
            case "outlineDefaultTransparentSecondary": return .outlineDefaultTransparentSecondaryGold
            case "outlineDefaultTransparentSecondaryActive": return .outlineDefaultTransparentSecondaryActiveGold
            case "outlineDefaultTransparentSecondaryHover": return .outlineDefaultTransparentSecondaryHoverGold
            case "outlineDefaultTransparentTertiary": return .outlineDefaultTransparentTertiaryGold
            case "outlineDefaultTransparentTertiaryActive": return .outlineDefaultTransparentTertiaryActiveGold
            case "outlineDefaultTransparentTertiaryHover": return .outlineDefaultTransparentTertiaryHoverGold
            case "outlineDefaultTransparentWarning": return .outlineDefaultTransparentWarningGold
            case "outlineDefaultTransparentWarningActive": return .outlineDefaultTransparentWarningActiveGold
            case "outlineDefaultTransparentWarningHover": return .outlineDefaultTransparentWarningHoverGold
            case "outlineDefaultWarning": return .outlineDefaultWarningGold
            case "outlineDefaultWarningActive": return .outlineDefaultWarningActiveGold
            case "outlineDefaultWarningHover": return .outlineDefaultWarningHoverGold
            case "outlineDefaultWarningMinor": return .outlineDefaultWarningMinorGold
            case "outlineDefaultWarningMinorActive": return .outlineDefaultWarningMinorActiveGold
            case "outlineDefaultWarningMinorHover": return .outlineDefaultWarningMinorHoverGold
            case "outlineInverseAccent": return .outlineInverseAccentGold
            case "outlineInverseAccentActive": return .outlineInverseAccentActiveGold
            case "outlineInverseAccentHover": return .outlineInverseAccentHoverGold
            case "outlineInverseAccentMinor": return .outlineInverseAccentMinorGold
            case "outlineInverseAccentMinorActive": return .outlineInverseAccentMinorActiveGold
            case "outlineInverseAccentMinorHover": return .outlineInverseAccentMinorHoverGold
            case "outlineInverseClear": return .outlineInverseClearGold
            case "outlineInverseClearActive": return .outlineInverseClearActiveGold
            case "outlineInverseClearHover": return .outlineInverseClearHoverGold
            case "outlineInverseInfo": return .outlineInverseInfoGold
            case "outlineInverseInfoActive": return .outlineInverseInfoActiveGold
            case "outlineInverseInfoHover": return .outlineInverseInfoHoverGold
            case "outlineInverseInfoMinor": return .outlineInverseInfoMinorGold
            case "outlineInverseInfoMinorActive": return .outlineInverseInfoMinorActiveGold
            case "outlineInverseInfoMinorHover": return .outlineInverseInfoMinorHoverGold
            case "outlineInverseNegative": return .outlineInverseNegativeGold
            case "outlineInverseNegativeActive": return .outlineInverseNegativeActiveGold
            case "outlineInverseNegativeHover": return .outlineInverseNegativeHoverGold
            case "outlineInverseNegativeMinor": return .outlineInverseNegativeMinorGold
            case "outlineInverseNegativeMinorActive": return .outlineInverseNegativeMinorActiveGold
            case "outlineInverseNegativeMinorHover": return .outlineInverseNegativeMinorHoverGold
            case "outlineInversePositive": return .outlineInversePositiveGold
            case "outlineInversePositiveActive": return .outlineInversePositiveActiveGold
            case "outlineInversePositiveHover": return .outlineInversePositiveHoverGold
            case "outlineInversePositiveMinor": return .outlineInversePositiveMinorGold
            case "outlineInversePositiveMinorActive": return .outlineInversePositiveMinorActiveGold
            case "outlineInversePositiveMinorHover": return .outlineInversePositiveMinorHoverGold
            case "outlineInversePromo": return .outlineInversePromoGold
            case "outlineInversePromoActive": return .outlineInversePromoActiveGold
            case "outlineInversePromoHover": return .outlineInversePromoHoverGold
            case "outlineInversePromoMinor": return .outlineInversePromoMinorGold
            case "outlineInversePromoMinorActive": return .outlineInversePromoMinorActiveGold
            case "outlineInversePromoMinorHover": return .outlineInversePromoMinorHoverGold
            case "outlineInverseSolidPrimary": return .outlineInverseSolidPrimaryGold
            case "outlineInverseSolidPrimaryActive": return .outlineInverseSolidPrimaryActiveGold
            case "outlineInverseSolidPrimaryHover": return .outlineInverseSolidPrimaryHoverGold
            case "outlineInverseSolidSecondary": return .outlineInverseSolidSecondaryGold
            case "outlineInverseSolidSecondaryActive": return .outlineInverseSolidSecondaryActiveGold
            case "outlineInverseSolidSecondaryHover": return .outlineInverseSolidSecondaryHoverGold
            case "outlineInverseSolidTertiary": return .outlineInverseSolidTertiaryGold
            case "outlineInverseSolidTertiaryActive": return .outlineInverseSolidTertiaryActiveGold
            case "outlineInverseSolidTertiaryHover": return .outlineInverseSolidTertiaryHoverGold
            case "outlineInverseTransparentAccent": return .outlineInverseTransparentAccentGold
            case "outlineInverseTransparentAccentActive": return .outlineInverseTransparentAccentActiveGold
            case "outlineInverseTransparentAccentHover": return .outlineInverseTransparentAccentHoverGold
            case "outlineInverseTransparentDefault": return .outlineInverseTransparentDefaultGold
            case "outlineInverseTransparentDefaultActive": return .outlineInverseTransparentDefaultActiveGold
            case "outlineInverseTransparentDefaultHover": return .outlineInverseTransparentDefaultHoverGold
            case "outlineInverseTransparentInfo": return .outlineInverseTransparentInfoGold
            case "outlineInverseTransparentInfoActive": return .outlineInverseTransparentInfoActiveGold
            case "outlineInverseTransparentInfoHover": return .outlineInverseTransparentInfoHoverGold
            case "outlineInverseTransparentNegative": return .outlineInverseTransparentNegativeGold
            case "outlineInverseTransparentNegativeActive": return .outlineInverseTransparentNegativeActiveGold
            case "outlineInverseTransparentNegativeHover": return .outlineInverseTransparentNegativeHoverGold
            case "outlineInverseTransparentPositive": return .outlineInverseTransparentPositiveGold
            case "outlineInverseTransparentPositiveActive": return .outlineInverseTransparentPositiveActiveGold
            case "outlineInverseTransparentPositiveHover": return .outlineInverseTransparentPositiveHoverGold
            case "outlineInverseTransparentPrimary": return .outlineInverseTransparentPrimaryGold
            case "outlineInverseTransparentPrimaryActive": return .outlineInverseTransparentPrimaryActiveGold
            case "outlineInverseTransparentPrimaryHover": return .outlineInverseTransparentPrimaryHoverGold
            case "outlineInverseTransparentSecondary": return .outlineInverseTransparentSecondaryGold
            case "outlineInverseTransparentSecondaryActive": return .outlineInverseTransparentSecondaryActiveGold
            case "outlineInverseTransparentSecondaryHover": return .outlineInverseTransparentSecondaryHoverGold
            case "outlineInverseTransparentTertiary": return .outlineInverseTransparentTertiaryGold
            case "outlineInverseTransparentTertiaryActive": return .outlineInverseTransparentTertiaryActiveGold
            case "outlineInverseTransparentTertiaryHover": return .outlineInverseTransparentTertiaryHoverGold
            case "outlineInverseTransparentWarning": return .outlineInverseTransparentWarningGold
            case "outlineInverseTransparentWarningActive": return .outlineInverseTransparentWarningActiveGold
            case "outlineInverseTransparentWarningHover": return .outlineInverseTransparentWarningHoverGold
            case "outlineInverseWarning": return .outlineInverseWarningGold
            case "outlineInverseWarningActive": return .outlineInverseWarningActiveGold
            case "outlineInverseWarningHover": return .outlineInverseWarningHoverGold
            case "outlineInverseWarningMinor": return .outlineInverseWarningMinorGold
            case "outlineInverseWarningMinorActive": return .outlineInverseWarningMinorActiveGold
            case "outlineInverseWarningMinorHover": return .outlineInverseWarningMinorHoverGold
            case "outlineOnDarkAccent": return .outlineOnDarkAccentGold
            case "outlineOnDarkAccentActive": return .outlineOnDarkAccentActiveGold
            case "outlineOnDarkAccentHover": return .outlineOnDarkAccentHoverGold
            case "outlineOnDarkAccentMinor": return .outlineOnDarkAccentMinorGold
            case "outlineOnDarkAccentMinorActive": return .outlineOnDarkAccentMinorActiveGold
            case "outlineOnDarkAccentMinorHover": return .outlineOnDarkAccentMinorHoverGold
            case "outlineOnDarkClear": return .outlineOnDarkClearGold
            case "outlineOnDarkClearActive": return .outlineOnDarkClearActiveGold
            case "outlineOnDarkClearHover": return .outlineOnDarkClearHoverGold
            case "outlineOnDarkInfo": return .outlineOnDarkInfoGold
            case "outlineOnDarkInfoActive": return .outlineOnDarkInfoActiveGold
            case "outlineOnDarkInfoHover": return .outlineOnDarkInfoHoverGold
            case "outlineOnDarkInfoMinor": return .outlineOnDarkInfoMinorGold
            case "outlineOnDarkInfoMinorActive": return .outlineOnDarkInfoMinorActiveGold
            case "outlineOnDarkInfoMinorHover": return .outlineOnDarkInfoMinorHoverGold
            case "outlineOnDarkNegative": return .outlineOnDarkNegativeGold
            case "outlineOnDarkNegativeActive": return .outlineOnDarkNegativeActiveGold
            case "outlineOnDarkNegativeHover": return .outlineOnDarkNegativeHoverGold
            case "outlineOnDarkNegativeMinor": return .outlineOnDarkNegativeMinorGold
            case "outlineOnDarkNegativeMinorActive": return .outlineOnDarkNegativeMinorActiveGold
            case "outlineOnDarkNegativeMinorHover": return .outlineOnDarkNegativeMinorHoverGold
            case "outlineOnDarkPositive": return .outlineOnDarkPositiveGold
            case "outlineOnDarkPositiveActive": return .outlineOnDarkPositiveActiveGold
            case "outlineOnDarkPositiveHover": return .outlineOnDarkPositiveHoverGold
            case "outlineOnDarkPositiveMinor": return .outlineOnDarkPositiveMinorGold
            case "outlineOnDarkPositiveMinorActive": return .outlineOnDarkPositiveMinorActiveGold
            case "outlineOnDarkPositiveMinorHover": return .outlineOnDarkPositiveMinorHoverGold
            case "outlineOnDarkPromo": return .outlineOnDarkPromoGold
            case "outlineOnDarkPromoActive": return .outlineOnDarkPromoActiveGold
            case "outlineOnDarkPromoHover": return .outlineOnDarkPromoHoverGold
            case "outlineOnDarkPromoMinor": return .outlineOnDarkPromoMinorGold
            case "outlineOnDarkPromoMinorActive": return .outlineOnDarkPromoMinorActiveGold
            case "outlineOnDarkPromoMinorHover": return .outlineOnDarkPromoMinorHoverGold
            case "outlineOnDarkSolidPrimary": return .outlineOnDarkSolidPrimaryGold
            case "outlineOnDarkSolidPrimaryActive": return .outlineOnDarkSolidPrimaryActiveGold
            case "outlineOnDarkSolidPrimaryHover": return .outlineOnDarkSolidPrimaryHoverGold
            case "outlineOnDarkSolidSecondary": return .outlineOnDarkSolidSecondaryGold
            case "outlineOnDarkSolidSecondaryActive": return .outlineOnDarkSolidSecondaryActiveGold
            case "outlineOnDarkSolidSecondaryHover": return .outlineOnDarkSolidSecondaryHoverGold
            case "outlineOnDarkSolidTertiary": return .outlineOnDarkSolidTertiaryGold
            case "outlineOnDarkSolidTertiaryActive": return .outlineOnDarkSolidTertiaryActiveGold
            case "outlineOnDarkSolidTertiaryHover": return .outlineOnDarkSolidTertiaryHoverGold
            case "outlineOnDarkTransparentAccent": return .outlineOnDarkTransparentAccentGold
            case "outlineOnDarkTransparentAccentActive": return .outlineOnDarkTransparentAccentActiveGold
            case "outlineOnDarkTransparentAccentHover": return .outlineOnDarkTransparentAccentHoverGold
            case "outlineOnDarkTransparentDefault": return .outlineOnDarkTransparentDefaultGold
            case "outlineOnDarkTransparentDefaultActive": return .outlineOnDarkTransparentDefaultActiveGold
            case "outlineOnDarkTransparentDefaultHover": return .outlineOnDarkTransparentDefaultHoverGold
            case "outlineOnDarkTransparentInfo": return .outlineOnDarkTransparentInfoGold
            case "outlineOnDarkTransparentInfoActive": return .outlineOnDarkTransparentInfoActiveGold
            case "outlineOnDarkTransparentInfoHover": return .outlineOnDarkTransparentInfoHoverGold
            case "outlineOnDarkTransparentNegative": return .outlineOnDarkTransparentNegativeGold
            case "outlineOnDarkTransparentNegativeActive": return .outlineOnDarkTransparentNegativeActiveGold
            case "outlineOnDarkTransparentNegativeHover": return .outlineOnDarkTransparentNegativeHoverGold
            case "outlineOnDarkTransparentPositive": return .outlineOnDarkTransparentPositiveGold
            case "outlineOnDarkTransparentPositiveActive": return .outlineOnDarkTransparentPositiveActiveGold
            case "outlineOnDarkTransparentPositiveHover": return .outlineOnDarkTransparentPositiveHoverGold
            case "outlineOnDarkTransparentPrimary": return .outlineOnDarkTransparentPrimaryGold
            case "outlineOnDarkTransparentPrimaryActive": return .outlineOnDarkTransparentPrimaryActiveGold
            case "outlineOnDarkTransparentPrimaryHover": return .outlineOnDarkTransparentPrimaryHoverGold
            case "outlineOnDarkTransparentSecondary": return .outlineOnDarkTransparentSecondaryGold
            case "outlineOnDarkTransparentSecondaryActive": return .outlineOnDarkTransparentSecondaryActiveGold
            case "outlineOnDarkTransparentSecondaryHover": return .outlineOnDarkTransparentSecondaryHoverGold
            case "outlineOnDarkTransparentTertiary": return .outlineOnDarkTransparentTertiaryGold
            case "outlineOnDarkTransparentTertiaryActive": return .outlineOnDarkTransparentTertiaryActiveGold
            case "outlineOnDarkTransparentTertiaryHover": return .outlineOnDarkTransparentTertiaryHoverGold
            case "outlineOnDarkTransparentWarning": return .outlineOnDarkTransparentWarningGold
            case "outlineOnDarkTransparentWarningActive": return .outlineOnDarkTransparentWarningActiveGold
            case "outlineOnDarkTransparentWarningHover": return .outlineOnDarkTransparentWarningHoverGold
            case "outlineOnDarkWarning": return .outlineOnDarkWarningGold
            case "outlineOnDarkWarningActive": return .outlineOnDarkWarningActiveGold
            case "outlineOnDarkWarningHover": return .outlineOnDarkWarningHoverGold
            case "outlineOnDarkWarningMinor": return .outlineOnDarkWarningMinorGold
            case "outlineOnDarkWarningMinorActive": return .outlineOnDarkWarningMinorActiveGold
            case "outlineOnDarkWarningMinorHover": return .outlineOnDarkWarningMinorHoverGold
            case "outlineOnLightAccent": return .outlineOnLightAccentGold
            case "outlineOnLightAccentActive": return .outlineOnLightAccentActiveGold
            case "outlineOnLightAccentHover": return .outlineOnLightAccentHoverGold
            case "outlineOnLightAccentMinor": return .outlineOnLightAccentMinorGold
            case "outlineOnLightAccentMinorActive": return .outlineOnLightAccentMinorActiveGold
            case "outlineOnLightAccentMinorHover": return .outlineOnLightAccentMinorHoverGold
            case "outlineOnLightClear": return .outlineOnLightClearGold
            case "outlineOnLightClearActive": return .outlineOnLightClearActiveGold
            case "outlineOnLightClearHover": return .outlineOnLightClearHoverGold
            case "outlineOnLightInfo": return .outlineOnLightInfoGold
            case "outlineOnLightInfoActive": return .outlineOnLightInfoActiveGold
            case "outlineOnLightInfoHover": return .outlineOnLightInfoHoverGold
            case "outlineOnLightInfoMinor": return .outlineOnLightInfoMinorGold
            case "outlineOnLightInfoMinorActive": return .outlineOnLightInfoMinorActiveGold
            case "outlineOnLightInfoMinorHover": return .outlineOnLightInfoMinorHoverGold
            case "outlineOnLightNegative": return .outlineOnLightNegativeGold
            case "outlineOnLightNegativeActive": return .outlineOnLightNegativeActiveGold
            case "outlineOnLightNegativeHover": return .outlineOnLightNegativeHoverGold
            case "outlineOnLightNegativeMinor": return .outlineOnLightNegativeMinorGold
            case "outlineOnLightNegativeMinorActive": return .outlineOnLightNegativeMinorActiveGold
            case "outlineOnLightNegativeMinorHover": return .outlineOnLightNegativeMinorHoverGold
            case "outlineOnLightPositive": return .outlineOnLightPositiveGold
            case "outlineOnLightPositiveActive": return .outlineOnLightPositiveActiveGold
            case "outlineOnLightPositiveHover": return .outlineOnLightPositiveHoverGold
            case "outlineOnLightPositiveMinor": return .outlineOnLightPositiveMinorGold
            case "outlineOnLightPositiveMinorActive": return .outlineOnLightPositiveMinorActiveGold
            case "outlineOnLightPositiveMinorHover": return .outlineOnLightPositiveMinorHoverGold
            case "outlineOnLightPromo": return .outlineOnLightPromoGold
            case "outlineOnLightPromoActive": return .outlineOnLightPromoActiveGold
            case "outlineOnLightPromoHover": return .outlineOnLightPromoHoverGold
            case "outlineOnLightPromoMinor": return .outlineOnLightPromoMinorGold
            case "outlineOnLightPromoMinorActive": return .outlineOnLightPromoMinorActiveGold
            case "outlineOnLightPromoMinorHover": return .outlineOnLightPromoMinorHoverGold
            case "outlineOnLightSolidPrimary": return .outlineOnLightSolidPrimaryGold
            case "outlineOnLightSolidPrimaryActive": return .outlineOnLightSolidPrimaryActiveGold
            case "outlineOnLightSolidPrimaryHover": return .outlineOnLightSolidPrimaryHoverGold
            case "outlineOnLightSolidSecondary": return .outlineOnLightSolidSecondaryGold
            case "outlineOnLightSolidSecondaryActive": return .outlineOnLightSolidSecondaryActiveGold
            case "outlineOnLightSolidSecondaryHover": return .outlineOnLightSolidSecondaryHoverGold
            case "outlineOnLightSolidTertiary": return .outlineOnLightSolidTertiaryGold
            case "outlineOnLightSolidTertiaryActive": return .outlineOnLightSolidTertiaryActiveGold
            case "outlineOnLightSolidTertiaryHover": return .outlineOnLightSolidTertiaryHoverGold
            case "outlineOnLightTransparentAccent": return .outlineOnLightTransparentAccentGold
            case "outlineOnLightTransparentAccentActive": return .outlineOnLightTransparentAccentActiveGold
            case "outlineOnLightTransparentAccentHover": return .outlineOnLightTransparentAccentHoverGold
            case "outlineOnLightTransparentDefault": return .outlineOnLightTransparentDefaultGold
            case "outlineOnLightTransparentDefaultActive": return .outlineOnLightTransparentDefaultActiveGold
            case "outlineOnLightTransparentDefaultHover": return .outlineOnLightTransparentDefaultHoverGold
            case "outlineOnLightTransparentInfo": return .outlineOnLightTransparentInfoGold
            case "outlineOnLightTransparentInfoActive": return .outlineOnLightTransparentInfoActiveGold
            case "outlineOnLightTransparentInfoHover": return .outlineOnLightTransparentInfoHoverGold
            case "outlineOnLightTransparentNegative": return .outlineOnLightTransparentNegativeGold
            case "outlineOnLightTransparentNegativeActive": return .outlineOnLightTransparentNegativeActiveGold
            case "outlineOnLightTransparentNegativeHover": return .outlineOnLightTransparentNegativeHoverGold
            case "outlineOnLightTransparentPositive": return .outlineOnLightTransparentPositiveGold
            case "outlineOnLightTransparentPositiveActive": return .outlineOnLightTransparentPositiveActiveGold
            case "outlineOnLightTransparentPositiveHover": return .outlineOnLightTransparentPositiveHoverGold
            case "outlineOnLightTransparentPrimary": return .outlineOnLightTransparentPrimaryGold
            case "outlineOnLightTransparentPrimaryActive": return .outlineOnLightTransparentPrimaryActiveGold
            case "outlineOnLightTransparentPrimaryHover": return .outlineOnLightTransparentPrimaryHoverGold
            case "outlineOnLightTransparentSecondary": return .outlineOnLightTransparentSecondaryGold
            case "outlineOnLightTransparentSecondaryActive": return .outlineOnLightTransparentSecondaryActiveGold
            case "outlineOnLightTransparentSecondaryHover": return .outlineOnLightTransparentSecondaryHoverGold
            case "outlineOnLightTransparentTertiary": return .outlineOnLightTransparentTertiaryGold
            case "outlineOnLightTransparentTertiaryActive": return .outlineOnLightTransparentTertiaryActiveGold
            case "outlineOnLightTransparentTertiaryHover": return .outlineOnLightTransparentTertiaryHoverGold
            case "outlineOnLightTransparentWarning": return .outlineOnLightTransparentWarningGold
            case "outlineOnLightTransparentWarningActive": return .outlineOnLightTransparentWarningActiveGold
            case "outlineOnLightTransparentWarningHover": return .outlineOnLightTransparentWarningHoverGold
            case "outlineOnLightWarning": return .outlineOnLightWarningGold
            case "outlineOnLightWarningActive": return .outlineOnLightWarningActiveGold
            case "outlineOnLightWarningHover": return .outlineOnLightWarningHoverGold
            case "outlineOnLightWarningMinor": return .outlineOnLightWarningMinorGold
            case "outlineOnLightWarningMinorActive": return .outlineOnLightWarningMinorActiveGold
            case "outlineOnLightWarningMinorHover": return .outlineOnLightWarningMinorHoverGold
            case "overlayDefaultBlur": return .overlayDefaultBlurGold
            case "overlayDefaultHard": return .overlayDefaultHardGold
            case "overlayDefaultSoft": return .overlayDefaultSoftGold
            case "overlayInverseBlur": return .overlayInverseBlurGold
            case "overlayInverseHard": return .overlayInverseHardGold
            case "overlayInverseSoft": return .overlayInverseSoftGold
            case "overlayOnDarkBlur": return .overlayOnDarkBlurGold
            case "overlayOnDarkHard": return .overlayOnDarkHardGold
            case "overlayOnDarkSoft": return .overlayOnDarkSoftGold
            case "overlayOnLightBlur": return .overlayOnLightBlurGold
            case "overlayOnLightHard": return .overlayOnLightHardGold
            case "overlayOnLightSoft": return .overlayOnLightSoftGold
            case "surfaceDefaultAccent": return .surfaceDefaultAccentGold
            case "surfaceDefaultAccentActive": return .surfaceDefaultAccentActiveGold
            case "surfaceDefaultAccentB2B": return .surfaceDefaultAccentB2BGold
            case "surfaceDefaultAccentB2BActive": return .surfaceDefaultAccentB2BActiveGold
            case "surfaceDefaultAccentB2BHover": return .surfaceDefaultAccentB2BHoverGold
            case "surfaceDefaultAccentBlue": return .surfaceDefaultAccentBlueGold
            case "surfaceDefaultAccentBlueActive": return .surfaceDefaultAccentBlueActiveGold
            case "surfaceDefaultAccentBlueHover": return .surfaceDefaultAccentBlueHoverGold
            case "surfaceDefaultAccentDiscount": return .surfaceDefaultAccentDiscountGold
            case "surfaceDefaultAccentDiscountActive": return .surfaceDefaultAccentDiscountActiveGold
            case "surfaceDefaultAccentDiscountHover": return .surfaceDefaultAccentDiscountHoverGold
            case "surfaceDefaultAccentGold": return .surfaceDefaultAccentGoldGold
            case "surfaceDefaultAccentGoldActive": return .surfaceDefaultAccentGoldActiveGold
            case "surfaceDefaultAccentGoldHover": return .surfaceDefaultAccentGoldHoverGold
            case "surfaceDefaultAccentHover": return .surfaceDefaultAccentHoverGold
            case "surfaceDefaultAccentMinor": return .surfaceDefaultAccentMinorGold
            case "surfaceDefaultAccentMinorActive": return .surfaceDefaultAccentMinorActiveGold
            case "surfaceDefaultAccentMinorHover": return .surfaceDefaultAccentMinorHoverGold
            case "surfaceDefaultAdditional": return .surfaceDefaultAdditionalGold
            case "surfaceDefaultAdditionalActive": return .surfaceDefaultAdditionalActiveGold
            case "surfaceDefaultAdditionalHover": return .surfaceDefaultAdditionalHoverGold
            case "surfaceDefaultClear": return .surfaceDefaultClearGold
            case "surfaceDefaultClearActive": return .surfaceDefaultClearActiveGold
            case "surfaceDefaultClearHover": return .surfaceDefaultClearHoverGold
            case "surfaceDefaultInfo": return .surfaceDefaultInfoGold
            case "surfaceDefaultInfoActive": return .surfaceDefaultInfoActiveGold
            case "surfaceDefaultInfoHover": return .surfaceDefaultInfoHoverGold
            case "surfaceDefaultInfoMinor": return .surfaceDefaultInfoMinorGold
            case "surfaceDefaultInfoMinorActive": return .surfaceDefaultInfoMinorActiveGold
            case "surfaceDefaultInfoMinorHover": return .surfaceDefaultInfoMinorHoverGold
            case "surfaceDefaultNegative": return .surfaceDefaultNegativeGold
            case "surfaceDefaultNegativeActive": return .surfaceDefaultNegativeActiveGold
            case "surfaceDefaultNegativeHover": return .surfaceDefaultNegativeHoverGold
            case "surfaceDefaultNegativeMinor": return .surfaceDefaultNegativeMinorGold
            case "surfaceDefaultNegativeMinorActive": return .surfaceDefaultNegativeMinorActiveGold
            case "surfaceDefaultNegativeMinorHover": return .surfaceDefaultNegativeMinorHoverGold
            case "surfaceDefaultPositive": return .surfaceDefaultPositiveGold
            case "surfaceDefaultPositiveActive": return .surfaceDefaultPositiveActiveGold
            case "surfaceDefaultPositiveHover": return .surfaceDefaultPositiveHoverGold
            case "surfaceDefaultPositiveMinor": return .surfaceDefaultPositiveMinorGold
            case "surfaceDefaultPositiveMinorActive": return .surfaceDefaultPositiveMinorActiveGold
            case "surfaceDefaultPositiveMinorHover": return .surfaceDefaultPositiveMinorHoverGold
            case "surfaceDefaultPromo": return .surfaceDefaultPromoGold
            case "surfaceDefaultPromoActive": return .surfaceDefaultPromoActiveGold
            case "surfaceDefaultPromoHover": return .surfaceDefaultPromoHoverGold
            case "surfaceDefaultPromoMinor": return .surfaceDefaultPromoMinorGold
            case "surfaceDefaultPromoMinorActive": return .surfaceDefaultPromoMinorActiveGold
            case "surfaceDefaultPromoMinorHover": return .surfaceDefaultPromoMinorHoverGold
            case "surfaceDefaultSolidCard": return .surfaceDefaultSolidCardGold
            case "surfaceDefaultSolidCardActive": return .surfaceDefaultSolidCardActiveGold
            case "surfaceDefaultSolidCardBrightness": return .surfaceDefaultSolidCardBrightnessGold
            case "surfaceDefaultSolidCardHover": return .surfaceDefaultSolidCardHoverGold
            case "surfaceDefaultSolidDefault": return .surfaceDefaultSolidDefaultGold
            case "surfaceDefaultSolidDefaultActive": return .surfaceDefaultSolidDefaultActiveGold
            case "surfaceDefaultSolidDefaultHover": return .surfaceDefaultSolidDefaultHoverGold
            case "surfaceDefaultSolidPrimary": return .surfaceDefaultSolidPrimaryGold
            case "surfaceDefaultSolidPrimaryActive": return .surfaceDefaultSolidPrimaryActiveGold
            case "surfaceDefaultSolidPrimaryBrightness": return .surfaceDefaultSolidPrimaryBrightnessGold
            case "surfaceDefaultSolidPrimaryHover": return .surfaceDefaultSolidPrimaryHoverGold
            case "surfaceDefaultSolidSecondary": return .surfaceDefaultSolidSecondaryGold
            case "surfaceDefaultSolidSecondaryActive": return .surfaceDefaultSolidSecondaryActiveGold
            case "surfaceDefaultSolidSecondaryHover": return .surfaceDefaultSolidSecondaryHoverGold
            case "surfaceDefaultSolidTertiary": return .surfaceDefaultSolidTertiaryGold
            case "surfaceDefaultSolidTertiaryActive": return .surfaceDefaultSolidTertiaryActiveGold
            case "surfaceDefaultSolidTertiaryHover": return .surfaceDefaultSolidTertiaryHoverGold
            case "surfaceDefaultTransparentAccent": return .surfaceDefaultTransparentAccentGold
            case "surfaceDefaultTransparentAccentActive": return .surfaceDefaultTransparentAccentActiveGold
            case "surfaceDefaultTransparentAccentHover": return .surfaceDefaultTransparentAccentHoverGold
            case "surfaceDefaultTransparentCard": return .surfaceDefaultTransparentCardGold
            case "surfaceDefaultTransparentCardActive": return .surfaceDefaultTransparentCardActiveGold
            case "surfaceDefaultTransparentCardBrightness": return .surfaceDefaultTransparentCardBrightnessGold
            case "surfaceDefaultTransparentCardHover": return .surfaceDefaultTransparentCardHoverGold
            case "surfaceDefaultTransparentDeep": return .surfaceDefaultTransparentDeepGold
            case "surfaceDefaultTransparentDeepActive": return .surfaceDefaultTransparentDeepActiveGold
            case "surfaceDefaultTransparentDeepHover": return .surfaceDefaultTransparentDeepHoverGold
            case "surfaceDefaultTransparentInfo": return .surfaceDefaultTransparentInfoGold
            case "surfaceDefaultTransparentInfoActive": return .surfaceDefaultTransparentInfoActiveGold
            case "surfaceDefaultTransparentInfoHover": return .surfaceDefaultTransparentInfoHoverGold
            case "surfaceDefaultTransparentNegative": return .surfaceDefaultTransparentNegativeGold
            case "surfaceDefaultTransparentNegativeActive": return .surfaceDefaultTransparentNegativeActiveGold
            case "surfaceDefaultTransparentNegativeHover": return .surfaceDefaultTransparentNegativeHoverGold
            case "surfaceDefaultTransparentPositive": return .surfaceDefaultTransparentPositiveGold
            case "surfaceDefaultTransparentPositiveActive": return .surfaceDefaultTransparentPositiveActiveGold
            case "surfaceDefaultTransparentPositiveHover": return .surfaceDefaultTransparentPositiveHoverGold
            case "surfaceDefaultTransparentPrimary": return .surfaceDefaultTransparentPrimaryGold
            case "surfaceDefaultTransparentPrimaryActive": return .surfaceDefaultTransparentPrimaryActiveGold
            case "surfaceDefaultTransparentPrimaryHover": return .surfaceDefaultTransparentPrimaryHoverGold
            case "surfaceDefaultTransparentPromo": return .surfaceDefaultTransparentPromoGold
            case "surfaceDefaultTransparentPromoActive": return .surfaceDefaultTransparentPromoActiveGold
            case "surfaceDefaultTransparentPromoHover": return .surfaceDefaultTransparentPromoHoverGold
            case "surfaceDefaultTransparentSecondary": return .surfaceDefaultTransparentSecondaryGold
            case "surfaceDefaultTransparentSecondaryActive": return .surfaceDefaultTransparentSecondaryActiveGold
            case "surfaceDefaultTransparentSecondaryHover": return .surfaceDefaultTransparentSecondaryHoverGold
            case "surfaceDefaultTransparentTertiary": return .surfaceDefaultTransparentTertiaryGold
            case "surfaceDefaultTransparentTertiaryActive": return .surfaceDefaultTransparentTertiaryActiveGold
            case "surfaceDefaultTransparentTertiaryHover": return .surfaceDefaultTransparentTertiaryHoverGold
            case "surfaceDefaultTransparentWarning": return .surfaceDefaultTransparentWarningGold
            case "surfaceDefaultTransparentWarningActive": return .surfaceDefaultTransparentWarningActiveGold
            case "surfaceDefaultTransparentWarningHover": return .surfaceDefaultTransparentWarningHoverGold
            case "surfaceDefaultWarning": return .surfaceDefaultWarningGold
            case "surfaceDefaultWarningActive": return .surfaceDefaultWarningActiveGold
            case "surfaceDefaultWarningHover": return .surfaceDefaultWarningHoverGold
            case "surfaceDefaultWarningMinor": return .surfaceDefaultWarningMinorGold
            case "surfaceDefaultWarningMinorActive": return .surfaceDefaultWarningMinorActiveGold
            case "surfaceDefaultWarningMinorHover": return .surfaceDefaultWarningMinorHoverGold
            case "surfaceInverseAccent": return .surfaceInverseAccentGold
            case "surfaceInverseAccentActive": return .surfaceInverseAccentActiveGold
            case "surfaceInverseAccentHover": return .surfaceInverseAccentHoverGold
            case "surfaceInverseAccentMinor": return .surfaceInverseAccentMinorGold
            case "surfaceInverseAccentMinorActive": return .surfaceInverseAccentMinorActiveGold
            case "surfaceInverseAccentMinorHover": return .surfaceInverseAccentMinorHoverGold
            case "surfaceInverseClear": return .surfaceInverseClearGold
            case "surfaceInverseClearActive": return .surfaceInverseClearActiveGold
            case "surfaceInverseClearHover": return .surfaceInverseClearHoverGold
            case "surfaceInverseInfo": return .surfaceInverseInfoGold
            case "surfaceInverseInfoActive": return .surfaceInverseInfoActiveGold
            case "surfaceInverseInfoHover": return .surfaceInverseInfoHoverGold
            case "surfaceInverseInfoMinor": return .surfaceInverseInfoMinorGold
            case "surfaceInverseInfoMinorActive": return .surfaceInverseInfoMinorActiveGold
            case "surfaceInverseInfoMinorHover": return .surfaceInverseInfoMinorHoverGold
            case "surfaceInverseNegative": return .surfaceInverseNegativeGold
            case "surfaceInverseNegativeActive": return .surfaceInverseNegativeActiveGold
            case "surfaceInverseNegativeHover": return .surfaceInverseNegativeHoverGold
            case "surfaceInverseNegativeMinor": return .surfaceInverseNegativeMinorGold
            case "surfaceInverseNegativeMinorActive": return .surfaceInverseNegativeMinorActiveGold
            case "surfaceInverseNegativeMinorHover": return .surfaceInverseNegativeMinorHoverGold
            case "surfaceInversePositive": return .surfaceInversePositiveGold
            case "surfaceInversePositiveActive": return .surfaceInversePositiveActiveGold
            case "surfaceInversePositiveHover": return .surfaceInversePositiveHoverGold
            case "surfaceInversePositiveMinor": return .surfaceInversePositiveMinorGold
            case "surfaceInversePositiveMinorActive": return .surfaceInversePositiveMinorActiveGold
            case "surfaceInversePositiveMinorHover": return .surfaceInversePositiveMinorHoverGold
            case "surfaceInversePromo": return .surfaceInversePromoGold
            case "surfaceInversePromoActive": return .surfaceInversePromoActiveGold
            case "surfaceInversePromoHover": return .surfaceInversePromoHoverGold
            case "surfaceInversePromoMinor": return .surfaceInversePromoMinorGold
            case "surfaceInversePromoMinorActive": return .surfaceInversePromoMinorActiveGold
            case "surfaceInversePromoMinorHover": return .surfaceInversePromoMinorHoverGold
            case "surfaceInverseSolidCard": return .surfaceInverseSolidCardGold
            case "surfaceInverseSolidCardActive": return .surfaceInverseSolidCardActiveGold
            case "surfaceInverseSolidCardBrightness": return .surfaceInverseSolidCardBrightnessGold
            case "surfaceInverseSolidCardHover": return .surfaceInverseSolidCardHoverGold
            case "surfaceInverseSolidDefault": return .surfaceInverseSolidDefaultGold
            case "surfaceInverseSolidDefaultActive": return .surfaceInverseSolidDefaultActiveGold
            case "surfaceInverseSolidDefaultHover": return .surfaceInverseSolidDefaultHoverGold
            case "surfaceInverseSolidPrimary": return .surfaceInverseSolidPrimaryGold
            case "surfaceInverseSolidPrimaryActive": return .surfaceInverseSolidPrimaryActiveGold
            case "surfaceInverseSolidPrimaryBrightness": return .surfaceInverseSolidPrimaryBrightnessGold
            case "surfaceInverseSolidPrimaryHover": return .surfaceInverseSolidPrimaryHoverGold
            case "surfaceInverseSolidSecondary": return .surfaceInverseSolidSecondaryGold
            case "surfaceInverseSolidSecondaryActive": return .surfaceInverseSolidSecondaryActiveGold
            case "surfaceInverseSolidSecondaryHover": return .surfaceInverseSolidSecondaryHoverGold
            case "surfaceInverseSolidTertiary": return .surfaceInverseSolidTertiaryGold
            case "surfaceInverseSolidTertiaryActive": return .surfaceInverseSolidTertiaryActiveGold
            case "surfaceInverseSolidTertiaryHover": return .surfaceInverseSolidTertiaryHoverGold
            case "surfaceInverseTransparentAccent": return .surfaceInverseTransparentAccentGold
            case "surfaceInverseTransparentAccentActive": return .surfaceInverseTransparentAccentActiveGold
            case "surfaceInverseTransparentAccentHover": return .surfaceInverseTransparentAccentHoverGold
            case "surfaceInverseTransparentCard": return .surfaceInverseTransparentCardGold
            case "surfaceInverseTransparentCardActive": return .surfaceInverseTransparentCardActiveGold
            case "surfaceInverseTransparentCardBrightness": return .surfaceInverseTransparentCardBrightnessGold
            case "surfaceInverseTransparentCardHover": return .surfaceInverseTransparentCardHoverGold
            case "surfaceInverseTransparentDeep": return .surfaceInverseTransparentDeepGold
            case "surfaceInverseTransparentDeepActive": return .surfaceInverseTransparentDeepActiveGold
            case "surfaceInverseTransparentDeepHover": return .surfaceInverseTransparentDeepHoverGold
            case "surfaceInverseTransparentInfo": return .surfaceInverseTransparentInfoGold
            case "surfaceInverseTransparentInfoActive": return .surfaceInverseTransparentInfoActiveGold
            case "surfaceInverseTransparentInfoHover": return .surfaceInverseTransparentInfoHoverGold
            case "surfaceInverseTransparentNegative": return .surfaceInverseTransparentNegativeGold
            case "surfaceInverseTransparentNegativeActive": return .surfaceInverseTransparentNegativeActiveGold
            case "surfaceInverseTransparentNegativeHover": return .surfaceInverseTransparentNegativeHoverGold
            case "surfaceInverseTransparentPositive": return .surfaceInverseTransparentPositiveGold
            case "surfaceInverseTransparentPositiveActive": return .surfaceInverseTransparentPositiveActiveGold
            case "surfaceInverseTransparentPositiveHover": return .surfaceInverseTransparentPositiveHoverGold
            case "surfaceInverseTransparentPrimary": return .surfaceInverseTransparentPrimaryGold
            case "surfaceInverseTransparentPrimaryActive": return .surfaceInverseTransparentPrimaryActiveGold
            case "surfaceInverseTransparentPrimaryHover": return .surfaceInverseTransparentPrimaryHoverGold
            case "surfaceInverseTransparentPromo": return .surfaceInverseTransparentPromoGold
            case "surfaceInverseTransparentPromoActive": return .surfaceInverseTransparentPromoActiveGold
            case "surfaceInverseTransparentPromoHover": return .surfaceInverseTransparentPromoHoverGold
            case "surfaceInverseTransparentSecondary": return .surfaceInverseTransparentSecondaryGold
            case "surfaceInverseTransparentSecondaryActive": return .surfaceInverseTransparentSecondaryActiveGold
            case "surfaceInverseTransparentSecondaryHover": return .surfaceInverseTransparentSecondaryHoverGold
            case "surfaceInverseTransparentTertiary": return .surfaceInverseTransparentTertiaryGold
            case "surfaceInverseTransparentTertiaryActive": return .surfaceInverseTransparentTertiaryActiveGold
            case "surfaceInverseTransparentTertiaryHover": return .surfaceInverseTransparentTertiaryHoverGold
            case "surfaceInverseTransparentWarning": return .surfaceInverseTransparentWarningGold
            case "surfaceInverseTransparentWarningActive": return .surfaceInverseTransparentWarningActiveGold
            case "surfaceInverseTransparentWarningHover": return .surfaceInverseTransparentWarningHoverGold
            case "surfaceInverseWarning": return .surfaceInverseWarningGold
            case "surfaceInverseWarningActive": return .surfaceInverseWarningActiveGold
            case "surfaceInverseWarningHover": return .surfaceInverseWarningHoverGold
            case "surfaceInverseWarningMinor": return .surfaceInverseWarningMinorGold
            case "surfaceInverseWarningMinorActive": return .surfaceInverseWarningMinorActiveGold
            case "surfaceInverseWarningMinorHover": return .surfaceInverseWarningMinorHoverGold
            case "surfaceOnDarkAccent": return .surfaceOnDarkAccentGold
            case "surfaceOnDarkAccentActive": return .surfaceOnDarkAccentActiveGold
            case "surfaceOnDarkAccentB2B": return .surfaceOnDarkAccentB2BGold
            case "surfaceOnDarkAccentB2BActive": return .surfaceOnDarkAccentB2BActiveGold
            case "surfaceOnDarkAccentB2BHover": return .surfaceOnDarkAccentB2BHoverGold
            case "surfaceOnDarkAccentBlue": return .surfaceOnDarkAccentBlueGold
            case "surfaceOnDarkAccentBlueActive": return .surfaceOnDarkAccentBlueActiveGold
            case "surfaceOnDarkAccentBlueHover": return .surfaceOnDarkAccentBlueHoverGold
            case "surfaceOnDarkAccentDiscount": return .surfaceOnDarkAccentDiscountGold
            case "surfaceOnDarkAccentDiscountActive": return .surfaceOnDarkAccentDiscountActiveGold
            case "surfaceOnDarkAccentDiscountHover": return .surfaceOnDarkAccentDiscountHoverGold
            case "surfaceOnDarkAccentGold": return .surfaceOnDarkAccentGoldGold
            case "surfaceOnDarkAccentGoldActive": return .surfaceOnDarkAccentGoldActiveGold
            case "surfaceOnDarkAccentGoldHover": return .surfaceOnDarkAccentGoldHoverGold
            case "surfaceOnDarkAccentHover": return .surfaceOnDarkAccentHoverGold
            case "surfaceOnDarkAccentMinor": return .surfaceOnDarkAccentMinorGold
            case "surfaceOnDarkAccentMinorActive": return .surfaceOnDarkAccentMinorActiveGold
            case "surfaceOnDarkAccentMinorHover": return .surfaceOnDarkAccentMinorHoverGold
            case "surfaceOnDarkAdditional": return .surfaceOnDarkAdditionalGold
            case "surfaceOnDarkAdditionalActive": return .surfaceOnDarkAdditionalActiveGold
            case "surfaceOnDarkAdditionalHover": return .surfaceOnDarkAdditionalHoverGold
            case "surfaceOnDarkClear": return .surfaceOnDarkClearGold
            case "surfaceOnDarkClearActive": return .surfaceOnDarkClearActiveGold
            case "surfaceOnDarkClearHover": return .surfaceOnDarkClearHoverGold
            case "surfaceOnDarkInfo": return .surfaceOnDarkInfoGold
            case "surfaceOnDarkInfoActive": return .surfaceOnDarkInfoActiveGold
            case "surfaceOnDarkInfoHover": return .surfaceOnDarkInfoHoverGold
            case "surfaceOnDarkInfoMinor": return .surfaceOnDarkInfoMinorGold
            case "surfaceOnDarkInfoMinorActive": return .surfaceOnDarkInfoMinorActiveGold
            case "surfaceOnDarkInfoMinorHover": return .surfaceOnDarkInfoMinorHoverGold
            case "surfaceOnDarkNegative": return .surfaceOnDarkNegativeGold
            case "surfaceOnDarkNegativeActive": return .surfaceOnDarkNegativeActiveGold
            case "surfaceOnDarkNegativeHover": return .surfaceOnDarkNegativeHoverGold
            case "surfaceOnDarkNegativeMinor": return .surfaceOnDarkNegativeMinorGold
            case "surfaceOnDarkNegativeMinorActive": return .surfaceOnDarkNegativeMinorActiveGold
            case "surfaceOnDarkNegativeMinorHover": return .surfaceOnDarkNegativeMinorHoverGold
            case "surfaceOnDarkPositive": return .surfaceOnDarkPositiveGold
            case "surfaceOnDarkPositiveActive": return .surfaceOnDarkPositiveActiveGold
            case "surfaceOnDarkPositiveHover": return .surfaceOnDarkPositiveHoverGold
            case "surfaceOnDarkPositiveMinor": return .surfaceOnDarkPositiveMinorGold
            case "surfaceOnDarkPositiveMinorActive": return .surfaceOnDarkPositiveMinorActiveGold
            case "surfaceOnDarkPositiveMinorHover": return .surfaceOnDarkPositiveMinorHoverGold
            case "surfaceOnDarkPromo": return .surfaceOnDarkPromoGold
            case "surfaceOnDarkPromoActive": return .surfaceOnDarkPromoActiveGold
            case "surfaceOnDarkPromoHover": return .surfaceOnDarkPromoHoverGold
            case "surfaceOnDarkPromoMinor": return .surfaceOnDarkPromoMinorGold
            case "surfaceOnDarkPromoMinorActive": return .surfaceOnDarkPromoMinorActiveGold
            case "surfaceOnDarkPromoMinorHover": return .surfaceOnDarkPromoMinorHoverGold
            case "surfaceOnDarkSolidCard": return .surfaceOnDarkSolidCardGold
            case "surfaceOnDarkSolidCardActive": return .surfaceOnDarkSolidCardActiveGold
            case "surfaceOnDarkSolidCardBrightness": return .surfaceOnDarkSolidCardBrightnessGold
            case "surfaceOnDarkSolidCardHover": return .surfaceOnDarkSolidCardHoverGold
            case "surfaceOnDarkSolidDefault": return .surfaceOnDarkSolidDefaultGold
            case "surfaceOnDarkSolidDefaultActive": return .surfaceOnDarkSolidDefaultActiveGold
            case "surfaceOnDarkSolidDefaultHover": return .surfaceOnDarkSolidDefaultHoverGold
            case "surfaceOnDarkSolidPrimary": return .surfaceOnDarkSolidPrimaryGold
            case "surfaceOnDarkSolidPrimaryActive": return .surfaceOnDarkSolidPrimaryActiveGold
            case "surfaceOnDarkSolidPrimaryBrightness": return .surfaceOnDarkSolidPrimaryBrightnessGold
            case "surfaceOnDarkSolidPrimaryHover": return .surfaceOnDarkSolidPrimaryHoverGold
            case "surfaceOnDarkSolidSecondary": return .surfaceOnDarkSolidSecondaryGold
            case "surfaceOnDarkSolidSecondaryActive": return .surfaceOnDarkSolidSecondaryActiveGold
            case "surfaceOnDarkSolidSecondaryHover": return .surfaceOnDarkSolidSecondaryHoverGold
            case "surfaceOnDarkSolidTertiary": return .surfaceOnDarkSolidTertiaryGold
            case "surfaceOnDarkSolidTertiaryActive": return .surfaceOnDarkSolidTertiaryActiveGold
            case "surfaceOnDarkSolidTertiaryHover": return .surfaceOnDarkSolidTertiaryHoverGold
            case "surfaceOnDarkTransparentAccent": return .surfaceOnDarkTransparentAccentGold
            case "surfaceOnDarkTransparentAccentActive": return .surfaceOnDarkTransparentAccentActiveGold
            case "surfaceOnDarkTransparentAccentHover": return .surfaceOnDarkTransparentAccentHoverGold
            case "surfaceOnDarkTransparentCard": return .surfaceOnDarkTransparentCardGold
            case "surfaceOnDarkTransparentCardActive": return .surfaceOnDarkTransparentCardActiveGold
            case "surfaceOnDarkTransparentCardBrightness": return .surfaceOnDarkTransparentCardBrightnessGold
            case "surfaceOnDarkTransparentCardHover": return .surfaceOnDarkTransparentCardHoverGold
            case "surfaceOnDarkTransparentDeep": return .surfaceOnDarkTransparentDeepGold
            case "surfaceOnDarkTransparentDeepActive": return .surfaceOnDarkTransparentDeepActiveGold
            case "surfaceOnDarkTransparentDeepHover": return .surfaceOnDarkTransparentDeepHoverGold
            case "surfaceOnDarkTransparentInfo": return .surfaceOnDarkTransparentInfoGold
            case "surfaceOnDarkTransparentInfoActive": return .surfaceOnDarkTransparentInfoActiveGold
            case "surfaceOnDarkTransparentInfoHover": return .surfaceOnDarkTransparentInfoHoverGold
            case "surfaceOnDarkTransparentNegative": return .surfaceOnDarkTransparentNegativeGold
            case "surfaceOnDarkTransparentNegativeActive": return .surfaceOnDarkTransparentNegativeActiveGold
            case "surfaceOnDarkTransparentNegativeHover": return .surfaceOnDarkTransparentNegativeHoverGold
            case "surfaceOnDarkTransparentPositive": return .surfaceOnDarkTransparentPositiveGold
            case "surfaceOnDarkTransparentPositiveActive": return .surfaceOnDarkTransparentPositiveActiveGold
            case "surfaceOnDarkTransparentPositiveHover": return .surfaceOnDarkTransparentPositiveHoverGold
            case "surfaceOnDarkTransparentPrimary": return .surfaceOnDarkTransparentPrimaryGold
            case "surfaceOnDarkTransparentPrimaryActive": return .surfaceOnDarkTransparentPrimaryActiveGold
            case "surfaceOnDarkTransparentPrimaryHover": return .surfaceOnDarkTransparentPrimaryHoverGold
            case "surfaceOnDarkTransparentPromo": return .surfaceOnDarkTransparentPromoGold
            case "surfaceOnDarkTransparentPromoActive": return .surfaceOnDarkTransparentPromoActiveGold
            case "surfaceOnDarkTransparentPromoHover": return .surfaceOnDarkTransparentPromoHoverGold
            case "surfaceOnDarkTransparentSecondary": return .surfaceOnDarkTransparentSecondaryGold
            case "surfaceOnDarkTransparentSecondaryActive": return .surfaceOnDarkTransparentSecondaryActiveGold
            case "surfaceOnDarkTransparentSecondaryHover": return .surfaceOnDarkTransparentSecondaryHoverGold
            case "surfaceOnDarkTransparentTertiary": return .surfaceOnDarkTransparentTertiaryGold
            case "surfaceOnDarkTransparentTertiaryActive": return .surfaceOnDarkTransparentTertiaryActiveGold
            case "surfaceOnDarkTransparentTertiaryHover": return .surfaceOnDarkTransparentTertiaryHoverGold
            case "surfaceOnDarkTransparentWarning": return .surfaceOnDarkTransparentWarningGold
            case "surfaceOnDarkTransparentWarningActive": return .surfaceOnDarkTransparentWarningActiveGold
            case "surfaceOnDarkTransparentWarningHover": return .surfaceOnDarkTransparentWarningHoverGold
            case "surfaceOnDarkWarning": return .surfaceOnDarkWarningGold
            case "surfaceOnDarkWarningActive": return .surfaceOnDarkWarningActiveGold
            case "surfaceOnDarkWarningHover": return .surfaceOnDarkWarningHoverGold
            case "surfaceOnDarkWarningMinor": return .surfaceOnDarkWarningMinorGold
            case "surfaceOnDarkWarningMinorActive": return .surfaceOnDarkWarningMinorActiveGold
            case "surfaceOnDarkWarningMinorHover": return .surfaceOnDarkWarningMinorHoverGold
            case "surfaceOnLightAccent": return .surfaceOnLightAccentGold
            case "surfaceOnLightAccentActive": return .surfaceOnLightAccentActiveGold
            case "surfaceOnLightAccentB2B": return .surfaceOnLightAccentB2BGold
            case "surfaceOnLightAccentB2BActive": return .surfaceOnLightAccentB2BActiveGold
            case "surfaceOnLightAccentB2BHover": return .surfaceOnLightAccentB2BHoverGold
            case "surfaceOnLightAccentBlue": return .surfaceOnLightAccentBlueGold
            case "surfaceOnLightAccentBlueActive": return .surfaceOnLightAccentBlueActiveGold
            case "surfaceOnLightAccentBlueHover": return .surfaceOnLightAccentBlueHoverGold
            case "surfaceOnLightAccentDiscount": return .surfaceOnLightAccentDiscountGold
            case "surfaceOnLightAccentDiscountActive": return .surfaceOnLightAccentDiscountActiveGold
            case "surfaceOnLightAccentDiscountHover": return .surfaceOnLightAccentDiscountHoverGold
            case "surfaceOnLightAccentGold": return .surfaceOnLightAccentGoldGold
            case "surfaceOnLightAccentGoldActive": return .surfaceOnLightAccentGoldActiveGold
            case "surfaceOnLightAccentGoldHover": return .surfaceOnLightAccentGoldHoverGold
            case "surfaceOnLightAccentHover": return .surfaceOnLightAccentHoverGold
            case "surfaceOnLightAccentMinor": return .surfaceOnLightAccentMinorGold
            case "surfaceOnLightAccentMinorActive": return .surfaceOnLightAccentMinorActiveGold
            case "surfaceOnLightAccentMinorHover": return .surfaceOnLightAccentMinorHoverGold
            case "surfaceOnLightAdditional": return .surfaceOnLightAdditionalGold
            case "surfaceOnLightAdditionalActive": return .surfaceOnLightAdditionalActiveGold
            case "surfaceOnLightAdditionalHover": return .surfaceOnLightAdditionalHoverGold
            case "surfaceOnLightClear": return .surfaceOnLightClearGold
            case "surfaceOnLightClearActive": return .surfaceOnLightClearActiveGold
            case "surfaceOnLightClearHover": return .surfaceOnLightClearHoverGold
            case "surfaceOnLightInfo": return .surfaceOnLightInfoGold
            case "surfaceOnLightInfoActive": return .surfaceOnLightInfoActiveGold
            case "surfaceOnLightInfoHover": return .surfaceOnLightInfoHoverGold
            case "surfaceOnLightInfoMinor": return .surfaceOnLightInfoMinorGold
            case "surfaceOnLightInfoMinorActive": return .surfaceOnLightInfoMinorActiveGold
            case "surfaceOnLightInfoMinorHover": return .surfaceOnLightInfoMinorHoverGold
            case "surfaceOnLightNegative": return .surfaceOnLightNegativeGold
            case "surfaceOnLightNegativeActive": return .surfaceOnLightNegativeActiveGold
            case "surfaceOnLightNegativeHover": return .surfaceOnLightNegativeHoverGold
            case "surfaceOnLightNegativeMinor": return .surfaceOnLightNegativeMinorGold
            case "surfaceOnLightNegativeMinorActive": return .surfaceOnLightNegativeMinorActiveGold
            case "surfaceOnLightNegativeMinorHover": return .surfaceOnLightNegativeMinorHoverGold
            case "surfaceOnLightPositive": return .surfaceOnLightPositiveGold
            case "surfaceOnLightPositiveActive": return .surfaceOnLightPositiveActiveGold
            case "surfaceOnLightPositiveHover": return .surfaceOnLightPositiveHoverGold
            case "surfaceOnLightPositiveMinor": return .surfaceOnLightPositiveMinorGold
            case "surfaceOnLightPositiveMinorActive": return .surfaceOnLightPositiveMinorActiveGold
            case "surfaceOnLightPositiveMinorHover": return .surfaceOnLightPositiveMinorHoverGold
            case "surfaceOnLightPromo": return .surfaceOnLightPromoGold
            case "surfaceOnLightPromoActive": return .surfaceOnLightPromoActiveGold
            case "surfaceOnLightPromoHover": return .surfaceOnLightPromoHoverGold
            case "surfaceOnLightPromoMinor": return .surfaceOnLightPromoMinorGold
            case "surfaceOnLightPromoMinorActive": return .surfaceOnLightPromoMinorActiveGold
            case "surfaceOnLightPromoMinorHover": return .surfaceOnLightPromoMinorHoverGold
            case "surfaceOnLightSolidCard": return .surfaceOnLightSolidCardGold
            case "surfaceOnLightSolidCardActive": return .surfaceOnLightSolidCardActiveGold
            case "surfaceOnLightSolidCardBrightness": return .surfaceOnLightSolidCardBrightnessGold
            case "surfaceOnLightSolidCardHover": return .surfaceOnLightSolidCardHoverGold
            case "surfaceOnLightSolidDefault": return .surfaceOnLightSolidDefaultGold
            case "surfaceOnLightSolidDefaultActive": return .surfaceOnLightSolidDefaultActiveGold
            case "surfaceOnLightSolidDefaultHover": return .surfaceOnLightSolidDefaultHoverGold
            case "surfaceOnLightSolidPrimary": return .surfaceOnLightSolidPrimaryGold
            case "surfaceOnLightSolidPrimaryActive": return .surfaceOnLightSolidPrimaryActiveGold
            case "surfaceOnLightSolidPrimaryBrightness": return .surfaceOnLightSolidPrimaryBrightnessGold
            case "surfaceOnLightSolidPrimaryHover": return .surfaceOnLightSolidPrimaryHoverGold
            case "surfaceOnLightSolidSecondary": return .surfaceOnLightSolidSecondaryGold
            case "surfaceOnLightSolidSecondaryActive": return .surfaceOnLightSolidSecondaryActiveGold
            case "surfaceOnLightSolidSecondaryHover": return .surfaceOnLightSolidSecondaryHoverGold
            case "surfaceOnLightSolidTertiary": return .surfaceOnLightSolidTertiaryGold
            case "surfaceOnLightSolidTertiaryActive": return .surfaceOnLightSolidTertiaryActiveGold
            case "surfaceOnLightSolidTertiaryHover": return .surfaceOnLightSolidTertiaryHoverGold
            case "surfaceOnLightTransparentAccent": return .surfaceOnLightTransparentAccentGold
            case "surfaceOnLightTransparentAccentActive": return .surfaceOnLightTransparentAccentActiveGold
            case "surfaceOnLightTransparentAccentHover": return .surfaceOnLightTransparentAccentHoverGold
            case "surfaceOnLightTransparentCard": return .surfaceOnLightTransparentCardGold
            case "surfaceOnLightTransparentCardActive": return .surfaceOnLightTransparentCardActiveGold
            case "surfaceOnLightTransparentCardBrightness": return .surfaceOnLightTransparentCardBrightnessGold
            case "surfaceOnLightTransparentCardHover": return .surfaceOnLightTransparentCardHoverGold
            case "surfaceOnLightTransparentDeep": return .surfaceOnLightTransparentDeepGold
            case "surfaceOnLightTransparentDeepActive": return .surfaceOnLightTransparentDeepActiveGold
            case "surfaceOnLightTransparentDeepHover": return .surfaceOnLightTransparentDeepHoverGold
            case "surfaceOnLightTransparentInfo": return .surfaceOnLightTransparentInfoGold
            case "surfaceOnLightTransparentInfoActive": return .surfaceOnLightTransparentInfoActiveGold
            case "surfaceOnLightTransparentInfoHover": return .surfaceOnLightTransparentInfoHoverGold
            case "surfaceOnLightTransparentNegative": return .surfaceOnLightTransparentNegativeGold
            case "surfaceOnLightTransparentNegativeActive": return .surfaceOnLightTransparentNegativeActiveGold
            case "surfaceOnLightTransparentNegativeHover": return .surfaceOnLightTransparentNegativeHoverGold
            case "surfaceOnLightTransparentPositive": return .surfaceOnLightTransparentPositiveGold
            case "surfaceOnLightTransparentPositiveActive": return .surfaceOnLightTransparentPositiveActiveGold
            case "surfaceOnLightTransparentPositiveHover": return .surfaceOnLightTransparentPositiveHoverGold
            case "surfaceOnLightTransparentPrimary": return .surfaceOnLightTransparentPrimaryGold
            case "surfaceOnLightTransparentPrimaryActive": return .surfaceOnLightTransparentPrimaryActiveGold
            case "surfaceOnLightTransparentPrimaryHover": return .surfaceOnLightTransparentPrimaryHoverGold
            case "surfaceOnLightTransparentPromo": return .surfaceOnLightTransparentPromoGold
            case "surfaceOnLightTransparentPromoActive": return .surfaceOnLightTransparentPromoActiveGold
            case "surfaceOnLightTransparentPromoHover": return .surfaceOnLightTransparentPromoHoverGold
            case "surfaceOnLightTransparentSecondary": return .surfaceOnLightTransparentSecondaryGold
            case "surfaceOnLightTransparentSecondaryActive": return .surfaceOnLightTransparentSecondaryActiveGold
            case "surfaceOnLightTransparentSecondaryHover": return .surfaceOnLightTransparentSecondaryHoverGold
            case "surfaceOnLightTransparentTertiary": return .surfaceOnLightTransparentTertiaryGold
            case "surfaceOnLightTransparentTertiaryActive": return .surfaceOnLightTransparentTertiaryActiveGold
            case "surfaceOnLightTransparentTertiaryHover": return .surfaceOnLightTransparentTertiaryHoverGold
            case "surfaceOnLightTransparentWarning": return .surfaceOnLightTransparentWarningGold
            case "surfaceOnLightTransparentWarningActive": return .surfaceOnLightTransparentWarningActiveGold
            case "surfaceOnLightTransparentWarningHover": return .surfaceOnLightTransparentWarningHoverGold
            case "surfaceOnLightWarning": return .surfaceOnLightWarningGold
            case "surfaceOnLightWarningActive": return .surfaceOnLightWarningActiveGold
            case "surfaceOnLightWarningHover": return .surfaceOnLightWarningHoverGold
            case "surfaceOnLightWarningMinor": return .surfaceOnLightWarningMinorGold
            case "surfaceOnLightWarningMinorActive": return .surfaceOnLightWarningMinorActiveGold
            case "surfaceOnLightWarningMinorHover": return .surfaceOnLightWarningMinorHoverGold
            case "textDefaultAccent": return .textDefaultAccentGold
            case "textDefaultAccentActive": return .textDefaultAccentActiveGold
            case "textDefaultAccentB2B": return .textDefaultAccentB2BGold
            case "textDefaultAccentB2BActive": return .textDefaultAccentB2BActiveGold
            case "textDefaultAccentB2BHover": return .textDefaultAccentB2BHoverGold
            case "textDefaultAccentDiscount": return .textDefaultAccentDiscountGold
            case "textDefaultAccentDiscountActive": return .textDefaultAccentDiscountActiveGold
            case "textDefaultAccentDiscountHover": return .textDefaultAccentDiscountHoverGold
            case "textDefaultAccentGold": return .textDefaultAccentGoldGold
            case "textDefaultAccentGoldActive": return .textDefaultAccentGoldActiveGold
            case "textDefaultAccentGoldHover": return .textDefaultAccentGoldHoverGold
            case "textDefaultAccentHover": return .textDefaultAccentHoverGold
            case "textDefaultAccentMinor": return .textDefaultAccentMinorGold
            case "textDefaultAccentMinorActive": return .textDefaultAccentMinorActiveGold
            case "textDefaultAccentMinorHover": return .textDefaultAccentMinorHoverGold
            case "textDefaultInfo": return .textDefaultInfoGold
            case "textDefaultInfoActive": return .textDefaultInfoActiveGold
            case "textDefaultInfoHover": return .textDefaultInfoHoverGold
            case "textDefaultInfoMinor": return .textDefaultInfoMinorGold
            case "textDefaultInfoMinorActive": return .textDefaultInfoMinorActiveGold
            case "textDefaultInfoMinorHover": return .textDefaultInfoMinorHoverGold
            case "textDefaultNegative": return .textDefaultNegativeGold
            case "textDefaultNegativeActive": return .textDefaultNegativeActiveGold
            case "textDefaultNegativeHover": return .textDefaultNegativeHoverGold
            case "textDefaultNegativeMinor": return .textDefaultNegativeMinorGold
            case "textDefaultNegativeMinorActive": return .textDefaultNegativeMinorActiveGold
            case "textDefaultNegativeMinorHover": return .textDefaultNegativeMinorHoverGold
            case "textDefaultParagraph": return .textDefaultParagraphGold
            case "textDefaultParagraphActive": return .textDefaultParagraphActiveGold
            case "textDefaultParagraphHover": return .textDefaultParagraphHoverGold
            case "textDefaultPositive": return .textDefaultPositiveGold
            case "textDefaultPositiveActive": return .textDefaultPositiveActiveGold
            case "textDefaultPositiveHover": return .textDefaultPositiveHoverGold
            case "textDefaultPositiveMinor": return .textDefaultPositiveMinorGold
            case "textDefaultPositiveMinorActive": return .textDefaultPositiveMinorActiveGold
            case "textDefaultPositiveMinorHover": return .textDefaultPositiveMinorHoverGold
            case "textDefaultPrimary": return .textDefaultPrimaryGold
            case "textDefaultPrimaryActive": return .textDefaultPrimaryActiveGold
            case "textDefaultPrimaryBrightness": return .textDefaultPrimaryBrightnessGold
            case "textDefaultPrimaryHover": return .textDefaultPrimaryHoverGold
            case "textDefaultPromo": return .textDefaultPromoGold
            case "textDefaultPromoActive": return .textDefaultPromoActiveGold
            case "textDefaultPromoHover": return .textDefaultPromoHoverGold
            case "textDefaultPromoMinor": return .textDefaultPromoMinorGold
            case "textDefaultPromoMinorActive": return .textDefaultPromoMinorActiveGold
            case "textDefaultPromoMinorHover": return .textDefaultPromoMinorHoverGold
            case "textDefaultSecondary": return .textDefaultSecondaryGold
            case "textDefaultSecondaryActive": return .textDefaultSecondaryActiveGold
            case "textDefaultSecondaryHover": return .textDefaultSecondaryHoverGold
            case "textDefaultTertiary": return .textDefaultTertiaryGold
            case "textDefaultTertiaryActive": return .textDefaultTertiaryActiveGold
            case "textDefaultTertiaryHover": return .textDefaultTertiaryHoverGold
            case "textDefaultWarning": return .textDefaultWarningGold
            case "textDefaultWarningActive": return .textDefaultWarningActiveGold
            case "textDefaultWarningHover": return .textDefaultWarningHoverGold
            case "textDefaultWarningMinor": return .textDefaultWarningMinorGold
            case "textDefaultWarningMinorActive": return .textDefaultWarningMinorActiveGold
            case "textDefaultWarningMinorHover": return .textDefaultWarningMinorHoverGold
            case "textInverseAccent": return .textInverseAccentGold
            case "textInverseAccentActive": return .textInverseAccentActiveGold
            case "textInverseAccentHover": return .textInverseAccentHoverGold
            case "textInverseAccentMinor": return .textInverseAccentMinorGold
            case "textInverseAccentMinorActive": return .textInverseAccentMinorActiveGold
            case "textInverseAccentMinorHover": return .textInverseAccentMinorHoverGold
            case "textInverseInfo": return .textInverseInfoGold
            case "textInverseInfoActive": return .textInverseInfoActiveGold
            case "textInverseInfoHover": return .textInverseInfoHoverGold
            case "textInverseInfoMinor": return .textInverseInfoMinorGold
            case "textInverseInfoMinorActive": return .textInverseInfoMinorActiveGold
            case "textInverseInfoMinorHover": return .textInverseInfoMinorHoverGold
            case "textInverseNegative": return .textInverseNegativeGold
            case "textInverseNegativeActive": return .textInverseNegativeActiveGold
            case "textInverseNegativeHover": return .textInverseNegativeHoverGold
            case "textInverseNegativeMinor": return .textInverseNegativeMinorGold
            case "textInverseNegativeMinorActive": return .textInverseNegativeMinorActiveGold
            case "textInverseNegativeMinorHover": return .textInverseNegativeMinorHoverGold
            case "textInverseParagraph": return .textInverseParagraphGold
            case "textInverseParagraphActive": return .textInverseParagraphActiveGold
            case "textInverseParagraphHover": return .textInverseParagraphHoverGold
            case "textInversePositive": return .textInversePositiveGold
            case "textInversePositiveActive": return .textInversePositiveActiveGold
            case "textInversePositiveHover": return .textInversePositiveHoverGold
            case "textInversePositiveMinor": return .textInversePositiveMinorGold
            case "textInversePositiveMinorActive": return .textInversePositiveMinorActiveGold
            case "textInversePositiveMinorHover": return .textInversePositiveMinorHoverGold
            case "textInversePrimary": return .textInversePrimaryGold
            case "textInversePrimaryActive": return .textInversePrimaryActiveGold
            case "textInversePrimaryBrightness": return .textInversePrimaryBrightnessGold
            case "textInversePrimaryHover": return .textInversePrimaryHoverGold
            case "textInversePromo": return .textInversePromoGold
            case "textInversePromoActive": return .textInversePromoActiveGold
            case "textInversePromoHover": return .textInversePromoHoverGold
            case "textInversePromoMinor": return .textInversePromoMinorGold
            case "textInversePromoMinorActive": return .textInversePromoMinorActiveGold
            case "textInversePromoMinorHover": return .textInversePromoMinorHoverGold
            case "textInverseSecondary": return .textInverseSecondaryGold
            case "textInverseSecondaryActive": return .textInverseSecondaryActiveGold
            case "textInverseSecondaryHover": return .textInverseSecondaryHoverGold
            case "textInverseTertiary": return .textInverseTertiaryGold
            case "textInverseTertiaryActive": return .textInverseTertiaryActiveGold
            case "textInverseTertiaryHover": return .textInverseTertiaryHoverGold
            case "textInverseWarning": return .textInverseWarningGold
            case "textInverseWarningActive": return .textInverseWarningActiveGold
            case "textInverseWarningHover": return .textInverseWarningHoverGold
            case "textInverseWarningMinor": return .textInverseWarningMinorGold
            case "textInverseWarningMinorActive": return .textInverseWarningMinorActiveGold
            case "textInverseWarningMinorHover": return .textInverseWarningMinorHoverGold
            case "textOnDarkAccent": return .textOnDarkAccentGold
            case "textOnDarkAccentActive": return .textOnDarkAccentActiveGold
            case "textOnDarkAccentB2B": return .textOnDarkAccentB2BGold
            case "textOnDarkAccentB2BActive": return .textOnDarkAccentB2BActiveGold
            case "textOnDarkAccentB2BHover": return .textOnDarkAccentB2BHoverGold
            case "textOnDarkAccentDiscount": return .textOnDarkAccentDiscountGold
            case "textOnDarkAccentDiscountActive": return .textOnDarkAccentDiscountActiveGold
            case "textOnDarkAccentDiscountHover": return .textOnDarkAccentDiscountHoverGold
            case "textOnDarkAccentGold": return .textOnDarkAccentGoldGold
            case "textOnDarkAccentGoldActive": return .textOnDarkAccentGoldActiveGold
            case "textOnDarkAccentGoldHover": return .textOnDarkAccentGoldHoverGold
            case "textOnDarkAccentHover": return .textOnDarkAccentHoverGold
            case "textOnDarkAccentMinor": return .textOnDarkAccentMinorGold
            case "textOnDarkAccentMinorActive": return .textOnDarkAccentMinorActiveGold
            case "textOnDarkAccentMinorHover": return .textOnDarkAccentMinorHoverGold
            case "textOnDarkInfo": return .textOnDarkInfoGold
            case "textOnDarkInfoActive": return .textOnDarkInfoActiveGold
            case "textOnDarkInfoHover": return .textOnDarkInfoHoverGold
            case "textOnDarkInfoMinor": return .textOnDarkInfoMinorGold
            case "textOnDarkInfoMinorActive": return .textOnDarkInfoMinorActiveGold
            case "textOnDarkInfoMinorHover": return .textOnDarkInfoMinorHoverGold
            case "textOnDarkNegative": return .textOnDarkNegativeGold
            case "textOnDarkNegativeActive": return .textOnDarkNegativeActiveGold
            case "textOnDarkNegativeHover": return .textOnDarkNegativeHoverGold
            case "textOnDarkNegativeMinor": return .textOnDarkNegativeMinorGold
            case "textOnDarkNegativeMinorActive": return .textOnDarkNegativeMinorActiveGold
            case "textOnDarkNegativeMinorHover": return .textOnDarkNegativeMinorHoverGold
            case "textOnDarkParagraph": return .textOnDarkParagraphGold
            case "textOnDarkParagraphActive": return .textOnDarkParagraphActiveGold
            case "textOnDarkParagraphHover": return .textOnDarkParagraphHoverGold
            case "textOnDarkPositive": return .textOnDarkPositiveGold
            case "textOnDarkPositiveActive": return .textOnDarkPositiveActiveGold
            case "textOnDarkPositiveHover": return .textOnDarkPositiveHoverGold
            case "textOnDarkPositiveMinor": return .textOnDarkPositiveMinorGold
            case "textOnDarkPositiveMinorActive": return .textOnDarkPositiveMinorActiveGold
            case "textOnDarkPositiveMinorHover": return .textOnDarkPositiveMinorHoverGold
            case "textOnDarkPrimary": return .textOnDarkPrimaryGold
            case "textOnDarkPrimaryActive": return .textOnDarkPrimaryActiveGold
            case "textOnDarkPrimaryBrightness": return .textOnDarkPrimaryBrightnessGold
            case "textOnDarkPrimaryHover": return .textOnDarkPrimaryHoverGold
            case "textOnDarkPromo": return .textOnDarkPromoGold
            case "textOnDarkPromoActive": return .textOnDarkPromoActiveGold
            case "textOnDarkPromoHover": return .textOnDarkPromoHoverGold
            case "textOnDarkPromoMinor": return .textOnDarkPromoMinorGold
            case "textOnDarkPromoMinorActive": return .textOnDarkPromoMinorActiveGold
            case "textOnDarkPromoMinorHover": return .textOnDarkPromoMinorHoverGold
            case "textOnDarkSecondary": return .textOnDarkSecondaryGold
            case "textOnDarkSecondaryActive": return .textOnDarkSecondaryActiveGold
            case "textOnDarkSecondaryHover": return .textOnDarkSecondaryHoverGold
            case "textOnDarkTertiary": return .textOnDarkTertiaryGold
            case "textOnDarkTertiaryActive": return .textOnDarkTertiaryActiveGold
            case "textOnDarkTertiaryHover": return .textOnDarkTertiaryHoverGold
            case "textOnDarkWarning": return .textOnDarkWarningGold
            case "textOnDarkWarningActive": return .textOnDarkWarningActiveGold
            case "textOnDarkWarningHover": return .textOnDarkWarningHoverGold
            case "textOnDarkWarningMinor": return .textOnDarkWarningMinorGold
            case "textOnDarkWarningMinorActive": return .textOnDarkWarningMinorActiveGold
            case "textOnDarkWarningMinorHover": return .textOnDarkWarningMinorHoverGold
            case "textOnLightAccent": return .textOnLightAccentGold
            case "textOnLightAccentActive": return .textOnLightAccentActiveGold
            case "textOnLightAccentB2B": return .textOnLightAccentB2BGold
            case "textOnLightAccentB2BActive": return .textOnLightAccentB2BActiveGold
            case "textOnLightAccentB2BHover": return .textOnLightAccentB2BHoverGold
            case "textOnLightAccentDiscount": return .textOnLightAccentDiscountGold
            case "textOnLightAccentDiscountActive": return .textOnLightAccentDiscountActiveGold
            case "textOnLightAccentDiscountHover": return .textOnLightAccentDiscountHoverGold
            case "textOnLightAccentGold": return .textOnLightAccentGoldGold
            case "textOnLightAccentGoldActive": return .textOnLightAccentGoldActiveGold
            case "textOnLightAccentGoldHover": return .textOnLightAccentGoldHoverGold
            case "textOnLightAccentHover": return .textOnLightAccentHoverGold
            case "textOnLightAccentMinor": return .textOnLightAccentMinorGold
            case "textOnLightAccentMinorActive": return .textOnLightAccentMinorActiveGold
            case "textOnLightAccentMinorHover": return .textOnLightAccentMinorHoverGold
            case "textOnLightInfo": return .textOnLightInfoGold
            case "textOnLightInfoActive": return .textOnLightInfoActiveGold
            case "textOnLightInfoHover": return .textOnLightInfoHoverGold
            case "textOnLightInfoMinor": return .textOnLightInfoMinorGold
            case "textOnLightInfoMinorActive": return .textOnLightInfoMinorActiveGold
            case "textOnLightInfoMinorHover": return .textOnLightInfoMinorHoverGold
            case "textOnLightNegative": return .textOnLightNegativeGold
            case "textOnLightNegativeActive": return .textOnLightNegativeActiveGold
            case "textOnLightNegativeHover": return .textOnLightNegativeHoverGold
            case "textOnLightNegativeMinor": return .textOnLightNegativeMinorGold
            case "textOnLightNegativeMinorActive": return .textOnLightNegativeMinorActiveGold
            case "textOnLightNegativeMinorHover": return .textOnLightNegativeMinorHoverGold
            case "textOnLightParagraph": return .textOnLightParagraphGold
            case "textOnLightParagraphActive": return .textOnLightParagraphActiveGold
            case "textOnLightParagraphHover": return .textOnLightParagraphHoverGold
            case "textOnLightPositive": return .textOnLightPositiveGold
            case "textOnLightPositiveActive": return .textOnLightPositiveActiveGold
            case "textOnLightPositiveHover": return .textOnLightPositiveHoverGold
            case "textOnLightPositiveMinor": return .textOnLightPositiveMinorGold
            case "textOnLightPositiveMinorActive": return .textOnLightPositiveMinorActiveGold
            case "textOnLightPositiveMinorHover": return .textOnLightPositiveMinorHoverGold
            case "textOnLightPrimary": return .textOnLightPrimaryGold
            case "textOnLightPrimaryActive": return .textOnLightPrimaryActiveGold
            case "textOnLightPrimaryBrightness": return .textOnLightPrimaryBrightnessGold
            case "textOnLightPrimaryHover": return .textOnLightPrimaryHoverGold
            case "textOnLightPromo": return .textOnLightPromoGold
            case "textOnLightPromoActive": return .textOnLightPromoActiveGold
            case "textOnLightPromoHover": return .textOnLightPromoHoverGold
            case "textOnLightPromoMinor": return .textOnLightPromoMinorGold
            case "textOnLightPromoMinorActive": return .textOnLightPromoMinorActiveGold
            case "textOnLightPromoMinorHover": return .textOnLightPromoMinorHoverGold
            case "textOnLightSecondary": return .textOnLightSecondaryGold
            case "textOnLightSecondaryActive": return .textOnLightSecondaryActiveGold
            case "textOnLightSecondaryHover": return .textOnLightSecondaryHoverGold
            case "textOnLightTertiary": return .textOnLightTertiaryGold
            case "textOnLightTertiaryActive": return .textOnLightTertiaryActiveGold
            case "textOnLightTertiaryHover": return .textOnLightTertiaryHoverGold
            case "textOnLightWarning": return .textOnLightWarningGold
            case "textOnLightWarningActive": return .textOnLightWarningActiveGold
            case "textOnLightWarningHover": return .textOnLightWarningHoverGold
            case "textOnLightWarningMinor": return .textOnLightWarningMinorGold
            case "textOnLightWarningMinorActive": return .textOnLightWarningMinorActiveGold
            case "textOnLightWarningMinorHover": return .textOnLightWarningMinorHoverGold
            default: return nil
            }
        }
    }
}

