/* This file is code generated. */

import SwiftUI
import UIKit
@_exported import SDDSThemeCore


public extension Gradients {
    static func registerGold() {
        ThemeTenantRegistry.shared.registerGradients(theme: "SDDSServ", tenant: Tenant(name: "Gold")) { id in
            switch id {
            case "outlineDefaultAccentGradient": return .outlineDefaultAccentGradientGold
            case "outlineDefaultAccentGradientActive": return .outlineDefaultAccentGradientActiveGold
            case "outlineDefaultAccentGradientHover": return .outlineDefaultAccentGradientHoverGold
            case "outlineDefaultAccentMinorGradient": return .outlineDefaultAccentMinorGradientGold
            case "outlineDefaultAccentMinorGradientActive": return .outlineDefaultAccentMinorGradientActiveGold
            case "outlineDefaultAccentMinorGradientHover": return .outlineDefaultAccentMinorGradientHoverGold
            case "outlineDefaultPromoGradient": return .outlineDefaultPromoGradientGold
            case "outlineDefaultPromoGradientActive": return .outlineDefaultPromoGradientActiveGold
            case "outlineDefaultPromoGradientHover": return .outlineDefaultPromoGradientHoverGold
            case "outlineDefaultPromoMinorGradient": return .outlineDefaultPromoMinorGradientGold
            case "outlineDefaultPromoMinorGradientActive": return .outlineDefaultPromoMinorGradientActiveGold
            case "outlineDefaultPromoMinorGradientHover": return .outlineDefaultPromoMinorGradientHoverGold
            case "outlineDefaultTransparentAccentGradient": return .outlineDefaultTransparentAccentGradientGold
            case "outlineDefaultTransparentAccentGradientActive": return .outlineDefaultTransparentAccentGradientActiveGold
            case "outlineDefaultTransparentAccentGradientHover": return .outlineDefaultTransparentAccentGradientHoverGold
            case "outlineInverseAccentGradient": return .outlineInverseAccentGradientGold
            case "outlineInverseAccentGradientActive": return .outlineInverseAccentGradientActiveGold
            case "outlineInverseAccentGradientHover": return .outlineInverseAccentGradientHoverGold
            case "outlineInverseAccentMinorGradient": return .outlineInverseAccentMinorGradientGold
            case "outlineInverseAccentMinorGradientActive": return .outlineInverseAccentMinorGradientActiveGold
            case "outlineInverseAccentMinorGradientHover": return .outlineInverseAccentMinorGradientHoverGold
            case "outlineInversePromoGradient": return .outlineInversePromoGradientGold
            case "outlineInversePromoGradientActive": return .outlineInversePromoGradientActiveGold
            case "outlineInversePromoGradientHover": return .outlineInversePromoGradientHoverGold
            case "outlineInversePromoMinorGradient": return .outlineInversePromoMinorGradientGold
            case "outlineInversePromoMinorGradientActive": return .outlineInversePromoMinorGradientActiveGold
            case "outlineInversePromoMinorGradientHover": return .outlineInversePromoMinorGradientHoverGold
            case "outlineInverseTransparentAccentGradient": return .outlineInverseTransparentAccentGradientGold
            case "outlineInverseTransparentAccentGradientActive": return .outlineInverseTransparentAccentGradientActiveGold
            case "outlineInverseTransparentAccentGradientHover": return .outlineInverseTransparentAccentGradientHoverGold
            case "outlineOnDarkAccentGradient": return .outlineOnDarkAccentGradientGold
            case "outlineOnDarkAccentGradientActive": return .outlineOnDarkAccentGradientActiveGold
            case "outlineOnDarkAccentGradientHover": return .outlineOnDarkAccentGradientHoverGold
            case "outlineOnDarkAccentMinorGradient": return .outlineOnDarkAccentMinorGradientGold
            case "outlineOnDarkAccentMinorGradientActive": return .outlineOnDarkAccentMinorGradientActiveGold
            case "outlineOnDarkAccentMinorGradientHover": return .outlineOnDarkAccentMinorGradientHoverGold
            case "outlineOnDarkPromoGradient": return .outlineOnDarkPromoGradientGold
            case "outlineOnDarkPromoGradientActive": return .outlineOnDarkPromoGradientActiveGold
            case "outlineOnDarkPromoGradientHover": return .outlineOnDarkPromoGradientHoverGold
            case "outlineOnDarkPromoMinorGradient": return .outlineOnDarkPromoMinorGradientGold
            case "outlineOnDarkPromoMinorGradientActive": return .outlineOnDarkPromoMinorGradientActiveGold
            case "outlineOnDarkPromoMinorGradientHover": return .outlineOnDarkPromoMinorGradientHoverGold
            case "outlineOnDarkTransparentAccentGradient": return .outlineOnDarkTransparentAccentGradientGold
            case "outlineOnDarkTransparentAccentGradientActive": return .outlineOnDarkTransparentAccentGradientActiveGold
            case "outlineOnDarkTransparentAccentGradientHover": return .outlineOnDarkTransparentAccentGradientHoverGold
            case "outlineOnLightAccentGradient": return .outlineOnLightAccentGradientGold
            case "outlineOnLightAccentGradientActive": return .outlineOnLightAccentGradientActiveGold
            case "outlineOnLightAccentGradientHover": return .outlineOnLightAccentGradientHoverGold
            case "outlineOnLightAccentMinorGradient": return .outlineOnLightAccentMinorGradientGold
            case "outlineOnLightAccentMinorGradientActive": return .outlineOnLightAccentMinorGradientActiveGold
            case "outlineOnLightAccentMinorGradientHover": return .outlineOnLightAccentMinorGradientHoverGold
            case "outlineOnLightPromoGradient": return .outlineOnLightPromoGradientGold
            case "outlineOnLightPromoGradientActive": return .outlineOnLightPromoGradientActiveGold
            case "outlineOnLightPromoGradientHover": return .outlineOnLightPromoGradientHoverGold
            case "outlineOnLightPromoMinorGradient": return .outlineOnLightPromoMinorGradientGold
            case "outlineOnLightPromoMinorGradientActive": return .outlineOnLightPromoMinorGradientActiveGold
            case "outlineOnLightPromoMinorGradientHover": return .outlineOnLightPromoMinorGradientHoverGold
            case "outlineOnLightTransparentAccentGradient": return .outlineOnLightTransparentAccentGradientGold
            case "outlineOnLightTransparentAccentGradientActive": return .outlineOnLightTransparentAccentGradientActiveGold
            case "outlineOnLightTransparentAccentGradientHover": return .outlineOnLightTransparentAccentGradientHoverGold
            case "surfaceDefaultAccentGradient": return .surfaceDefaultAccentGradientGold
            case "surfaceDefaultAccentGradientActive": return .surfaceDefaultAccentGradientActiveGold
            case "surfaceDefaultAccentGradientHover": return .surfaceDefaultAccentGradientHoverGold
            case "surfaceDefaultAccentMinorGradient": return .surfaceDefaultAccentMinorGradientGold
            case "surfaceDefaultAccentMinorGradientActive": return .surfaceDefaultAccentMinorGradientActiveGold
            case "surfaceDefaultAccentMinorGradientHover": return .surfaceDefaultAccentMinorGradientHoverGold
            case "surfaceDefaultPromoGradient": return .surfaceDefaultPromoGradientGold
            case "surfaceDefaultPromoGradientActive": return .surfaceDefaultPromoGradientActiveGold
            case "surfaceDefaultPromoGradientHover": return .surfaceDefaultPromoGradientHoverGold
            case "surfaceDefaultPromoMinorGradient": return .surfaceDefaultPromoMinorGradientGold
            case "surfaceDefaultPromoMinorGradientActive": return .surfaceDefaultPromoMinorGradientActiveGold
            case "surfaceDefaultPromoMinorGradientHover": return .surfaceDefaultPromoMinorGradientHoverGold
            case "surfaceDefaultSkeletonDeepGradient": return .surfaceDefaultSkeletonDeepGradientGold
            case "surfaceDefaultSkeletonDeepGradientActive": return .surfaceDefaultSkeletonDeepGradientActiveGold
            case "surfaceDefaultSkeletonDeepGradientHover": return .surfaceDefaultSkeletonDeepGradientHoverGold
            case "surfaceDefaultSkeletonGradient": return .surfaceDefaultSkeletonGradientGold
            case "surfaceDefaultSkeletonGradientActive": return .surfaceDefaultSkeletonGradientActiveGold
            case "surfaceDefaultSkeletonGradientHover": return .surfaceDefaultSkeletonGradientHoverGold
            case "surfaceDefaultTransparentAccentGradient": return .surfaceDefaultTransparentAccentGradientGold
            case "surfaceDefaultTransparentAccentGradientActive": return .surfaceDefaultTransparentAccentGradientActiveGold
            case "surfaceDefaultTransparentAccentGradientHover": return .surfaceDefaultTransparentAccentGradientHoverGold
            case "surfaceDefaultTransparentPromoGradient": return .surfaceDefaultTransparentPromoGradientGold
            case "surfaceDefaultTransparentPromoGradientActive": return .surfaceDefaultTransparentPromoGradientActiveGold
            case "surfaceDefaultTransparentPromoGradientHover": return .surfaceDefaultTransparentPromoGradientHoverGold
            case "surfaceInverseAccentGradient": return .surfaceInverseAccentGradientGold
            case "surfaceInverseAccentGradientActive": return .surfaceInverseAccentGradientActiveGold
            case "surfaceInverseAccentGradientHover": return .surfaceInverseAccentGradientHoverGold
            case "surfaceInverseAccentMinorGradient": return .surfaceInverseAccentMinorGradientGold
            case "surfaceInverseAccentMinorGradientActive": return .surfaceInverseAccentMinorGradientActiveGold
            case "surfaceInverseAccentMinorGradientHover": return .surfaceInverseAccentMinorGradientHoverGold
            case "surfaceInversePromoGradient": return .surfaceInversePromoGradientGold
            case "surfaceInversePromoGradientActive": return .surfaceInversePromoGradientActiveGold
            case "surfaceInversePromoGradientHover": return .surfaceInversePromoGradientHoverGold
            case "surfaceInversePromoMinorGradient": return .surfaceInversePromoMinorGradientGold
            case "surfaceInversePromoMinorGradientActive": return .surfaceInversePromoMinorGradientActiveGold
            case "surfaceInversePromoMinorGradientHover": return .surfaceInversePromoMinorGradientHoverGold
            case "surfaceInverseSkeletonDeepGradient": return .surfaceInverseSkeletonDeepGradientGold
            case "surfaceInverseSkeletonDeepGradientActive": return .surfaceInverseSkeletonDeepGradientActiveGold
            case "surfaceInverseSkeletonDeepGradientHover": return .surfaceInverseSkeletonDeepGradientHoverGold
            case "surfaceInverseSkeletonGradient": return .surfaceInverseSkeletonGradientGold
            case "surfaceInverseSkeletonGradientActive": return .surfaceInverseSkeletonGradientActiveGold
            case "surfaceInverseSkeletonGradientHover": return .surfaceInverseSkeletonGradientHoverGold
            case "surfaceInverseTransparentAccentGradient": return .surfaceInverseTransparentAccentGradientGold
            case "surfaceInverseTransparentAccentGradientActive": return .surfaceInverseTransparentAccentGradientActiveGold
            case "surfaceInverseTransparentAccentGradientHover": return .surfaceInverseTransparentAccentGradientHoverGold
            case "surfaceInverseTransparentPromoGradient": return .surfaceInverseTransparentPromoGradientGold
            case "surfaceInverseTransparentPromoGradientActive": return .surfaceInverseTransparentPromoGradientActiveGold
            case "surfaceInverseTransparentPromoGradientHover": return .surfaceInverseTransparentPromoGradientHoverGold
            case "surfaceOnDarkAccentGradient": return .surfaceOnDarkAccentGradientGold
            case "surfaceOnDarkAccentGradientActive": return .surfaceOnDarkAccentGradientActiveGold
            case "surfaceOnDarkAccentGradientHover": return .surfaceOnDarkAccentGradientHoverGold
            case "surfaceOnDarkAccentMinorGradient": return .surfaceOnDarkAccentMinorGradientGold
            case "surfaceOnDarkAccentMinorGradientActive": return .surfaceOnDarkAccentMinorGradientActiveGold
            case "surfaceOnDarkAccentMinorGradientHover": return .surfaceOnDarkAccentMinorGradientHoverGold
            case "surfaceOnDarkPromoGradient": return .surfaceOnDarkPromoGradientGold
            case "surfaceOnDarkPromoGradientActive": return .surfaceOnDarkPromoGradientActiveGold
            case "surfaceOnDarkPromoGradientHover": return .surfaceOnDarkPromoGradientHoverGold
            case "surfaceOnDarkPromoMinorGradient": return .surfaceOnDarkPromoMinorGradientGold
            case "surfaceOnDarkPromoMinorGradientActive": return .surfaceOnDarkPromoMinorGradientActiveGold
            case "surfaceOnDarkPromoMinorGradientHover": return .surfaceOnDarkPromoMinorGradientHoverGold
            case "surfaceOnDarkSkeletonDeepGradient": return .surfaceOnDarkSkeletonDeepGradientGold
            case "surfaceOnDarkSkeletonDeepGradientActive": return .surfaceOnDarkSkeletonDeepGradientActiveGold
            case "surfaceOnDarkSkeletonDeepGradientHover": return .surfaceOnDarkSkeletonDeepGradientHoverGold
            case "surfaceOnDarkSkeletonGradient": return .surfaceOnDarkSkeletonGradientGold
            case "surfaceOnDarkSkeletonGradientActive": return .surfaceOnDarkSkeletonGradientActiveGold
            case "surfaceOnDarkSkeletonGradientHover": return .surfaceOnDarkSkeletonGradientHoverGold
            case "surfaceOnDarkTransparentAccentGradient": return .surfaceOnDarkTransparentAccentGradientGold
            case "surfaceOnDarkTransparentAccentGradientActive": return .surfaceOnDarkTransparentAccentGradientActiveGold
            case "surfaceOnDarkTransparentAccentGradientHover": return .surfaceOnDarkTransparentAccentGradientHoverGold
            case "surfaceOnDarkTransparentPromoGradient": return .surfaceOnDarkTransparentPromoGradientGold
            case "surfaceOnDarkTransparentPromoGradientActive": return .surfaceOnDarkTransparentPromoGradientActiveGold
            case "surfaceOnDarkTransparentPromoGradientHover": return .surfaceOnDarkTransparentPromoGradientHoverGold
            case "surfaceOnLightAccentGradient": return .surfaceOnLightAccentGradientGold
            case "surfaceOnLightAccentGradientActive": return .surfaceOnLightAccentGradientActiveGold
            case "surfaceOnLightAccentGradientHover": return .surfaceOnLightAccentGradientHoverGold
            case "surfaceOnLightAccentMinorGradient": return .surfaceOnLightAccentMinorGradientGold
            case "surfaceOnLightAccentMinorGradientActive": return .surfaceOnLightAccentMinorGradientActiveGold
            case "surfaceOnLightAccentMinorGradientHover": return .surfaceOnLightAccentMinorGradientHoverGold
            case "surfaceOnLightPromoGradient": return .surfaceOnLightPromoGradientGold
            case "surfaceOnLightPromoGradientActive": return .surfaceOnLightPromoGradientActiveGold
            case "surfaceOnLightPromoGradientHover": return .surfaceOnLightPromoGradientHoverGold
            case "surfaceOnLightPromoMinorGradient": return .surfaceOnLightPromoMinorGradientGold
            case "surfaceOnLightPromoMinorGradientActive": return .surfaceOnLightPromoMinorGradientActiveGold
            case "surfaceOnLightPromoMinorGradientHover": return .surfaceOnLightPromoMinorGradientHoverGold
            case "surfaceOnLightSkeletonDeepGradient": return .surfaceOnLightSkeletonDeepGradientGold
            case "surfaceOnLightSkeletonDeepGradientActive": return .surfaceOnLightSkeletonDeepGradientActiveGold
            case "surfaceOnLightSkeletonDeepGradientHover": return .surfaceOnLightSkeletonDeepGradientHoverGold
            case "surfaceOnLightSkeletonGradient": return .surfaceOnLightSkeletonGradientGold
            case "surfaceOnLightSkeletonGradientActive": return .surfaceOnLightSkeletonGradientActiveGold
            case "surfaceOnLightSkeletonGradientHover": return .surfaceOnLightSkeletonGradientHoverGold
            case "surfaceOnLightTransparentAccentGradient": return .surfaceOnLightTransparentAccentGradientGold
            case "surfaceOnLightTransparentAccentGradientActive": return .surfaceOnLightTransparentAccentGradientActiveGold
            case "surfaceOnLightTransparentAccentGradientHover": return .surfaceOnLightTransparentAccentGradientHoverGold
            case "surfaceOnLightTransparentPromoGradient": return .surfaceOnLightTransparentPromoGradientGold
            case "surfaceOnLightTransparentPromoGradientActive": return .surfaceOnLightTransparentPromoGradientActiveGold
            case "surfaceOnLightTransparentPromoGradientHover": return .surfaceOnLightTransparentPromoGradientHoverGold
            case "textDefaultAccentGradient": return .textDefaultAccentGradientGold
            case "textDefaultAccentGradientActive": return .textDefaultAccentGradientActiveGold
            case "textDefaultAccentGradientHover": return .textDefaultAccentGradientHoverGold
            case "textDefaultAccentMinorGradient": return .textDefaultAccentMinorGradientGold
            case "textDefaultAccentMinorGradientActive": return .textDefaultAccentMinorGradientActiveGold
            case "textDefaultAccentMinorGradientHover": return .textDefaultAccentMinorGradientHoverGold
            case "textDefaultPromoGradient": return .textDefaultPromoGradientGold
            case "textDefaultPromoGradientActive": return .textDefaultPromoGradientActiveGold
            case "textDefaultPromoGradientHover": return .textDefaultPromoGradientHoverGold
            case "textDefaultPromoMinorGradient": return .textDefaultPromoMinorGradientGold
            case "textDefaultPromoMinorGradientActive": return .textDefaultPromoMinorGradientActiveGold
            case "textDefaultPromoMinorGradientHover": return .textDefaultPromoMinorGradientHoverGold
            case "textInverseAccentGradient": return .textInverseAccentGradientGold
            case "textInverseAccentGradientActive": return .textInverseAccentGradientActiveGold
            case "textInverseAccentGradientHover": return .textInverseAccentGradientHoverGold
            case "textInverseAccentMinorGradient": return .textInverseAccentMinorGradientGold
            case "textInverseAccentMinorGradientActive": return .textInverseAccentMinorGradientActiveGold
            case "textInverseAccentMinorGradientHover": return .textInverseAccentMinorGradientHoverGold
            case "textInversePromoGradient": return .textInversePromoGradientGold
            case "textInversePromoGradientActive": return .textInversePromoGradientActiveGold
            case "textInversePromoGradientHover": return .textInversePromoGradientHoverGold
            case "textInversePromoMinorGradient": return .textInversePromoMinorGradientGold
            case "textInversePromoMinorGradientActive": return .textInversePromoMinorGradientActiveGold
            case "textInversePromoMinorGradientHover": return .textInversePromoMinorGradientHoverGold
            case "textOnDarkAccentGradient": return .textOnDarkAccentGradientGold
            case "textOnDarkAccentGradientActive": return .textOnDarkAccentGradientActiveGold
            case "textOnDarkAccentGradientHover": return .textOnDarkAccentGradientHoverGold
            case "textOnDarkAccentMinorGradient": return .textOnDarkAccentMinorGradientGold
            case "textOnDarkAccentMinorGradientActive": return .textOnDarkAccentMinorGradientActiveGold
            case "textOnDarkAccentMinorGradientHover": return .textOnDarkAccentMinorGradientHoverGold
            case "textOnDarkPromoGradient": return .textOnDarkPromoGradientGold
            case "textOnDarkPromoGradientActive": return .textOnDarkPromoGradientActiveGold
            case "textOnDarkPromoGradientHover": return .textOnDarkPromoGradientHoverGold
            case "textOnDarkPromoMinorGradient": return .textOnDarkPromoMinorGradientGold
            case "textOnDarkPromoMinorGradientActive": return .textOnDarkPromoMinorGradientActiveGold
            case "textOnDarkPromoMinorGradientHover": return .textOnDarkPromoMinorGradientHoverGold
            case "textOnLightAccentGradient": return .textOnLightAccentGradientGold
            case "textOnLightAccentGradientActive": return .textOnLightAccentGradientActiveGold
            case "textOnLightAccentGradientHover": return .textOnLightAccentGradientHoverGold
            case "textOnLightAccentMinorGradient": return .textOnLightAccentMinorGradientGold
            case "textOnLightAccentMinorGradientActive": return .textOnLightAccentMinorGradientActiveGold
            case "textOnLightAccentMinorGradientHover": return .textOnLightAccentMinorGradientHoverGold
            case "textOnLightPromoGradient": return .textOnLightPromoGradientGold
            case "textOnLightPromoGradientActive": return .textOnLightPromoGradientActiveGold
            case "textOnLightPromoGradientHover": return .textOnLightPromoGradientHoverGold
            case "textOnLightPromoMinorGradient": return .textOnLightPromoMinorGradientGold
            case "textOnLightPromoMinorGradientActive": return .textOnLightPromoMinorGradientActiveGold
            case "textOnLightPromoMinorGradientHover": return .textOnLightPromoMinorGradientHoverGold
            default: return nil
            }
        }
    }
}

