import Foundation

/// Генерирует Swift-реестр сэмплов внутри модуля фикстур: сэмплы объявлены
/// internal, поэтому перечислить их из тестов можно только через
/// сгенерированный файл в том же модуле.
public enum RegistryGenerator {

    /// `records` — итог скана (core-слой); в реестр попадают только `view`-сэмплы.
    public static func source(records: [SampleRecord]) -> String {
        var out = """
        // Generated by dsbuilder docs extract --emit-registry. Do not edit.
        // Реестр `// @DocSample`-сэмплов для скриншот-тестов документации.
        import SwiftUI

        public enum DocSamples {
            public struct Entry {
                public let id: String
                public let fqName: String
                public let needScreenshot: Bool
                public let makeView: () -> AnyView

                public init(id: String, fqName: String, needScreenshot: Bool, makeView: @escaping () -> AnyView) {
                    self.id = id
                    self.fqName = fqName
                    self.needScreenshot = needScreenshot
                    self.makeView = makeView
                }
            }

            public static let all: [Entry] = [

        """
        for record in records where record.kind == "view" {
            // Имя структуры — последний сегмент fqName (id может быть переопределён
            // через `id=` и не совпадать с именем типа).
            let typeName = record.fqName.split(separator: ".").last.map(String.init) ?? record.id
            out += """
                    Entry(
                        id: "\(record.id)",
                        fqName: "\(record.fqName)",
                        needScreenshot: \(record.needScreenshot),
                        makeView: { AnyView(\(typeName)()) }
                    ),

            """
        }
        out += """
            ]
        }

        """
        return out
    }
}
