#!/usr/bin/env python3
"""
Generate sandbox story registrations for SDDSDemoApp.

Scans `Views/**/**/*SandboxStory.swift` for `enum <Name>Story: Story`
and emits a generated file used by `GeneratedStoriesRegistration`.
"""

from __future__ import annotations

import re
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
VIEWS_DIR = ROOT / "SDDSDemoApp" / "SDDSDemoApp" / "Views"
OUT_FILE = (
    ROOT
    / "SDDSDemoApp"
    / "SDDSDemoApp"
    / "Common"
    / "Sandbox"
    / "GeneratedStories+Autogen.swift"
)

STORY_PATTERN = re.compile(r"\benum\s+([A-Za-z_][A-Za-z0-9_]*)\s*:\s*Story\b")


def collect_story_types() -> list[str]:
    story_types: list[str] = []
    for path in sorted(VIEWS_DIR.rglob("*SandboxStory.swift")):
        text = path.read_text(encoding="utf-8")
        matches = STORY_PATTERN.findall(text)
        story_types.extend(matches)
    return sorted(set(story_types))


def build_output(story_types: list[str]) -> str:
    lines: list[str] = []
    lines.append("// This file is auto-generated by scripts/generate_sandbox_stories.py.")
    lines.append("// Do not edit manually.")
    lines.append("")
    lines.append("import SandboxCore")
    lines.append("import SwiftUI")
    lines.append("")
    lines.append("enum GeneratedStoriesAutogen {")
    lines.append("    static func registerAll() {")
    for story_type in story_types:
        lines.append(f"        StoryRegistry.shared.register({story_type}.self)")
        lines.append(
            f"        SandboxStoryRenderRegistry.shared.register(id: {story_type}.id) {{ theme in"
        )
        lines.append(
            f"            AnyView({story_type}.content(state: {story_type}.defaultState, theme: theme))"
        )
        lines.append("        }")
    lines.append("    }")
    lines.append("}")
    lines.append("")
    return "\n".join(lines)


def main() -> None:
    story_types = collect_story_types()
    OUT_FILE.write_text(build_output(story_types), encoding="utf-8")
    print(f"Generated {OUT_FILE} with {len(story_types)} stories.")


if __name__ == "__main__":
    main()
