/* This file is code generated. */

import Foundation
@_exported import SDDSThemeCore

public enum Typographies {
    case bodyLBold
    case bodyLMedium
    case bodyLNormal
    case bodyMBold
    case bodyMMedium
    case bodyMNormal
    case bodySBold
    case bodySMedium
    case bodySNormal
    case bodyXsBold
    case bodyXsMedium
    case bodyXsNormal
    case bodyXxsBold
    case bodyXxsMedium
    case bodyXxsNormal
    case displayLBold
    case displayLMedium
    case displayLNormal
    case displayMBold
    case displayMMedium
    case displayMNormal
    case displaySBold
    case displaySMedium
    case displaySNormal
    case headerH1Bold
    case headerH1Medium
    case headerH1Normal
    case headerH2Bold
    case headerH2Medium
    case headerH2Normal
    case headerH3Bold
    case headerH3Medium
    case headerH3Normal
    case headerH4Bold
    case headerH4Medium
    case headerH4Normal
    case headerH5Bold
    case headerH5Medium
    case headerH5Normal
    case textLBold
    case textLMedium
    case textLNormal
    case textMBold
    case textMMedium
    case textMNormal
    case textSBold
    case textSMedium
    case textSNormal
    case textXsBold
    case textXsMedium
    case textXsNormal

    public var token: AdaptiveTypographyToken {
        switch self {
        case .bodyLBold:
            return .bodyLBold
        case .bodyLMedium:
            return .bodyLMedium
        case .bodyLNormal:
            return .bodyLNormal
        case .bodyMBold:
            return .bodyMBold
        case .bodyMMedium:
            return .bodyMMedium
        case .bodyMNormal:
            return .bodyMNormal
        case .bodySBold:
            return .bodySBold
        case .bodySMedium:
            return .bodySMedium
        case .bodySNormal:
            return .bodySNormal
        case .bodyXsBold:
            return .bodyXsBold
        case .bodyXsMedium:
            return .bodyXsMedium
        case .bodyXsNormal:
            return .bodyXsNormal
        case .bodyXxsBold:
            return .bodyXxsBold
        case .bodyXxsMedium:
            return .bodyXxsMedium
        case .bodyXxsNormal:
            return .bodyXxsNormal
        case .displayLBold:
            return .displayLBold
        case .displayLMedium:
            return .displayLMedium
        case .displayLNormal:
            return .displayLNormal
        case .displayMBold:
            return .displayMBold
        case .displayMMedium:
            return .displayMMedium
        case .displayMNormal:
            return .displayMNormal
        case .displaySBold:
            return .displaySBold
        case .displaySMedium:
            return .displaySMedium
        case .displaySNormal:
            return .displaySNormal
        case .headerH1Bold:
            return .headerH1Bold
        case .headerH1Medium:
            return .headerH1Medium
        case .headerH1Normal:
            return .headerH1Normal
        case .headerH2Bold:
            return .headerH2Bold
        case .headerH2Medium:
            return .headerH2Medium
        case .headerH2Normal:
            return .headerH2Normal
        case .headerH3Bold:
            return .headerH3Bold
        case .headerH3Medium:
            return .headerH3Medium
        case .headerH3Normal:
            return .headerH3Normal
        case .headerH4Bold:
            return .headerH4Bold
        case .headerH4Medium:
            return .headerH4Medium
        case .headerH4Normal:
            return .headerH4Normal
        case .headerH5Bold:
            return .headerH5Bold
        case .headerH5Medium:
            return .headerH5Medium
        case .headerH5Normal:
            return .headerH5Normal
        case .textLBold:
            return .textLBold
        case .textLMedium:
            return .textLMedium
        case .textLNormal:
            return .textLNormal
        case .textMBold:
            return .textMBold
        case .textMMedium:
            return .textMMedium
        case .textMNormal:
            return .textMNormal
        case .textSBold:
            return .textSBold
        case .textSMedium:
            return .textSMedium
        case .textSNormal:
            return .textSNormal
        case .textXsBold:
            return .textXsBold
        case .textXsMedium:
            return .textXsMedium
        case .textXsNormal:
            return .textXsNormal
        }
    }
}
