import Foundation

public extension TextAreaAppearance {
    func size(_ size: TextAreaSizeConfiguration) -> TextAreaAppearance {
        return TextAreaAppearance(
            size: size,
            backgroundColor: self.backgroundColor,
            backgroundColorReadOnly: self.backgroundColorReadOnly,
            borderColor: self.borderColor,
            captionColor: self.captionColor,
            captionColorFocused: self.captionColorFocused,
            captionColorReadOnly: self.captionColorReadOnly,
            captionTypography: self.captionTypography,
            counterColor: self.counterColor,
            counterColorReadOnly: self.counterColorReadOnly,
            counterTypography: self.counterTypography,
            cursorColor: self.cursorColor,
            disabledAlpha: self.disabledAlpha,
            endContentColor: self.endContentColor,
            backgroundColorFocused: self.backgroundColorFocused,
            innerTitleTextAlignment: self.innerTitleTextAlignment,
            innerTitleTypography: self.innerTitleTypography,
            inputTextAlignment: self.inputTextAlignment,
            lineColor: self.lineColor,
            lineColorFocused: self.lineColorFocused,
            optionalTitleColor: self.optionalTitleColor,
            placeholderColor: self.placeholderColor,
            placeholderColorFocused: self.placeholderColorFocused,
            placeholderColorReadOnly: self.placeholderColorReadOnly,
            requiredIndicatorColor: self.requiredIndicatorColor,
            startContentColor: self.startContentColor,
            textAfterColor: self.textAfterColor,
            textBeforeColor: self.textBeforeColor,
            textColor: self.textColor,
            textColorFocused: self.textColorFocused,
            textColorReadOnly: self.textColorReadOnly,
            textTypography: self.textTypography,
            titleColor: self.titleColor,
            titleTextAlignment: self.titleTextAlignment,
            titleTypography: self.titleTypography
        )
    }

    func captionTypography(_ captionTypography: TypographyConfiguration) -> TextAreaAppearance {
        return TextAreaAppearance(
            size: self.size,
            backgroundColor: self.backgroundColor,
            backgroundColorReadOnly: self.backgroundColorReadOnly,
            borderColor: self.borderColor,
            captionColor: self.captionColor,
            captionColorFocused: self.captionColorFocused,
            captionColorReadOnly: self.captionColorReadOnly,
            captionTypography: captionTypography,
            counterColor: self.counterColor,
            counterColorReadOnly: self.counterColorReadOnly,
            counterTypography: self.counterTypography,
            cursorColor: self.cursorColor,
            disabledAlpha: self.disabledAlpha,
            endContentColor: self.endContentColor,
            backgroundColorFocused: self.backgroundColorFocused,
            innerTitleTextAlignment: self.innerTitleTextAlignment,
            innerTitleTypography: self.innerTitleTypography,
            inputTextAlignment: self.inputTextAlignment,
            lineColor: self.lineColor,
            lineColorFocused: self.lineColorFocused,
            optionalTitleColor: self.optionalTitleColor,
            placeholderColor: self.placeholderColor,
            placeholderColorFocused: self.placeholderColorFocused,
            placeholderColorReadOnly: self.placeholderColorReadOnly,
            requiredIndicatorColor: self.requiredIndicatorColor,
            startContentColor: self.startContentColor,
            textAfterColor: self.textAfterColor,
            textBeforeColor: self.textBeforeColor,
            textColor: self.textColor,
            textColorFocused: self.textColorFocused,
            textColorReadOnly: self.textColorReadOnly,
            textTypography: self.textTypography,
            titleColor: self.titleColor,
            titleTextAlignment: self.titleTextAlignment,
            titleTypography: self.titleTypography
        )
    }

    func counterTypography(_ counterTypography: TypographyConfiguration) -> TextAreaAppearance {
        return TextAreaAppearance(
            size: self.size,
            backgroundColor: self.backgroundColor,
            backgroundColorReadOnly: self.backgroundColorReadOnly,
            borderColor: self.borderColor,
            captionColor: self.captionColor,
            captionColorFocused: self.captionColorFocused,
            captionColorReadOnly: self.captionColorReadOnly,
            captionTypography: self.captionTypography,
            counterColor: self.counterColor,
            counterColorReadOnly: self.counterColorReadOnly,
            counterTypography: counterTypography,
            cursorColor: self.cursorColor,
            disabledAlpha: self.disabledAlpha,
            endContentColor: self.endContentColor,
            backgroundColorFocused: self.backgroundColorFocused,
            innerTitleTextAlignment: self.innerTitleTextAlignment,
            innerTitleTypography: self.innerTitleTypography,
            inputTextAlignment: self.inputTextAlignment,
            lineColor: self.lineColor,
            lineColorFocused: self.lineColorFocused,
            optionalTitleColor: self.optionalTitleColor,
            placeholderColor: self.placeholderColor,
            placeholderColorFocused: self.placeholderColorFocused,
            placeholderColorReadOnly: self.placeholderColorReadOnly,
            requiredIndicatorColor: self.requiredIndicatorColor,
            startContentColor: self.startContentColor,
            textAfterColor: self.textAfterColor,
            textBeforeColor: self.textBeforeColor,
            textColor: self.textColor,
            textColorFocused: self.textColorFocused,
            textColorReadOnly: self.textColorReadOnly,
            textTypography: self.textTypography,
            titleColor: self.titleColor,
            titleTextAlignment: self.titleTextAlignment,
            titleTypography: self.titleTypography
        )
    }

    func textTypography(_ textTypography: TypographyConfiguration) -> TextAreaAppearance {
        return TextAreaAppearance(
            size: self.size,
            backgroundColor: self.backgroundColor,
            backgroundColorReadOnly: self.backgroundColorReadOnly,
            borderColor: self.borderColor,
            captionColor: self.captionColor,
            captionColorFocused: self.captionColorFocused,
            captionColorReadOnly: self.captionColorReadOnly,
            captionTypography: self.captionTypography,
            counterColor: self.counterColor,
            counterColorReadOnly: self.counterColorReadOnly,
            counterTypography: self.counterTypography,
            cursorColor: self.cursorColor,
            disabledAlpha: self.disabledAlpha,
            endContentColor: self.endContentColor,
            backgroundColorFocused: self.backgroundColorFocused,
            innerTitleTextAlignment: self.innerTitleTextAlignment,
            innerTitleTypography: self.innerTitleTypography,
            inputTextAlignment: self.inputTextAlignment,
            lineColor: self.lineColor,
            lineColorFocused: self.lineColorFocused,
            optionalTitleColor: self.optionalTitleColor,
            placeholderColor: self.placeholderColor,
            placeholderColorFocused: self.placeholderColorFocused,
            placeholderColorReadOnly: self.placeholderColorReadOnly,
            requiredIndicatorColor: self.requiredIndicatorColor,
            startContentColor: self.startContentColor,
            textAfterColor: self.textAfterColor,
            textBeforeColor: self.textBeforeColor,
            textColor: self.textColor,
            textColorFocused: self.textColorFocused,
            textColorReadOnly: self.textColorReadOnly,
            textTypography: textTypography,
            titleColor: self.titleColor,
            titleTextAlignment: self.titleTextAlignment,
            titleTypography: self.titleTypography
        )
    }

    func innerTitleTypography(_ innerTitleTypography: TypographyConfiguration) -> TextAreaAppearance {
        return TextAreaAppearance(
            size: self.size,
            backgroundColor: self.backgroundColor,
            backgroundColorReadOnly: self.backgroundColorReadOnly,
            borderColor: self.borderColor,
            captionColor: self.captionColor,
            captionColorFocused: self.captionColorFocused,
            captionColorReadOnly: self.captionColorReadOnly,
            captionTypography: self.captionTypography,
            counterColor: self.counterColor,
            counterColorReadOnly: self.counterColorReadOnly,
            counterTypography: self.counterTypography,
            cursorColor: self.cursorColor,
            disabledAlpha: self.disabledAlpha,
            endContentColor: self.endContentColor,
            backgroundColorFocused: self.backgroundColorFocused,
            innerTitleTextAlignment: self.innerTitleTextAlignment,
            innerTitleTypography: innerTitleTypography,
            inputTextAlignment: self.inputTextAlignment,
            lineColor: self.lineColor,
            lineColorFocused: self.lineColorFocused,
            optionalTitleColor: self.optionalTitleColor,
            placeholderColor: self.placeholderColor,
            placeholderColorFocused: self.placeholderColorFocused,
            placeholderColorReadOnly: self.placeholderColorReadOnly,
            requiredIndicatorColor: self.requiredIndicatorColor,
            startContentColor: self.startContentColor,
            textAfterColor: self.textAfterColor,
            textBeforeColor: self.textBeforeColor,
            textColor: self.textColor,
            textColorFocused: self.textColorFocused,
            textColorReadOnly: self.textColorReadOnly,
            textTypography: self.textTypography,
            titleColor: self.titleColor,
            titleTextAlignment: self.titleTextAlignment,
            titleTypography: self.titleTypography
        )
    }

    func titleTypography(_ titleTypography: TypographyConfiguration) -> TextAreaAppearance {
        return TextAreaAppearance(
            size: self.size,
            backgroundColor: self.backgroundColor,
            backgroundColorReadOnly: self.backgroundColorReadOnly,
            borderColor: self.borderColor,
            captionColor: self.captionColor,
            captionColorFocused: self.captionColorFocused,
            captionColorReadOnly: self.captionColorReadOnly,
            captionTypography: self.captionTypography,
            counterColor: self.counterColor,
            counterColorReadOnly: self.counterColorReadOnly,
            counterTypography: self.counterTypography,
            cursorColor: self.cursorColor,
            disabledAlpha: self.disabledAlpha,
            endContentColor: self.endContentColor,
            backgroundColorFocused: self.backgroundColorFocused,
            innerTitleTextAlignment: self.innerTitleTextAlignment,
            innerTitleTypography: self.innerTitleTypography,
            inputTextAlignment: self.inputTextAlignment,
            lineColor: self.lineColor,
            lineColorFocused: self.lineColorFocused,
            optionalTitleColor: self.optionalTitleColor,
            placeholderColor: self.placeholderColor,
            placeholderColorFocused: self.placeholderColorFocused,
            placeholderColorReadOnly: self.placeholderColorReadOnly,
            requiredIndicatorColor: self.requiredIndicatorColor,
            startContentColor: self.startContentColor,
            textAfterColor: self.textAfterColor,
            textBeforeColor: self.textBeforeColor,
            textColor: self.textColor,
            textColorFocused: self.textColorFocused,
            textColorReadOnly: self.textColorReadOnly,
            textTypography: self.textTypography,
            titleColor: self.titleColor,
            titleTextAlignment: self.titleTextAlignment,
            titleTypography: titleTypography
        )
    }

    func applyColorVariation(variation: TextAreaAppearance) -> TextAreaAppearance {
        return TextAreaAppearance(
            size: self.size,
            backgroundColor: variation.backgroundColor,
            backgroundColorReadOnly: variation.backgroundColorReadOnly,
            borderColor: variation.borderColor,
            captionColor: variation.captionColor,
            captionColorFocused: variation.captionColorFocused,
            captionColorReadOnly: variation.captionColorReadOnly,
            captionTypography: self.captionTypography,
            counterColor: variation.counterColor,
            counterColorReadOnly: variation.counterColorReadOnly,
            counterTypography: self.counterTypography,
            cursorColor: variation.cursorColor,
            disabledAlpha: variation.disabledAlpha,
            endContentColor: variation.endContentColor,
            backgroundColorFocused: variation.backgroundColorFocused,
            innerTitleTextAlignment: self.innerTitleTextAlignment,
            innerTitleTypography: self.innerTitleTypography,
            inputTextAlignment: self.inputTextAlignment,
            lineColor: variation.lineColor,
            lineColorFocused: variation.lineColorFocused,
            optionalTitleColor: variation.optionalTitleColor,
            placeholderColor: variation.placeholderColor,
            placeholderColorFocused: variation.placeholderColorFocused,
            placeholderColorReadOnly: variation.placeholderColorReadOnly,
            requiredIndicatorColor: variation.requiredIndicatorColor,
            startContentColor: variation.startContentColor,
            textAfterColor: variation.textAfterColor,
            textBeforeColor: variation.textBeforeColor,
            textColor: variation.textColor,
            textColorFocused: variation.textColorFocused,
            textColorReadOnly: variation.textColorReadOnly,
            textTypography: self.textTypography,
            titleColor: variation.titleColor,
            titleTextAlignment: self.titleTextAlignment,
            titleTypography: self.titleTypography
        )
    }
}
