name: 'Get release changelog'

description: 'Returns release changelog'

inputs:
  fromTag:
    description: 'Тэг, название ветки или хэш коммита'
    required: false
  toTag:
    description: 'Тэг, название ветки или хэш коммита'
    required: false


outputs:
  changelog:
    description: "Processed changelog"
    value: ${{ steps.changelog.outputs.changelog }}
  changelog_json:
    description: "Processed changelog json"
    value: ${{ steps.changelog.outputs.changelogJson }}
  pull_requests:
    description: "Pull requests"
    value: ${{ steps.github_release.outputs.pull_requests }}

runs:
  using: "composite"
  steps:
    - name: Compute envs
      shell: bash
      run: |
        if [ -z "${{ inputs.fromTag }}" ]; then
          FROM_TAG=$(git tag --sort=-creatordate | grep '^release-' | sed -n '2p')
        else
          FROM_TAG="${{ inputs.fromTag }}"
        fi

        if [ -z "${{ inputs.toTag }}" ]; then
          TO_TAG="HEAD"
        else
          TO_TAG="${{ inputs.toTag }}"
        fi

        echo "FROM_TAG=$FROM_TAG" >> $GITHUB_ENV
        echo "TO_TAG=$TO_TAG" >> $GITHUB_ENV
        echo "FROM_TAG = $FROM_TAG and TO_TAG = $TO_TAG"
        DATE=$(date +'%d.%m.%Y')
        echo "DATE=$DATE" >> $GITHUB_ENV
        echo "FILE=${{ github.workspace }}/changelog_artifacts.md" >> $GITHUB_ENV

    - name: Build Changelog
      id: github_release
      uses: mikepenz/release-changelog-builder-action@v4.1.0
      with:
        fromTag: ${{ env.FROM_TAG }}
        toTag:  ${{ env.TO_TAG }}
        configuration: "./.github/changelog-builder-config.json"

    - name: Install dependencies
      shell: bash
      run: |
        cd .github/actions/preprocessing-release-changelog
        npm ci

    - name: Processing changelog data
      id: changelog
      uses: ./.github/actions/preprocessing-release-changelog
      with:
        data: |
          ${{ steps.github_release.outputs.changelog }}

    - name: Create "changelog_artifacts.md"
      shell: bash
      run: |
        cat > "${{ env.FILE }}" <<EOF
        ${{ steps.changelog.outputs.changelog }}
        EOF   

    - name: Debug print changelog_artifacts.md
      shell: bash
      run: |
        echo "🔍 Contents of changelog_artifacts.md:"
        cat "${{ env.FILE }}"
        echo ""
        echo "🔍 Raw changelog from mikepenz action:"
        echo "${{ steps.github_release.outputs.changelog }}"
        echo ""
        echo "🔍 Pull requests from mikepenz action:"
        echo "${{ steps.github_release.outputs.pull_requests }}"
        echo ""
        echo "🔍 FROM_TAG: ${{ env.FROM_TAG }}"
        echo "🔍 TO_TAG: ${{ env.TO_TAG }}"
        echo "🔍 Git log between tags:"
        git log --oneline "${{ env.FROM_TAG }}".."${{ env.TO_TAG }}"
        echo ""
        echo "🔍 Current branch:"
        git branch --show-current
        echo "🔍 Available branches:"
        git branch -a
        echo ""
        echo "🔍 Commits with PR numbers:"
        git log --oneline "${{ env.FROM_TAG }}".."${{ env.TO_TAG }}" | grep -E "#[0-9]" || echo "No PR numbers found"
        echo ""
        echo "🔍 All commits in range:"
        git log --oneline "${{ env.FROM_TAG }}".."${{ env.TO_TAG }}"
        echo ""
        echo "🔍 GitHub repository context:"
        echo "Repository: ${{ github.repository }}"
        echo "Ref: ${{ github.ref }}"
        echo "Event name: ${{ github.event_name }}"

    - name: Upload "changelog_artifacts.md"
      if: false
      uses: actions/upload-artifact@master
      with:
        name: release-changelog-artifacts
        path: ${{ env.FILE }}