name: Build Debug / Build debug artifacts

on:
  pull_request:
  
concurrency:
  # New commit on branch cancels running workflows of the same branch
  group: ${{ github.workflow }}-${{ github.head_ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: macos-latest
    environment: sdds

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Xcode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: 'latest'
          
      - name: Install the Apple certificate and provisioning profile
        uses: ./.github/actions/install-certficates

      - name: Run build script
        run: |
          chmod +x ./scripts/build.sh
          ./scripts/build.sh

      - name: Upload XCFrameworks as Artifact
        uses: actions/upload-artifact@v4.1.0
        with:
          name: xcframeworks
          path: build/**
