name: 'Build and Publish SDDS Components'

on:
  push:
    tags:
      - "SDDS-v[0-9]+.[0-9]+.[0-9]+"

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref }}
  cancel-in-progress: true

jobs:
  build-and-publish:
    name: Build and Publish
    runs-on: macos-latest
    environment: sdds
    strategy:
      matrix:
        module: 
          - name: SDDSComponents
            project_path: SDDSComponents/SDDSComponents.xcodeproj
          - name: SDDSThemeCore
            project_path: SDDSThemeBuilder/SDDSThemeBuilder.xcodeproj

    steps:
      - name: Checkout the code
        uses: actions/checkout@v4
        
      - name: Set up Xcode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: 'latest'
          
      - name: Install the Apple certificate and provisioning profile
        env:
          BUILD_CERTIFICATE_BASE64: ${{ secrets.BUILD_CERTIFICATE_BASE64 }}
          P12_PASSWORD: ${{ secrets.P12_PASSWORD }}
          BUILD_PROVISION_PROFILE_BASE64: ${{ secrets.BUILD_PROVISION_PROFILE_BASE64 }}
          KEYCHAIN_PASSWORD: ${{ secrets.KEYCHAIN_PASSWORD }}
        run: |
          chmod +x ./scripts/install_certificate_and_profile.sh

      - name: Install dependencies
        run: gem install xcodeproj

      - name: Run build script for ${{ matrix.module.name }}
        run: |
          chmod +x ./scripts/build_xcframeworks.rb
          ruby ./scripts/build_xcframeworks.rb -d . -p ${{ matrix.module.project_path }} -m ${{ matrix.module.name }}

      - name: Generate ${{ matrix.module.name }} zip
        id: zip_artifact
        run: |
           TAG_NAME=${GITHUB_REF#refs/tags/}
           cd ${{ matrix.module.name }}/build
           zip -r ../../${{ matrix.module.name }}-${TAG_NAME}.zip .
           cd ../..
           echo "::set-output name=zip_path::${{ matrix.module.name }}-${TAG_NAME}.zip"

      - name: Release ${{ matrix.module.name }}
        uses: softprops/action-gh-release@v2
        with:
          files: ${{ steps.zip_artifact.outputs.zip_path }}
          tag_name: ${{ github.ref_name }}
          token: ${{ secrets.GH_TOKEN }}
