name: 'Publish icons Release'

on:
  push:
    tags:
      - "SDDSIcons-v[0-9]+.[0-9]+.[0-9]+"

concurrency:
  # New commit on branch cancels running workflows of the same branch
  group: ${{ github.workflow }}-${{ github.head_ref }}
  cancel-in-progress: true

jobs:
  generate-distribution:
    name: Generate icons distribution zip
    runs-on: macos-latest
    environment: sdds
    steps:
      - name: Checkout the code
        uses: actions/checkout@v4

      - name: Set up Xcode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: 'latest'
          
      - name: Install the Apple certificate and provisioning profile
        env:
          BUILD_CERTIFICATE_BASE64: ${{ secrets.BUILD_CERTIFICATE_BASE64 }}
          P12_PASSWORD: ${{ secrets.P12_PASSWORD }}
          BUILD_PROVISION_PROFILE_BASE64: ${{ secrets.BUILD_PROVISION_PROFILE_BASE64 }}
          KEYCHAIN_PASSWORD: ${{ secrets.KEYCHAIN_PASSWORD }}
        run: |
          .chmod +x ./scripts/install_certificate_and_profile.sh

      - name: Build SDDSIcons
        run: |
          TAG_NAME=${GITHUB_REF#refs/tags/}
          xcodebuild -project SDDSIcons/SDDSIcons.xcodeproj -scheme "Build XCFramework"
          
      - name: Generate distribution zip
        id: zip_artifact
        run: |
           TAG_NAME=${GITHUB_REF#refs/tags/}
           echo "Tag name: $TAG_NAME"
           cd SDDSIcons
           mv build $TAG_NAME
           zip -r ./../$TAG_NAME.zip $TAG_NAME/SDDSIcons.xcframework
           echo "::set-output name=zip_path::${TAG_NAME}.zip"
           echo "::set-output name=release_title::${TAG_NAME}"

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: ${{ steps.zip_artifact.outputs.zip_path }}
          tag_name: ${{ steps.zip_artifact.outputs.release_title }}
          token: ${{ secrets.GH_TOKEN }}
