name: Build and Deploy to TestFlight

on:
  push:
    branches:
      - feature/vsdimitraki/auto-publish-sandbox-testflight
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Set up Xcode
        uses: actions/setup-xcode@v2
        with:
          xcode-version: 'latest'
          
      - name: Install the Apple certificate and provisioning profile
        env:
          BUILD_CERTIFICATE_BASE64: ${{ secrets.BUILD_CERTIFICATE_BASE64 }}
          P12_PASSWORD: ${{ secrets.P12_PASSWORD }}
          BUILD_PROVISION_PROFILE_BASE64: ${{ secrets.BUILD_PROVISION_PROFILE_BASE64 }}
          KEYCHAIN_PASSWORD: ${{ secrets.KEYCHAIN_PASSWORD }}
        run: |
          ./scripts/install_certificate_and_profile.sh
    
      - name: Run and build script
        run: |
          ./scripts/build_xcframeworks.rb -d . -w SDDS.xcworkspace

      - name: Upload XCFrameworks as Artifact
        uses: actions/upload-artifact@v4.1.0
        with:
          name: xcframeworks
          path: build/**
          
      - name: Install Fastlane and initialize
        run: |
         gem install fastlane -NV
         fastlane init

